// ------------------------------------------------------------
// 
// File Name: C:\UBC Summer 2021\gitproject\ELEC391_Final_Project\mike\V_Normal_RC\Filter_for_16PSK\hdlcoder\transmitter1\gm_gm_Modulation_test\FIR_Interpolation
// Created: 2021-06-15 22:33:09
// Generated by MATLAB 9.10 and HDL Coder 3.18
// 
// ------------------------------------------------------------
// 
// 
// ------------------------------------------------------------
// 
// Module: FIR_Interpolation
// Source Path: /FIR_Interpolation
// 
// ------------------------------------------------------------
// 
// HDL Implementation    : Fully parallel
// Folding Factor        : 1
// Multipliers           : 11



`timescale 1 ns / 1 ns

module FIR_Interpolation
               (
                clk,
                enb_1_1_1,
                reset,
                FIR_Interpolation_in,
                FIR_Interpolation_out
                );

  input   clk; 
  input   enb_1_1_1; 
  input   reset; 
  input   signed [63:0] FIR_Interpolation_in; //sfix64
  output  signed [63:0] FIR_Interpolation_out; //sfix64

////////////////////////////////////////////////////////////////
//Module Architecture: FIR_Interpolation
////////////////////////////////////////////////////////////////
  // Local Functions
  // Type Definitions
  // Constants
  parameter signed [63:0] coeffphase1_1 = 64'hFE769190700B3ED0; //sfix64_En64
  parameter signed [63:0] coeffphase1_2 = 64'h027A065B4DA622E0; //sfix64_En64
  parameter signed [63:0] coeffphase1_3 = 64'hFC9593D0781F3820; //sfix64_En64
  parameter signed [63:0] coeffphase1_4 = 64'h0437A42B5A7B2680; //sfix64_En64
  parameter signed [63:0] coeffphase1_5 = 64'hFB3E3DA86835D080; //sfix64_En64
  parameter signed [63:0] coeffphase1_6 = 64'h5F797D0199F19000; //sfix64_En64
  parameter signed [63:0] coeffphase1_7 = 64'hFB3E3DA86835D080; //sfix64_En64
  parameter signed [63:0] coeffphase1_8 = 64'h0437A42B5A7B2680; //sfix64_En64
  parameter signed [63:0] coeffphase1_9 = 64'hFC9593D0781F3820; //sfix64_En64
  parameter signed [63:0] coeffphase1_10 = 64'h027A065B4DA622E0; //sfix64_En64
  parameter signed [63:0] coeffphase1_11 = 64'hFE769190700B3ED0; //sfix64_En64
  parameter signed [63:0] coeffphase2_1 = 64'hFEAEDE377A722920; //sfix64_En64
  parameter signed [63:0] coeffphase2_2 = 64'h017B7FC66C68BB10; //sfix64_En64
  parameter signed [63:0] coeffphase2_3 = 64'hFEF352720A5DEAA0; //sfix64_En64
  parameter signed [63:0] coeffphase2_4 = 64'hFF41133814DF92A8; //sfix64_En64
  parameter signed [63:0] coeffphase2_5 = 64'h0798985725FDFA00; //sfix64_En64
  parameter signed [63:0] coeffphase2_6 = 64'h5CB41E381266AC00; //sfix64_En64
  parameter signed [63:0] coeffphase2_7 = 64'hF293889D61922A80; //sfix64_En64
  parameter signed [63:0] coeffphase2_8 = 64'h07B66C1FDCB06880; //sfix64_En64
  parameter signed [63:0] coeffphase2_9 = 64'hFB23833F72D16A40; //sfix64_En64
  parameter signed [63:0] coeffphase2_10 = 64'h02DFA6ED4F81E400; //sfix64_En64
  parameter signed [63:0] coeffphase2_11 = 64'h0000000000000000; //sfix64_En64
  parameter signed [63:0] coeffphase3_1 = 64'hFF41D31F53FE45A0; //sfix64_En64
  parameter signed [63:0] coeffphase3_2 = 64'hFFFFFFFFFFFFFF74; //sfix64_En64
  parameter signed [63:0] coeffphase3_3 = 64'h01ECBA178F1BBFB0; //sfix64_En64
  parameter signed [63:0] coeffphase3_4 = 64'hF97992DF3C225EC0; //sfix64_En64
  parameter signed [63:0] coeffphase3_5 = 64'h16D67DF2AD87B200; //sfix64_En64
  parameter signed [63:0] coeffphase3_6 = 64'h54AFFC0C98C4D800; //sfix64_En64
  parameter signed [63:0] coeffphase3_7 = 64'hEDE4FEE1F5597000; //sfix64_En64
  parameter signed [63:0] coeffphase3_8 = 64'h0968E31DD815DE80; //sfix64_En64
  parameter signed [63:0] coeffphase3_9 = 64'hFABACF3E26B94D40; //sfix64_En64
  parameter signed [63:0] coeffphase3_10 = 64'h02AFD295055B4280; //sfix64_En64
  parameter signed [63:0] coeffphase3_11 = 64'h0000000000000000; //sfix64_En64
  parameter signed [63:0] coeffphase4_1 = 64'h001CEF4D6CB5DE34; //sfix64_En64
  parameter signed [63:0] coeffphase4_2 = 64'hFE4191827BEEDDE0; //sfix64_En64
  parameter signed [63:0] coeffphase4_3 = 64'h050757FC26E45C80; //sfix64_En64
  parameter signed [63:0] coeffphase4_4 = 64'hF3CB1049F3277580; //sfix64_En64
  parameter signed [63:0] coeffphase4_5 = 64'h27BD4BA7219E1600; //sfix64_En64
  parameter signed [63:0] coeffphase4_6 = 64'h48471B6ABB87FC00; //sfix64_En64
  parameter signed [63:0] coeffphase4_7 = 64'hED0075609038A800; //sfix64_En64
  parameter signed [63:0] coeffphase4_8 = 64'h094E66BA1ED25780; //sfix64_En64
  parameter signed [63:0] coeffphase4_9 = 64'hFB483162541BB9C0; //sfix64_En64
  parameter signed [63:0] coeffphase4_10 = 64'h0208CF2E09D0C040; //sfix64_En64
  parameter signed [63:0] coeffphase4_11 = 64'h0000000000000000; //sfix64_En64
  parameter signed [63:0] coeffphase5_1 = 64'h011AD608386CC900; //sfix64_En64
  parameter signed [63:0] coeffphase5_2 = 64'hFC90DED27EC77640; //sfix64_En64
  parameter signed [63:0] coeffphase5_3 = 64'h07AF282DCFC7C640; //sfix64_En64
  parameter signed [63:0] coeffphase5_4 = 64'hEF46CE328BB12100; //sfix64_En64
  parameter signed [63:0] coeffphase5_5 = 64'h38C53EC640753800; //sfix64_En64
  parameter signed [63:0] coeffphase5_6 = 64'h38C53EC640753800; //sfix64_En64
  parameter signed [63:0] coeffphase5_7 = 64'hEF46CE328BB12100; //sfix64_En64
  parameter signed [63:0] coeffphase5_8 = 64'h07AF282DCFC7C640; //sfix64_En64
  parameter signed [63:0] coeffphase5_9 = 64'hFC90DED27EC77640; //sfix64_En64
  parameter signed [63:0] coeffphase5_10 = 64'h011AD608386CC900; //sfix64_En64
  parameter signed [63:0] coeffphase5_11 = 64'h0000000000000000; //sfix64_En64
  parameter signed [63:0] coeffphase6_1 = 64'h0208CF2E09D0C040; //sfix64_En64
  parameter signed [63:0] coeffphase6_2 = 64'hFB483162541BB9C0; //sfix64_En64
  parameter signed [63:0] coeffphase6_3 = 64'h094E66BA1ED25780; //sfix64_En64
  parameter signed [63:0] coeffphase6_4 = 64'hED0075609038A800; //sfix64_En64
  parameter signed [63:0] coeffphase6_5 = 64'h48471B6ABB87FC00; //sfix64_En64
  parameter signed [63:0] coeffphase6_6 = 64'h27BD4BA7219E1600; //sfix64_En64
  parameter signed [63:0] coeffphase6_7 = 64'hF3CB1049F3277580; //sfix64_En64
  parameter signed [63:0] coeffphase6_8 = 64'h050757FC26E45C80; //sfix64_En64
  parameter signed [63:0] coeffphase6_9 = 64'hFE4191827BEEDDE0; //sfix64_En64
  parameter signed [63:0] coeffphase6_10 = 64'h001CEF4D6CB5DE34; //sfix64_En64
  parameter signed [63:0] coeffphase6_11 = 64'h0000000000000000; //sfix64_En64
  parameter signed [63:0] coeffphase7_1 = 64'h02AFD295055B4280; //sfix64_En64
  parameter signed [63:0] coeffphase7_2 = 64'hFABACF3E26B94D40; //sfix64_En64
  parameter signed [63:0] coeffphase7_3 = 64'h0968E31DD815DE80; //sfix64_En64
  parameter signed [63:0] coeffphase7_4 = 64'hEDE4FEE1F5597000; //sfix64_En64
  parameter signed [63:0] coeffphase7_5 = 64'h54AFFC0C98C4D800; //sfix64_En64
  parameter signed [63:0] coeffphase7_6 = 64'h16D67DF2AD87B200; //sfix64_En64
  parameter signed [63:0] coeffphase7_7 = 64'hF97992DF3C225EC0; //sfix64_En64
  parameter signed [63:0] coeffphase7_8 = 64'h01ECBA178F1BBFB0; //sfix64_En64
  parameter signed [63:0] coeffphase7_9 = 64'hFFFFFFFFFFFFFF74; //sfix64_En64
  parameter signed [63:0] coeffphase7_10 = 64'hFF41D31F53FE45A0; //sfix64_En64
  parameter signed [63:0] coeffphase7_11 = 64'h0000000000000000; //sfix64_En64
  parameter signed [63:0] coeffphase8_1 = 64'h02DFA6ED4F81E400; //sfix64_En64
  parameter signed [63:0] coeffphase8_2 = 64'hFB23833F72D16A40; //sfix64_En64
  parameter signed [63:0] coeffphase8_3 = 64'h07B66C1FDCB06880; //sfix64_En64
  parameter signed [63:0] coeffphase8_4 = 64'hF293889D61922A80; //sfix64_En64
  parameter signed [63:0] coeffphase8_5 = 64'h5CB41E381266AC00; //sfix64_En64
  parameter signed [63:0] coeffphase8_6 = 64'h0798985725FDFA00; //sfix64_En64
  parameter signed [63:0] coeffphase8_7 = 64'hFF41133814DF92A8; //sfix64_En64
  parameter signed [63:0] coeffphase8_8 = 64'hFEF352720A5DEAA0; //sfix64_En64
  parameter signed [63:0] coeffphase8_9 = 64'h017B7FC66C68BB10; //sfix64_En64
  parameter signed [63:0] coeffphase8_10 = 64'hFEAEDE377A722920; //sfix64_En64
  parameter signed [63:0] coeffphase8_11 = 64'h0000000000000000; //sfix64_En64

  // Signals
  reg  [2:0] cur_count; // ufix3
  wire phase_7; // boolean
  reg  signed [63:0] delay_pipeline [0:9] ; // sfix64
  wire signed [63:0] product; // sfix64
  wire signed [63:0] product_mux; // sfix64_En64
  wire signed [127:0] mul_temp; // sfix128_En64
  wire signed [63:0] product_1; // sfix64
  wire signed [63:0] product_mux_1; // sfix64_En64
  wire signed [127:0] mul_temp_1; // sfix128_En64
  wire signed [63:0] product_2; // sfix64
  wire signed [63:0] product_mux_2; // sfix64_En64
  wire signed [127:0] mul_temp_2; // sfix128_En64
  wire signed [63:0] product_3; // sfix64
  wire signed [63:0] product_mux_3; // sfix64_En64
  wire signed [127:0] mul_temp_3; // sfix128_En64
  wire signed [63:0] product_4; // sfix64
  wire signed [63:0] product_mux_4; // sfix64_En64
  wire signed [127:0] mul_temp_4; // sfix128_En64
  wire signed [63:0] product_5; // sfix64
  wire signed [63:0] product_mux_5; // sfix64_En64
  wire signed [127:0] mul_temp_5; // sfix128_En64
  wire signed [63:0] product_6; // sfix64
  wire signed [63:0] product_mux_6; // sfix64_En64
  wire signed [127:0] mul_temp_6; // sfix128_En64
  wire signed [63:0] product_7; // sfix64
  wire signed [63:0] product_mux_7; // sfix64_En64
  wire signed [127:0] mul_temp_7; // sfix128_En64
  wire signed [63:0] product_8; // sfix64
  wire signed [63:0] product_mux_8; // sfix64_En64
  wire signed [127:0] mul_temp_8; // sfix128_En64
  wire signed [63:0] product_9; // sfix64
  wire signed [63:0] product_mux_9; // sfix64_En64
  wire signed [127:0] mul_temp_9; // sfix128_En64
  wire signed [63:0] product_10; // sfix64
  wire signed [63:0] product_mux_10; // sfix64_En64
  wire signed [127:0] mul_temp_10; // sfix128_En64
  wire signed [63:0] sum1; // sfix64
  wire signed [63:0] add_cast; // sfix64
  wire signed [63:0] add_cast_1; // sfix64
  wire signed [64:0] add_temp; // sfix65
  wire signed [63:0] sum2; // sfix64
  wire signed [63:0] add_cast_2; // sfix64
  wire signed [63:0] add_cast_3; // sfix64
  wire signed [64:0] add_temp_1; // sfix65
  wire signed [63:0] sum3; // sfix64
  wire signed [63:0] add_cast_4; // sfix64
  wire signed [63:0] add_cast_5; // sfix64
  wire signed [64:0] add_temp_2; // sfix65
  wire signed [63:0] sum4; // sfix64
  wire signed [63:0] add_cast_6; // sfix64
  wire signed [63:0] add_cast_7; // sfix64
  wire signed [64:0] add_temp_3; // sfix65
  wire signed [63:0] sum5; // sfix64
  wire signed [63:0] add_cast_8; // sfix64
  wire signed [63:0] add_cast_9; // sfix64
  wire signed [64:0] add_temp_4; // sfix65
  wire signed [63:0] sum6; // sfix64
  wire signed [63:0] add_cast_10; // sfix64
  wire signed [63:0] add_cast_11; // sfix64
  wire signed [64:0] add_temp_5; // sfix65
  wire signed [63:0] sum7; // sfix64
  wire signed [63:0] add_cast_12; // sfix64
  wire signed [63:0] add_cast_13; // sfix64
  wire signed [64:0] add_temp_6; // sfix65
  wire signed [63:0] sum8; // sfix64
  wire signed [63:0] add_cast_14; // sfix64
  wire signed [63:0] add_cast_15; // sfix64
  wire signed [64:0] add_temp_7; // sfix65
  wire signed [63:0] sum9; // sfix64
  wire signed [63:0] add_cast_16; // sfix64
  wire signed [63:0] add_cast_17; // sfix64
  wire signed [64:0] add_temp_8; // sfix65
  wire signed [63:0] sum10; // sfix64
  wire signed [63:0] add_cast_18; // sfix64
  wire signed [63:0] add_cast_19; // sfix64
  wire signed [64:0] add_temp_9; // sfix65
  reg  signed [63:0] regout; // sfix64
  wire signed [63:0] muxout; // sfix64

  // Block Statements
  always @ (posedge clk or posedge reset)
    begin: ce_output
      if (reset == 1'b1) begin
        cur_count <= 3'b000;
      end
      else begin
        if (enb_1_1_1 == 1'b1) begin
          if (cur_count >= 3'b111) begin
            cur_count <= 3'b000;
          end
          else begin
            cur_count <= cur_count + 3'b001;
          end
        end
      end
    end // ce_output

  assign  phase_7 = (cur_count == 3'b111 && enb_1_1_1 == 1'b1) ? 1'b1 : 1'b0;

  //   ---------------- Delay Registers ----------------

  always @( posedge clk or posedge reset)
    begin: Delay_Pipeline_process
      if (reset == 1'b1) begin
        delay_pipeline[0] <= 0;
        delay_pipeline[1] <= 0;
        delay_pipeline[2] <= 0;
        delay_pipeline[3] <= 0;
        delay_pipeline[4] <= 0;
        delay_pipeline[5] <= 0;
        delay_pipeline[6] <= 0;
        delay_pipeline[7] <= 0;
        delay_pipeline[8] <= 0;
        delay_pipeline[9] <= 0;
      end
      else begin
        if (phase_7 == 1'b1) begin
          delay_pipeline[0] <= FIR_Interpolation_in;
          delay_pipeline[1] <= delay_pipeline[0];
          delay_pipeline[2] <= delay_pipeline[1];
          delay_pipeline[3] <= delay_pipeline[2];
          delay_pipeline[4] <= delay_pipeline[3];
          delay_pipeline[5] <= delay_pipeline[4];
          delay_pipeline[6] <= delay_pipeline[5];
          delay_pipeline[7] <= delay_pipeline[6];
          delay_pipeline[8] <= delay_pipeline[7];
          delay_pipeline[9] <= delay_pipeline[8];
        end
      end
    end // Delay_Pipeline_process


  assign product_mux = (cur_count == 3'b000) ? coeffphase1_11 :
                      (cur_count == 3'b001) ? coeffphase2_11 :
                      (cur_count == 3'b010) ? coeffphase3_11 :
                      (cur_count == 3'b011) ? coeffphase4_11 :
                      (cur_count == 3'b100) ? coeffphase5_11 :
                      (cur_count == 3'b101) ? coeffphase6_11 :
                      (cur_count == 3'b110) ? coeffphase7_11 :
                      coeffphase8_11;
  assign mul_temp = delay_pipeline[9] * product_mux;
  assign product = mul_temp[127:64];

  assign product_mux_1 = (cur_count == 3'b000) ? coeffphase1_10 :
                        (cur_count == 3'b001) ? coeffphase2_10 :
                        (cur_count == 3'b010) ? coeffphase3_10 :
                        (cur_count == 3'b011) ? coeffphase4_10 :
                        (cur_count == 3'b100) ? coeffphase5_10 :
                        (cur_count == 3'b101) ? coeffphase6_10 :
                        (cur_count == 3'b110) ? coeffphase7_10 :
                        coeffphase8_10;
  assign mul_temp_1 = delay_pipeline[8] * product_mux_1;
  assign product_1 = mul_temp_1[127:64];

  assign product_mux_2 = (cur_count == 3'b000) ? coeffphase1_9 :
                        (cur_count == 3'b001) ? coeffphase2_9 :
                        (cur_count == 3'b010) ? coeffphase3_9 :
                        (cur_count == 3'b011) ? coeffphase4_9 :
                        (cur_count == 3'b100) ? coeffphase5_9 :
                        (cur_count == 3'b101) ? coeffphase6_9 :
                        (cur_count == 3'b110) ? coeffphase7_9 :
                        coeffphase8_9;
  assign mul_temp_2 = delay_pipeline[7] * product_mux_2;
  assign product_2 = mul_temp_2[127:64];

  assign product_mux_3 = (cur_count == 3'b000) ? coeffphase1_8 :
                        (cur_count == 3'b001) ? coeffphase2_8 :
                        (cur_count == 3'b010) ? coeffphase3_8 :
                        (cur_count == 3'b011) ? coeffphase4_8 :
                        (cur_count == 3'b100) ? coeffphase5_8 :
                        (cur_count == 3'b101) ? coeffphase6_8 :
                        (cur_count == 3'b110) ? coeffphase7_8 :
                        coeffphase8_8;
  assign mul_temp_3 = delay_pipeline[6] * product_mux_3;
  assign product_3 = mul_temp_3[127:64];

  assign product_mux_4 = (cur_count == 3'b000) ? coeffphase1_7 :
                        (cur_count == 3'b001) ? coeffphase2_7 :
                        (cur_count == 3'b010) ? coeffphase3_7 :
                        (cur_count == 3'b011) ? coeffphase4_7 :
                        (cur_count == 3'b100) ? coeffphase5_7 :
                        (cur_count == 3'b101) ? coeffphase6_7 :
                        (cur_count == 3'b110) ? coeffphase7_7 :
                        coeffphase8_7;
  assign mul_temp_4 = delay_pipeline[5] * product_mux_4;
  assign product_4 = mul_temp_4[127:64];

  assign product_mux_5 = (cur_count == 3'b000) ? coeffphase1_6 :
                        (cur_count == 3'b001) ? coeffphase2_6 :
                        (cur_count == 3'b010) ? coeffphase3_6 :
                        (cur_count == 3'b011) ? coeffphase4_6 :
                        (cur_count == 3'b100) ? coeffphase5_6 :
                        (cur_count == 3'b101) ? coeffphase6_6 :
                        (cur_count == 3'b110) ? coeffphase7_6 :
                        coeffphase8_6;
  assign mul_temp_5 = delay_pipeline[4] * product_mux_5;
  assign product_5 = mul_temp_5[127:64];

  assign product_mux_6 = (cur_count == 3'b000) ? coeffphase1_5 :
                        (cur_count == 3'b001) ? coeffphase2_5 :
                        (cur_count == 3'b010) ? coeffphase3_5 :
                        (cur_count == 3'b011) ? coeffphase4_5 :
                        (cur_count == 3'b100) ? coeffphase5_5 :
                        (cur_count == 3'b101) ? coeffphase6_5 :
                        (cur_count == 3'b110) ? coeffphase7_5 :
                        coeffphase8_5;
  assign mul_temp_6 = delay_pipeline[3] * product_mux_6;
  assign product_6 = mul_temp_6[127:64];

  assign product_mux_7 = (cur_count == 3'b000) ? coeffphase1_4 :
                        (cur_count == 3'b001) ? coeffphase2_4 :
                        (cur_count == 3'b010) ? coeffphase3_4 :
                        (cur_count == 3'b011) ? coeffphase4_4 :
                        (cur_count == 3'b100) ? coeffphase5_4 :
                        (cur_count == 3'b101) ? coeffphase6_4 :
                        (cur_count == 3'b110) ? coeffphase7_4 :
                        coeffphase8_4;
  assign mul_temp_7 = delay_pipeline[2] * product_mux_7;
  assign product_7 = mul_temp_7[127:64];

  assign product_mux_8 = (cur_count == 3'b000) ? coeffphase1_3 :
                        (cur_count == 3'b001) ? coeffphase2_3 :
                        (cur_count == 3'b010) ? coeffphase3_3 :
                        (cur_count == 3'b011) ? coeffphase4_3 :
                        (cur_count == 3'b100) ? coeffphase5_3 :
                        (cur_count == 3'b101) ? coeffphase6_3 :
                        (cur_count == 3'b110) ? coeffphase7_3 :
                        coeffphase8_3;
  assign mul_temp_8 = delay_pipeline[1] * product_mux_8;
  assign product_8 = mul_temp_8[127:64];

  assign product_mux_9 = (cur_count == 3'b000) ? coeffphase1_2 :
                        (cur_count == 3'b001) ? coeffphase2_2 :
                        (cur_count == 3'b010) ? coeffphase3_2 :
                        (cur_count == 3'b011) ? coeffphase4_2 :
                        (cur_count == 3'b100) ? coeffphase5_2 :
                        (cur_count == 3'b101) ? coeffphase6_2 :
                        (cur_count == 3'b110) ? coeffphase7_2 :
                        coeffphase8_2;
  assign mul_temp_9 = delay_pipeline[0] * product_mux_9;
  assign product_9 = mul_temp_9[127:64];

  assign product_mux_10 = (cur_count == 3'b000) ? coeffphase1_1 :
                         (cur_count == 3'b001) ? coeffphase2_1 :
                         (cur_count == 3'b010) ? coeffphase3_1 :
                         (cur_count == 3'b011) ? coeffphase4_1 :
                         (cur_count == 3'b100) ? coeffphase5_1 :
                         (cur_count == 3'b101) ? coeffphase6_1 :
                         (cur_count == 3'b110) ? coeffphase7_1 :
                         coeffphase8_1;
  assign mul_temp_10 = FIR_Interpolation_in * product_mux_10;
  assign product_10 = mul_temp_10[127:64];

  assign add_cast = product_10;
  assign add_cast_1 = product_9;
  assign add_temp = add_cast + add_cast_1;
  assign sum1 = add_temp[63:0];

  assign add_cast_2 = sum1;
  assign add_cast_3 = product_8;
  assign add_temp_1 = add_cast_2 + add_cast_3;
  assign sum2 = add_temp_1[63:0];

  assign add_cast_4 = sum2;
  assign add_cast_5 = product_7;
  assign add_temp_2 = add_cast_4 + add_cast_5;
  assign sum3 = add_temp_2[63:0];

  assign add_cast_6 = sum3;
  assign add_cast_7 = product_6;
  assign add_temp_3 = add_cast_6 + add_cast_7;
  assign sum4 = add_temp_3[63:0];

  assign add_cast_8 = sum4;
  assign add_cast_9 = product_5;
  assign add_temp_4 = add_cast_8 + add_cast_9;
  assign sum5 = add_temp_4[63:0];

  assign add_cast_10 = sum5;
  assign add_cast_11 = product_4;
  assign add_temp_5 = add_cast_10 + add_cast_11;
  assign sum6 = add_temp_5[63:0];

  assign add_cast_12 = sum6;
  assign add_cast_13 = product_3;
  assign add_temp_6 = add_cast_12 + add_cast_13;
  assign sum7 = add_temp_6[63:0];

  assign add_cast_14 = sum7;
  assign add_cast_15 = product_2;
  assign add_temp_7 = add_cast_14 + add_cast_15;
  assign sum8 = add_temp_7[63:0];

  assign add_cast_16 = sum8;
  assign add_cast_17 = product_1;
  assign add_temp_8 = add_cast_16 + add_cast_17;
  assign sum9 = add_temp_8[63:0];

  assign add_cast_18 = sum9;
  assign add_cast_19 = product;
  assign add_temp_9 = add_cast_18 + add_cast_19;
  assign sum10 = add_temp_9[63:0];

  always @ (posedge clk or posedge reset)
    begin: DataHoldRegister_process
      if (reset == 1'b1) begin
        regout <= 0;
      end
      else begin
        if (enb_1_1_1 == 1'b1) begin
          regout <= sum10;
        end
      end
    end // DataHoldRegister_process

  assign muxout = (enb_1_1_1 == 1'b1) ? sum10 :
            regout;
  // Assignment Statements
  assign FIR_Interpolation_out = muxout;
endmodule  // FIR_Interpolation
