// -------------------------------------------------------------
// 
// File Name: C:\Users\huber\Downloads\hdlsrc\HDLAWGNGenerator\HDLAWGNGenerator\alphadBtoLinearConverter.v
// Created: 2021-06-06 18:19:42
// 
// Generated by MATLAB 9.10 and HDL Coder 3.18
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: alphadBtoLinearConverter
// Source Path: HDLAWGNGenerator/AWGNGenerator/ dBtoLinearConverter
// Hierarchy Level: 1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module alphadBtoLinearConverter
          (clk,
           reset,
           enb,
           snrdB,
           noiseVar);


  input   clk;
  input   reset;
  input   enb;
  input   signed [15:0] snrdB;  // sfix16_En9
  output  [21:0] noiseVar;  // ufix22_En18


  wire signed [31:0] Gain_out1;  // sfix32_En20
  wire signed [15:0] Gain_out1_1;  // int16
  wire signed [15:0] Constant_out1;  // int16
  wire signed [15:0] Add_out1;  // int16
  reg signed [15:0] Delay1_out1;  // int16
  wire [8:0] sqrt_noisePow_2_k;  // ufix9
  wire [21:0] sqrt_noisePow_2_1 [0:511];  // ufix22_En18 [512]
  wire [21:0] sqrt_noisePow_2_out1;  // ufix22_En18

  // Add Block is used to obtain integer index to Lookup Table


  assign Gain_out1 = 16'sb0101000000000000 * snrdB;



  assign Gain_out1_1 = ({{4{Gain_out1[31]}}, Gain_out1[31:20]}) + $signed({1'b0, Gain_out1[19] & (( ~ Gain_out1[31]) | (|Gain_out1[18:0]))});



  assign Constant_out1 = 16'sb0000000011001001;



  assign Add_out1 = Gain_out1_1 + Constant_out1;



  always @(posedge clk or posedge reset)
    begin : Delay1_process
      if (reset == 1'b1) begin
        Delay1_out1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          Delay1_out1 <= Add_out1;
        end
      end
    end



  assign sqrt_noisePow_2_1[0] = 22'b0000000000000000000000;
  assign sqrt_noisePow_2_1[1] = 22'b0111000100100011000110;
  assign sqrt_noisePow_2_1[2] = 22'b0110111111010111100100;
  assign sqrt_noisePow_2_1[3] = 22'b0110111010001111110100;
  assign sqrt_noisePow_2_1[4] = 22'b0110110101001011110101;
  assign sqrt_noisePow_2_1[5] = 22'b0110110000001011100011;
  assign sqrt_noisePow_2_1[6] = 22'b0110101011001110111011;
  assign sqrt_noisePow_2_1[7] = 22'b0110100110010101111100;
  assign sqrt_noisePow_2_1[8] = 22'b0110100001100000100001;
  assign sqrt_noisePow_2_1[9] = 22'b0110011100101110101010;
  assign sqrt_noisePow_2_1[10] = 22'b0110011000000000010011;
  assign sqrt_noisePow_2_1[11] = 22'b0110010011010101011001;
  assign sqrt_noisePow_2_1[12] = 22'b0110001110101101111010;
  assign sqrt_noisePow_2_1[13] = 22'b0110001010001001110011;
  assign sqrt_noisePow_2_1[14] = 22'b0110000101101001000011;
  assign sqrt_noisePow_2_1[15] = 22'b0110000001001011100110;
  assign sqrt_noisePow_2_1[16] = 22'b0101111100110001011010;
  assign sqrt_noisePow_2_1[17] = 22'b0101111000011010011101;
  assign sqrt_noisePow_2_1[18] = 22'b0101110100000110101100;
  assign sqrt_noisePow_2_1[19] = 22'b0101101111110110000110;
  assign sqrt_noisePow_2_1[20] = 22'b0101101011101000100111;
  assign sqrt_noisePow_2_1[21] = 22'b0101100111011110001101;
  assign sqrt_noisePow_2_1[22] = 22'b0101100011010110110111;
  assign sqrt_noisePow_2_1[23] = 22'b0101011111010010100001;
  assign sqrt_noisePow_2_1[24] = 22'b0101011011010001001010;
  assign sqrt_noisePow_2_1[25] = 22'b0101010111010010110000;
  assign sqrt_noisePow_2_1[26] = 22'b0101010011010111010000;
  assign sqrt_noisePow_2_1[27] = 22'b0101001111011110101001;
  assign sqrt_noisePow_2_1[28] = 22'b0101001011101000110111;
  assign sqrt_noisePow_2_1[29] = 22'b0101000111110101111010;
  assign sqrt_noisePow_2_1[30] = 22'b0101000100000101101111;
  assign sqrt_noisePow_2_1[31] = 22'b0101000000011000010011;
  assign sqrt_noisePow_2_1[32] = 22'b0100111100101101100110;
  assign sqrt_noisePow_2_1[33] = 22'b0100111001000101100100;
  assign sqrt_noisePow_2_1[34] = 22'b0100110101100000001101;
  assign sqrt_noisePow_2_1[35] = 22'b0100110001111101011101;
  assign sqrt_noisePow_2_1[36] = 22'b0100101110011101010100;
  assign sqrt_noisePow_2_1[37] = 22'b0100101010111111101110;
  assign sqrt_noisePow_2_1[38] = 22'b0100100111100100101100;
  assign sqrt_noisePow_2_1[39] = 22'b0100100100001100001001;
  assign sqrt_noisePow_2_1[40] = 22'b0100100000110110000101;
  assign sqrt_noisePow_2_1[41] = 22'b0100011101100010011111;
  assign sqrt_noisePow_2_1[42] = 22'b0100011010010001010011;
  assign sqrt_noisePow_2_1[43] = 22'b0100010111000010100000;
  assign sqrt_noisePow_2_1[44] = 22'b0100010011110110000101;
  assign sqrt_noisePow_2_1[45] = 22'b0100010000101011111111;
  assign sqrt_noisePow_2_1[46] = 22'b0100001101100100001110;
  assign sqrt_noisePow_2_1[47] = 22'b0100001010011110101111;
  assign sqrt_noisePow_2_1[48] = 22'b0100000111011011100001;
  assign sqrt_noisePow_2_1[49] = 22'b0100000100011010100001;
  assign sqrt_noisePow_2_1[50] = 22'b0100000001011011101111;
  assign sqrt_noisePow_2_1[51] = 22'b0011111110011111001001;
  assign sqrt_noisePow_2_1[52] = 22'b0011111011100100101101;
  assign sqrt_noisePow_2_1[53] = 22'b0011111000101100011010;
  assign sqrt_noisePow_2_1[54] = 22'b0011110101110110001101;
  assign sqrt_noisePow_2_1[55] = 22'b0011110011000010000111;
  assign sqrt_noisePow_2_1[56] = 22'b0011110000010000000100;
  assign sqrt_noisePow_2_1[57] = 22'b0011101101100000000011;
  assign sqrt_noisePow_2_1[58] = 22'b0011101010110010000011;
  assign sqrt_noisePow_2_1[59] = 22'b0011101000000110000011;
  assign sqrt_noisePow_2_1[60] = 22'b0011100101011100000001;
  assign sqrt_noisePow_2_1[61] = 22'b0011100010110011111100;
  assign sqrt_noisePow_2_1[62] = 22'b0011100000001101110001;
  assign sqrt_noisePow_2_1[63] = 22'b0011011101101001100001;
  assign sqrt_noisePow_2_1[64] = 22'b0011011011000111001000;
  assign sqrt_noisePow_2_1[65] = 22'b0011011000100110100111;
  assign sqrt_noisePow_2_1[66] = 22'b0011010110000111111011;
  assign sqrt_noisePow_2_1[67] = 22'b0011010011101011000100;
  assign sqrt_noisePow_2_1[68] = 22'b0011010001001111111111;
  assign sqrt_noisePow_2_1[69] = 22'b0011001110110110101100;
  assign sqrt_noisePow_2_1[70] = 22'b0011001100011111001001;
  assign sqrt_noisePow_2_1[71] = 22'b0011001010001001010110;
  assign sqrt_noisePow_2_1[72] = 22'b0011000111110101010000;
  assign sqrt_noisePow_2_1[73] = 22'b0011000101100010110110;
  assign sqrt_noisePow_2_1[74] = 22'b0011000011010010001000;
  assign sqrt_noisePow_2_1[75] = 22'b0011000001000011000100;
  assign sqrt_noisePow_2_1[76] = 22'b0010111110110101101001;
  assign sqrt_noisePow_2_1[77] = 22'b0010111100101001110101;
  assign sqrt_noisePow_2_1[78] = 22'b0010111010011111101000;
  assign sqrt_noisePow_2_1[79] = 22'b0010111000010111000000;
  assign sqrt_noisePow_2_1[80] = 22'b0010110110001111111100;
  assign sqrt_noisePow_2_1[81] = 22'b0010110100001010011011;
  assign sqrt_noisePow_2_1[82] = 22'b0010110010000110011011;
  assign sqrt_noisePow_2_1[83] = 22'b0010110000000011111101;
  assign sqrt_noisePow_2_1[84] = 22'b0010101110000010111110;
  assign sqrt_noisePow_2_1[85] = 22'b0010101100000011011110;
  assign sqrt_noisePow_2_1[86] = 22'b0010101010000101011010;
  assign sqrt_noisePow_2_1[87] = 22'b0010101000001000110100;
  assign sqrt_noisePow_2_1[88] = 22'b0010100110001101101000;
  assign sqrt_noisePow_2_1[89] = 22'b0010100100010011110111;
  assign sqrt_noisePow_2_1[90] = 22'b0010100010011011011111;
  assign sqrt_noisePow_2_1[91] = 22'b0010100000100100100000;
  assign sqrt_noisePow_2_1[92] = 22'b0010011110101110110111;
  assign sqrt_noisePow_2_1[93] = 22'b0010011100111010100101;
  assign sqrt_noisePow_2_1[94] = 22'b0010011011000111100111;
  assign sqrt_noisePow_2_1[95] = 22'b0010011001010101111110;
  assign sqrt_noisePow_2_1[96] = 22'b0010010111100101101001;
  assign sqrt_noisePow_2_1[97] = 22'b0010010101110110100101;
  assign sqrt_noisePow_2_1[98] = 22'b0010010100001000110011;
  assign sqrt_noisePow_2_1[99] = 22'b0010010010011100010001;
  assign sqrt_noisePow_2_1[100] = 22'b0010010000110000111111;
  assign sqrt_noisePow_2_1[101] = 22'b0010001111000110111100;
  assign sqrt_noisePow_2_1[102] = 22'b0010001101011110000110;
  assign sqrt_noisePow_2_1[103] = 22'b0010001011110110011101;
  assign sqrt_noisePow_2_1[104] = 22'b0010001010010000000000;
  assign sqrt_noisePow_2_1[105] = 22'b0010001000101010101110;
  assign sqrt_noisePow_2_1[106] = 22'b0010000111000110100110;
  assign sqrt_noisePow_2_1[107] = 22'b0010000101100011100111;
  assign sqrt_noisePow_2_1[108] = 22'b0010000100000001110001;
  assign sqrt_noisePow_2_1[109] = 22'b0010000010100001000011;
  assign sqrt_noisePow_2_1[110] = 22'b0010000001000001011100;
  assign sqrt_noisePow_2_1[111] = 22'b0001111111100010111010;
  assign sqrt_noisePow_2_1[112] = 22'b0001111110000101011110;
  assign sqrt_noisePow_2_1[113] = 22'b0001111100101001000110;
  assign sqrt_noisePow_2_1[114] = 22'b0001111011001101110010;
  assign sqrt_noisePow_2_1[115] = 22'b0001111001110011100001;
  assign sqrt_noisePow_2_1[116] = 22'b0001111000011010010010;
  assign sqrt_noisePow_2_1[117] = 22'b0001110111000010000100;
  assign sqrt_noisePow_2_1[118] = 22'b0001110101101010110111;
  assign sqrt_noisePow_2_1[119] = 22'b0001110100010100101010;
  assign sqrt_noisePow_2_1[120] = 22'b0001110010111111011100;
  assign sqrt_noisePow_2_1[121] = 22'b0001110001101011001101;
  assign sqrt_noisePow_2_1[122] = 22'b0001110000010111111011;
  assign sqrt_noisePow_2_1[123] = 22'b0001101111000101100110;
  assign sqrt_noisePow_2_1[124] = 22'b0001101101110100001110;
  assign sqrt_noisePow_2_1[125] = 22'b0001101100100011110001;
  assign sqrt_noisePow_2_1[126] = 22'b0001101011010100001111;
  assign sqrt_noisePow_2_1[127] = 22'b0001101010000101100111;
  assign sqrt_noisePow_2_1[128] = 22'b0001101000110111111001;
  assign sqrt_noisePow_2_1[129] = 22'b0001100111101011000100;
  assign sqrt_noisePow_2_1[130] = 22'b0001100110011111000111;
  assign sqrt_noisePow_2_1[131] = 22'b0001100101010100000010;
  assign sqrt_noisePow_2_1[132] = 22'b0001100100001001110100;
  assign sqrt_noisePow_2_1[133] = 22'b0001100011000000011100;
  assign sqrt_noisePow_2_1[134] = 22'b0001100001110111111010;
  assign sqrt_noisePow_2_1[135] = 22'b0001100000110000001101;
  assign sqrt_noisePow_2_1[136] = 22'b0001011111101001010100;
  assign sqrt_noisePow_2_1[137] = 22'b0001011110100011010000;
  assign sqrt_noisePow_2_1[138] = 22'b0001011101011101111111;
  assign sqrt_noisePow_2_1[139] = 22'b0001011100011001100000;
  assign sqrt_noisePow_2_1[140] = 22'b0001011011010101110100;
  assign sqrt_noisePow_2_1[141] = 22'b0001011010010010111001;
  assign sqrt_noisePow_2_1[142] = 22'b0001011001010000110000;
  assign sqrt_noisePow_2_1[143] = 22'b0001011000001111010111;
  assign sqrt_noisePow_2_1[144] = 22'b0001010111001110101101;
  assign sqrt_noisePow_2_1[145] = 22'b0001010110001110110011;
  assign sqrt_noisePow_2_1[146] = 22'b0001010101001111101000;
  assign sqrt_noisePow_2_1[147] = 22'b0001010100010001001100;
  assign sqrt_noisePow_2_1[148] = 22'b0001010011010011011100;
  assign sqrt_noisePow_2_1[149] = 22'b0001010010010110011011;
  assign sqrt_noisePow_2_1[150] = 22'b0001010001011010000110;
  assign sqrt_noisePow_2_1[151] = 22'b0001010000011110011101;
  assign sqrt_noisePow_2_1[152] = 22'b0001001111100011011111;
  assign sqrt_noisePow_2_1[153] = 22'b0001001110101001001101;
  assign sqrt_noisePow_2_1[154] = 22'b0001001101101111100110;
  assign sqrt_noisePow_2_1[155] = 22'b0001001100110110101001;
  assign sqrt_noisePow_2_1[156] = 22'b0001001011111110010101;
  assign sqrt_noisePow_2_1[157] = 22'b0001001011000110101011;
  assign sqrt_noisePow_2_1[158] = 22'b0001001010001111101010;
  assign sqrt_noisePow_2_1[159] = 22'b0001001001011001010001;
  assign sqrt_noisePow_2_1[160] = 22'b0001001000100011100000;
  assign sqrt_noisePow_2_1[161] = 22'b0001000111101110010110;
  assign sqrt_noisePow_2_1[162] = 22'b0001000110111001110011;
  assign sqrt_noisePow_2_1[163] = 22'b0001000110000101110111;
  assign sqrt_noisePow_2_1[164] = 22'b0001000101010010100000;
  assign sqrt_noisePow_2_1[165] = 22'b0001000100011111101111;
  assign sqrt_noisePow_2_1[166] = 22'b0001000011101101100100;
  assign sqrt_noisePow_2_1[167] = 22'b0001000010111011111101;
  assign sqrt_noisePow_2_1[168] = 22'b0001000010001010111011;
  assign sqrt_noisePow_2_1[169] = 22'b0001000001011010011100;
  assign sqrt_noisePow_2_1[170] = 22'b0001000000101010100001;
  assign sqrt_noisePow_2_1[171] = 22'b0000111111111011001001;
  assign sqrt_noisePow_2_1[172] = 22'b0000111111001100010100;
  assign sqrt_noisePow_2_1[173] = 22'b0000111110011110000001;
  assign sqrt_noisePow_2_1[174] = 22'b0000111101110000010000;
  assign sqrt_noisePow_2_1[175] = 22'b0000111101000011000001;
  assign sqrt_noisePow_2_1[176] = 22'b0000111100010110010011;
  assign sqrt_noisePow_2_1[177] = 22'b0000111011101010000101;
  assign sqrt_noisePow_2_1[178] = 22'b0000111010111110011000;
  assign sqrt_noisePow_2_1[179] = 22'b0000111010010011001011;
  assign sqrt_noisePow_2_1[180] = 22'b0000111001101000011101;
  assign sqrt_noisePow_2_1[181] = 22'b0000111000111110001111;
  assign sqrt_noisePow_2_1[182] = 22'b0000111000010100100000;
  assign sqrt_noisePow_2_1[183] = 22'b0000110111101011001111;
  assign sqrt_noisePow_2_1[184] = 22'b0000110111000010011101;
  assign sqrt_noisePow_2_1[185] = 22'b0000110110011010001000;
  assign sqrt_noisePow_2_1[186] = 22'b0000110101110010010001;
  assign sqrt_noisePow_2_1[187] = 22'b0000110101001010110111;
  assign sqrt_noisePow_2_1[188] = 22'b0000110100100011111011;
  assign sqrt_noisePow_2_1[189] = 22'b0000110011111101011010;
  assign sqrt_noisePow_2_1[190] = 22'b0000110011010111010110;
  assign sqrt_noisePow_2_1[191] = 22'b0000110010110001101110;
  assign sqrt_noisePow_2_1[192] = 22'b0000110010001100100001;
  assign sqrt_noisePow_2_1[193] = 22'b0000110001100111101111;
  assign sqrt_noisePow_2_1[194] = 22'b0000110001000011011001;
  assign sqrt_noisePow_2_1[195] = 22'b0000110000011111011101;
  assign sqrt_noisePow_2_1[196] = 22'b0000101111111011111011;
  assign sqrt_noisePow_2_1[197] = 22'b0000101111011000110100;
  assign sqrt_noisePow_2_1[198] = 22'b0000101110110110000110;
  assign sqrt_noisePow_2_1[199] = 22'b0000101110010011110001;
  assign sqrt_noisePow_2_1[200] = 22'b0000101101110001110110;
  assign sqrt_noisePow_2_1[201] = 22'b0000101101010000010100;
  assign sqrt_noisePow_2_1[202] = 22'b0000101100101111001010;
  assign sqrt_noisePow_2_1[203] = 22'b0000101100001110011000;
  assign sqrt_noisePow_2_1[204] = 22'b0000101011101101111111;
  assign sqrt_noisePow_2_1[205] = 22'b0000101011001101111101;
  assign sqrt_noisePow_2_1[206] = 22'b0000101010101110010011;
  assign sqrt_noisePow_2_1[207] = 22'b0000101010001111000000;
  assign sqrt_noisePow_2_1[208] = 22'b0000101001110000000011;
  assign sqrt_noisePow_2_1[209] = 22'b0000101001010001011110;
  assign sqrt_noisePow_2_1[210] = 22'b0000101000110011001111;
  assign sqrt_noisePow_2_1[211] = 22'b0000101000010101010110;
  assign sqrt_noisePow_2_1[212] = 22'b0000100111110111110011;
  assign sqrt_noisePow_2_1[213] = 22'b0000100111011010100101;
  assign sqrt_noisePow_2_1[214] = 22'b0000100110111101101101;
  assign sqrt_noisePow_2_1[215] = 22'b0000100110100001001010;
  assign sqrt_noisePow_2_1[216] = 22'b0000100110000100111100;
  assign sqrt_noisePow_2_1[217] = 22'b0000100101101001000011;
  assign sqrt_noisePow_2_1[218] = 22'b0000100101001101011110;
  assign sqrt_noisePow_2_1[219] = 22'b0000100100110010001101;
  assign sqrt_noisePow_2_1[220] = 22'b0000100100010111010001;
  assign sqrt_noisePow_2_1[221] = 22'b0000100011111100101000;
  assign sqrt_noisePow_2_1[222] = 22'b0000100011100010010010;
  assign sqrt_noisePow_2_1[223] = 22'b0000100011001000010000;
  assign sqrt_noisePow_2_1[224] = 22'b0000100010101110100001;
  assign sqrt_noisePow_2_1[225] = 22'b0000100010010101000101;
  assign sqrt_noisePow_2_1[226] = 22'b0000100001111011111011;
  assign sqrt_noisePow_2_1[227] = 22'b0000100001100011000100;
  assign sqrt_noisePow_2_1[228] = 22'b0000100001001010011111;
  assign sqrt_noisePow_2_1[229] = 22'b0000100000110010001100;
  assign sqrt_noisePow_2_1[230] = 22'b0000100000011010001011;
  assign sqrt_noisePow_2_1[231] = 22'b0000100000000010011100;
  assign sqrt_noisePow_2_1[232] = 22'b0000011111101010111101;
  assign sqrt_noisePow_2_1[233] = 22'b0000011111010011110000;
  assign sqrt_noisePow_2_1[234] = 22'b0000011110111100110100;
  assign sqrt_noisePow_2_1[235] = 22'b0000011110100110001001;
  assign sqrt_noisePow_2_1[236] = 22'b0000011110001111101111;
  assign sqrt_noisePow_2_1[237] = 22'b0000011101111001100101;
  assign sqrt_noisePow_2_1[238] = 22'b0000011101100011101011;
  assign sqrt_noisePow_2_1[239] = 22'b0000011101001110000001;
  assign sqrt_noisePow_2_1[240] = 22'b0000011100111000100111;
  assign sqrt_noisePow_2_1[241] = 22'b0000011100100011011101;
  assign sqrt_noisePow_2_1[242] = 22'b0000011100001110100010;
  assign sqrt_noisePow_2_1[243] = 22'b0000011011111001110110;
  assign sqrt_noisePow_2_1[244] = 22'b0000011011100101011010;
  assign sqrt_noisePow_2_1[245] = 22'b0000011011010001001101;
  assign sqrt_noisePow_2_1[246] = 22'b0000011010111101001110;
  assign sqrt_noisePow_2_1[247] = 22'b0000011010101001011110;
  assign sqrt_noisePow_2_1[248] = 22'b0000011010010101111101;
  assign sqrt_noisePow_2_1[249] = 22'b0000011010000010101010;
  assign sqrt_noisePow_2_1[250] = 22'b0000011001101111100101;
  assign sqrt_noisePow_2_1[251] = 22'b0000011001011100101110;
  assign sqrt_noisePow_2_1[252] = 22'b0000011001001010000101;
  assign sqrt_noisePow_2_1[253] = 22'b0000011000110111101001;
  assign sqrt_noisePow_2_1[254] = 22'b0000011000100101011011;
  assign sqrt_noisePow_2_1[255] = 22'b0000011000010011011010;
  assign sqrt_noisePow_2_1[256] = 22'b0000011000000001100111;
  assign sqrt_noisePow_2_1[257] = 22'b0000010111110000000000;
  assign sqrt_noisePow_2_1[258] = 22'b0000010111011110100111;
  assign sqrt_noisePow_2_1[259] = 22'b0000010111001101011010;
  assign sqrt_noisePow_2_1[260] = 22'b0000010110111100011010;
  assign sqrt_noisePow_2_1[261] = 22'b0000010110101011100110;
  assign sqrt_noisePow_2_1[262] = 22'b0000010110011010111111;
  assign sqrt_noisePow_2_1[263] = 22'b0000010110001010100011;
  assign sqrt_noisePow_2_1[264] = 22'b0000010101111010010100;
  assign sqrt_noisePow_2_1[265] = 22'b0000010101101010010001;
  assign sqrt_noisePow_2_1[266] = 22'b0000010101011010011001;
  assign sqrt_noisePow_2_1[267] = 22'b0000010101001010101101;
  assign sqrt_noisePow_2_1[268] = 22'b0000010100111011001101;
  assign sqrt_noisePow_2_1[269] = 22'b0000010100101011111000;
  assign sqrt_noisePow_2_1[270] = 22'b0000010100011100101110;
  assign sqrt_noisePow_2_1[271] = 22'b0000010100001101101111;
  assign sqrt_noisePow_2_1[272] = 22'b0000010011111110111011;
  assign sqrt_noisePow_2_1[273] = 22'b0000010011110000010010;
  assign sqrt_noisePow_2_1[274] = 22'b0000010011100001110100;
  assign sqrt_noisePow_2_1[275] = 22'b0000010011010011100000;
  assign sqrt_noisePow_2_1[276] = 22'b0000010011000101010111;
  assign sqrt_noisePow_2_1[277] = 22'b0000010010110111011000;
  assign sqrt_noisePow_2_1[278] = 22'b0000010010101001100100;
  assign sqrt_noisePow_2_1[279] = 22'b0000010010011011111010;
  assign sqrt_noisePow_2_1[280] = 22'b0000010010001110011001;
  assign sqrt_noisePow_2_1[281] = 22'b0000010010000001000011;
  assign sqrt_noisePow_2_1[282] = 22'b0000010001110011110110;
  assign sqrt_noisePow_2_1[283] = 22'b0000010001100110110011;
  assign sqrt_noisePow_2_1[284] = 22'b0000010001011001111001;
  assign sqrt_noisePow_2_1[285] = 22'b0000010001001101001001;
  assign sqrt_noisePow_2_1[286] = 22'b0000010001000000100011;
  assign sqrt_noisePow_2_1[287] = 22'b0000010000110100000101;
  assign sqrt_noisePow_2_1[288] = 22'b0000010000100111110001;
  assign sqrt_noisePow_2_1[289] = 22'b0000010000011011100110;
  assign sqrt_noisePow_2_1[290] = 22'b0000010000001111100011;
  assign sqrt_noisePow_2_1[291] = 22'b0000010000000011101010;
  assign sqrt_noisePow_2_1[292] = 22'b0000001111110111111001;
  assign sqrt_noisePow_2_1[293] = 22'b0000001111101100010000;
  assign sqrt_noisePow_2_1[294] = 22'b0000001111100000110001;
  assign sqrt_noisePow_2_1[295] = 22'b0000001111010101011001;
  assign sqrt_noisePow_2_1[296] = 22'b0000001111001010001010;
  assign sqrt_noisePow_2_1[297] = 22'b0000001110111111000100;
  assign sqrt_noisePow_2_1[298] = 22'b0000001110110100000101;
  assign sqrt_noisePow_2_1[299] = 22'b0000001110101001001111;
  assign sqrt_noisePow_2_1[300] = 22'b0000001110011110100000;
  assign sqrt_noisePow_2_1[301] = 22'b0000001110010011111001;
  assign sqrt_noisePow_2_1[302] = 22'b0000001110001001011010;
  assign sqrt_noisePow_2_1[303] = 22'b0000001101111111000011;
  assign sqrt_noisePow_2_1[304] = 22'b0000001101110100110011;
  assign sqrt_noisePow_2_1[305] = 22'b0000001101101010101011;
  assign sqrt_noisePow_2_1[306] = 22'b0000001101100000101010;
  assign sqrt_noisePow_2_1[307] = 22'b0000001101010110110001;
  assign sqrt_noisePow_2_1[308] = 22'b0000001101001100111111;
  assign sqrt_noisePow_2_1[309] = 22'b0000001101000011010100;
  assign sqrt_noisePow_2_1[310] = 22'b0000001100111001110000;
  assign sqrt_noisePow_2_1[311] = 22'b0000001100110000010011;
  assign sqrt_noisePow_2_1[312] = 22'b0000001100100110111101;
  assign sqrt_noisePow_2_1[313] = 22'b0000001100011101101101;
  assign sqrt_noisePow_2_1[314] = 22'b0000001100010100100101;
  assign sqrt_noisePow_2_1[315] = 22'b0000001100001011100011;
  assign sqrt_noisePow_2_1[316] = 22'b0000001100000010101000;
  assign sqrt_noisePow_2_1[317] = 22'b0000001011111001110100;
  assign sqrt_noisePow_2_1[318] = 22'b0000001011110001000110;
  assign sqrt_noisePow_2_1[319] = 22'b0000001011101000011110;
  assign sqrt_noisePow_2_1[320] = 22'b0000001011011111111100;
  assign sqrt_noisePow_2_1[321] = 22'b0000001011010111100001;
  assign sqrt_noisePow_2_1[322] = 22'b0000001011001111001100;
  assign sqrt_noisePow_2_1[323] = 22'b0000001011000110111101;
  assign sqrt_noisePow_2_1[324] = 22'b0000001010111110110101;
  assign sqrt_noisePow_2_1[325] = 22'b0000001010110110110010;
  assign sqrt_noisePow_2_1[326] = 22'b0000001010101110110101;
  assign sqrt_noisePow_2_1[327] = 22'b0000001010100110111110;
  assign sqrt_noisePow_2_1[328] = 22'b0000001010011111001100;
  assign sqrt_noisePow_2_1[329] = 22'b0000001010010111100000;
  assign sqrt_noisePow_2_1[330] = 22'b0000001010001111111010;
  assign sqrt_noisePow_2_1[331] = 22'b0000001010001000011010;
  assign sqrt_noisePow_2_1[332] = 22'b0000001010000000111111;
  assign sqrt_noisePow_2_1[333] = 22'b0000001001111001101001;
  assign sqrt_noisePow_2_1[334] = 22'b0000001001110010011001;
  assign sqrt_noisePow_2_1[335] = 22'b0000001001101011001110;
  assign sqrt_noisePow_2_1[336] = 22'b0000001001100100001000;
  assign sqrt_noisePow_2_1[337] = 22'b0000001001011101001000;
  assign sqrt_noisePow_2_1[338] = 22'b0000001001010110001101;
  assign sqrt_noisePow_2_1[339] = 22'b0000001001001111010110;
  assign sqrt_noisePow_2_1[340] = 22'b0000001001001000100101;
  assign sqrt_noisePow_2_1[341] = 22'b0000001001000001111001;
  assign sqrt_noisePow_2_1[342] = 22'b0000001000111011010010;
  assign sqrt_noisePow_2_1[343] = 22'b0000001000110100101111;
  assign sqrt_noisePow_2_1[344] = 22'b0000001000101110010001;
  assign sqrt_noisePow_2_1[345] = 22'b0000001000100111111000;
  assign sqrt_noisePow_2_1[346] = 22'b0000001000100001100100;
  assign sqrt_noisePow_2_1[347] = 22'b0000001000011011010100;
  assign sqrt_noisePow_2_1[348] = 22'b0000001000010101001001;
  assign sqrt_noisePow_2_1[349] = 22'b0000001000001111000011;
  assign sqrt_noisePow_2_1[350] = 22'b0000001000001001000001;
  assign sqrt_noisePow_2_1[351] = 22'b0000001000000011000011;
  assign sqrt_noisePow_2_1[352] = 22'b0000000111111101001010;
  assign sqrt_noisePow_2_1[353] = 22'b0000000111110111010101;
  assign sqrt_noisePow_2_1[354] = 22'b0000000111110001100100;
  assign sqrt_noisePow_2_1[355] = 22'b0000000111101011110111;
  assign sqrt_noisePow_2_1[356] = 22'b0000000111100110001111;
  assign sqrt_noisePow_2_1[357] = 22'b0000000111100000101011;
  assign sqrt_noisePow_2_1[358] = 22'b0000000111011011001011;
  assign sqrt_noisePow_2_1[359] = 22'b0000000111010101101110;
  assign sqrt_noisePow_2_1[360] = 22'b0000000111010000010110;
  assign sqrt_noisePow_2_1[361] = 22'b0000000111001011000010;
  assign sqrt_noisePow_2_1[362] = 22'b0000000111000101110010;
  assign sqrt_noisePow_2_1[363] = 22'b0000000111000000100101;
  assign sqrt_noisePow_2_1[364] = 22'b0000000110111011011101;
  assign sqrt_noisePow_2_1[365] = 22'b0000000110110110011000;
  assign sqrt_noisePow_2_1[366] = 22'b0000000110110001010111;
  assign sqrt_noisePow_2_1[367] = 22'b0000000110101100011001;
  assign sqrt_noisePow_2_1[368] = 22'b0000000110100111011111;
  assign sqrt_noisePow_2_1[369] = 22'b0000000110100010101001;
  assign sqrt_noisePow_2_1[370] = 22'b0000000110011101110111;
  assign sqrt_noisePow_2_1[371] = 22'b0000000110011001000111;
  assign sqrt_noisePow_2_1[372] = 22'b0000000110010100011100;
  assign sqrt_noisePow_2_1[373] = 22'b0000000110001111110011;
  assign sqrt_noisePow_2_1[374] = 22'b0000000110001011001110;
  assign sqrt_noisePow_2_1[375] = 22'b0000000110000110101101;
  assign sqrt_noisePow_2_1[376] = 22'b0000000110000010001111;
  assign sqrt_noisePow_2_1[377] = 22'b0000000101111101110100;
  assign sqrt_noisePow_2_1[378] = 22'b0000000101111001011100;
  assign sqrt_noisePow_2_1[379] = 22'b0000000101110101000111;
  assign sqrt_noisePow_2_1[380] = 22'b0000000101110000110110;
  assign sqrt_noisePow_2_1[381] = 22'b0000000101101100101000;
  assign sqrt_noisePow_2_1[382] = 22'b0000000101101000011101;
  assign sqrt_noisePow_2_1[383] = 22'b0000000101100100010101;
  assign sqrt_noisePow_2_1[384] = 22'b0000000101100000010000;
  assign sqrt_noisePow_2_1[385] = 22'b0000000101011100001110;
  assign sqrt_noisePow_2_1[386] = 22'b0000000101011000001111;
  assign sqrt_noisePow_2_1[387] = 22'b0000000101010100010010;
  assign sqrt_noisePow_2_1[388] = 22'b0000000101010000011001;
  assign sqrt_noisePow_2_1[389] = 22'b0000000101001100100011;
  assign sqrt_noisePow_2_1[390] = 22'b0000000101001000101111;
  assign sqrt_noisePow_2_1[391] = 22'b0000000101000100111110;
  assign sqrt_noisePow_2_1[392] = 22'b0000000101000001010000;
  assign sqrt_noisePow_2_1[393] = 22'b0000000100111101100101;
  assign sqrt_noisePow_2_1[394] = 22'b0000000100111001111100;
  assign sqrt_noisePow_2_1[395] = 22'b0000000100110110010110;
  assign sqrt_noisePow_2_1[396] = 22'b0000000100110010110011;
  assign sqrt_noisePow_2_1[397] = 22'b0000000100101111010010;
  assign sqrt_noisePow_2_1[398] = 22'b0000000100101011110100;
  assign sqrt_noisePow_2_1[399] = 22'b0000000100101000011000;
  assign sqrt_noisePow_2_1[400] = 22'b0000000100100100111111;
  assign sqrt_noisePow_2_1[401] = 22'b0000000100100001101000;
  assign sqrt_noisePow_2_1[402] = 22'b0000000100011110010100;
  assign sqrt_noisePow_2_1[403] = 22'b0000000100011011000010;
  assign sqrt_noisePow_2_1[404] = 22'b0000000100010111110011;
  assign sqrt_noisePow_2_1[405] = 22'b0000000100010100100110;
  assign sqrt_noisePow_2_1[406] = 22'b0000000100010001011011;
  assign sqrt_noisePow_2_1[407] = 22'b0000000100001110010011;
  assign sqrt_noisePow_2_1[408] = 22'b0000000100001011001101;
  assign sqrt_noisePow_2_1[409] = 22'b0000000100001000001001;
  assign sqrt_noisePow_2_1[410] = 22'b0000000100000101001000;
  assign sqrt_noisePow_2_1[411] = 22'b0000000100000010001001;
  assign sqrt_noisePow_2_1[412] = 22'b0000000011111111001011;
  assign sqrt_noisePow_2_1[413] = 22'b0000000011111100010001;
  assign sqrt_noisePow_2_1[414] = 22'b0000000011111001011000;
  assign sqrt_noisePow_2_1[415] = 22'b0000000011110110100001;
  assign sqrt_noisePow_2_1[416] = 22'b0000000011110011101100;
  assign sqrt_noisePow_2_1[417] = 22'b0000000011110000111010;
  assign sqrt_noisePow_2_1[418] = 22'b0000000011101110001001;
  assign sqrt_noisePow_2_1[419] = 22'b0000000011101011011011;
  assign sqrt_noisePow_2_1[420] = 22'b0000000011101000101110;
  assign sqrt_noisePow_2_1[421] = 22'b0000000011100110000100;
  assign sqrt_noisePow_2_1[422] = 22'b0000000011100011011011;
  assign sqrt_noisePow_2_1[423] = 22'b0000000011100000110101;
  assign sqrt_noisePow_2_1[424] = 22'b0000000011011110010000;
  assign sqrt_noisePow_2_1[425] = 22'b0000000011011011101101;
  assign sqrt_noisePow_2_1[426] = 22'b0000000011011001001100;
  assign sqrt_noisePow_2_1[427] = 22'b0000000011010110101101;
  assign sqrt_noisePow_2_1[428] = 22'b0000000011010100010000;
  assign sqrt_noisePow_2_1[429] = 22'b0000000011010001110100;
  assign sqrt_noisePow_2_1[430] = 22'b0000000011001111011011;
  assign sqrt_noisePow_2_1[431] = 22'b0000000011001101000011;
  assign sqrt_noisePow_2_1[432] = 22'b0000000011001010101101;
  assign sqrt_noisePow_2_1[433] = 22'b0000000011001000011000;
  assign sqrt_noisePow_2_1[434] = 22'b0000000011000110000101;
  assign sqrt_noisePow_2_1[435] = 22'b0000000011000011110100;
  assign sqrt_noisePow_2_1[436] = 22'b0000000011000001100101;
  assign sqrt_noisePow_2_1[437] = 22'b0000000010111111010111;
  assign sqrt_noisePow_2_1[438] = 22'b0000000010111101001011;
  assign sqrt_noisePow_2_1[439] = 22'b0000000010111011000000;
  assign sqrt_noisePow_2_1[440] = 22'b0000000010111000110111;
  assign sqrt_noisePow_2_1[441] = 22'b0000000010110110110000;
  assign sqrt_noisePow_2_1[442] = 22'b0000000010110100101010;
  assign sqrt_noisePow_2_1[443] = 22'b0000000010110010100101;
  assign sqrt_noisePow_2_1[444] = 22'b0000000010110000100011;
  assign sqrt_noisePow_2_1[445] = 22'b0000000010101110100001;
  assign sqrt_noisePow_2_1[446] = 22'b0000000010101100100001;
  assign sqrt_noisePow_2_1[447] = 22'b0000000010101010100011;
  assign sqrt_noisePow_2_1[448] = 22'b0000000010101000100110;
  assign sqrt_noisePow_2_1[449] = 22'b0000000010100110101011;
  assign sqrt_noisePow_2_1[450] = 22'b0000000010100100110000;
  assign sqrt_noisePow_2_1[451] = 22'b0000000010100010111000;
  assign sqrt_noisePow_2_1[452] = 22'b0000000010100001000000;
  assign sqrt_noisePow_2_1[453] = 22'b0000000010011111001010;
  assign sqrt_noisePow_2_1[454] = 22'b0000000010011101010110;
  assign sqrt_noisePow_2_1[455] = 22'b0000000010011011100011;
  assign sqrt_noisePow_2_1[456] = 22'b0000000010011001110001;
  assign sqrt_noisePow_2_1[457] = 22'b0000000010011000000000;
  assign sqrt_noisePow_2_1[458] = 22'b0000000010010110010001;
  assign sqrt_noisePow_2_1[459] = 22'b0000000010010100100011;
  assign sqrt_noisePow_2_1[460] = 22'b0000000010010010110110;
  assign sqrt_noisePow_2_1[461] = 22'b0000000010010001001010;
  assign sqrt_noisePow_2_1[462] = 22'b0000000010001111100000;
  assign sqrt_noisePow_2_1[463] = 22'b0000000010001101110111;
  assign sqrt_noisePow_2_1[464] = 22'b0000000010001100001111;
  assign sqrt_noisePow_2_1[465] = 22'b0000000010001010101000;
  assign sqrt_noisePow_2_1[466] = 22'b0000000010001001000011;
  assign sqrt_noisePow_2_1[467] = 22'b0000000010000111011110;
  assign sqrt_noisePow_2_1[468] = 22'b0000000010000101111011;
  assign sqrt_noisePow_2_1[469] = 22'b0000000010000100011001;
  assign sqrt_noisePow_2_1[470] = 22'b0000000010000010111000;
  assign sqrt_noisePow_2_1[471] = 22'b0000000010000001011000;
  assign sqrt_noisePow_2_1[472] = 22'b0000000001111111111001;
  assign sqrt_noisePow_2_1[473] = 22'b0000000001111110011011;
  assign sqrt_noisePow_2_1[474] = 22'b0000000001111100111111;
  assign sqrt_noisePow_2_1[475] = 22'b0000000001111011100011;
  assign sqrt_noisePow_2_1[476] = 22'b0000000001111010001001;
  assign sqrt_noisePow_2_1[477] = 22'b0000000001111000101111;
  assign sqrt_noisePow_2_1[478] = 22'b0000000001110111010111;
  assign sqrt_noisePow_2_1[479] = 22'b0000000001110101111111;
  assign sqrt_noisePow_2_1[480] = 22'b0000000001110100101001;
  assign sqrt_noisePow_2_1[481] = 22'b0000000001110011010011;
  assign sqrt_noisePow_2_1[482] = 22'b0000000001110001111111;
  assign sqrt_noisePow_2_1[483] = 22'b0000000001110000101011;
  assign sqrt_noisePow_2_1[484] = 22'b0000000001101111011001;
  assign sqrt_noisePow_2_1[485] = 22'b0000000001101110000111;
  assign sqrt_noisePow_2_1[486] = 22'b0000000001101100110111;
  assign sqrt_noisePow_2_1[487] = 22'b0000000001101011100111;
  assign sqrt_noisePow_2_1[488] = 22'b0000000001101010011000;
  assign sqrt_noisePow_2_1[489] = 22'b0000000001101001001010;
  assign sqrt_noisePow_2_1[490] = 22'b0000000001100111111101;
  assign sqrt_noisePow_2_1[491] = 22'b0000000001100110110001;
  assign sqrt_noisePow_2_1[492] = 22'b0000000001100101100110;
  assign sqrt_noisePow_2_1[493] = 22'b0000000001100100011011;
  assign sqrt_noisePow_2_1[494] = 22'b0000000001100011010010;
  assign sqrt_noisePow_2_1[495] = 22'b0000000001100010001001;
  assign sqrt_noisePow_2_1[496] = 22'b0000000001100001000001;
  assign sqrt_noisePow_2_1[497] = 22'b0000000001011111111010;
  assign sqrt_noisePow_2_1[498] = 22'b0000000001011110110100;
  assign sqrt_noisePow_2_1[499] = 22'b0000000001011101101110;
  assign sqrt_noisePow_2_1[500] = 22'b0000000001011100101010;
  assign sqrt_noisePow_2_1[501] = 22'b0000000001011011100110;
  assign sqrt_noisePow_2_1[502] = 22'b0000000001011010100011;
  assign sqrt_noisePow_2_1[503] = 22'b0000000001011001100000;
  assign sqrt_noisePow_2_1[504] = 22'b0000000001011000011111;
  assign sqrt_noisePow_2_1[505] = 22'b0000000001010111011110;
  assign sqrt_noisePow_2_1[506] = 22'b0000000001010110011110;
  assign sqrt_noisePow_2_1[507] = 22'b0000000001010101011110;
  assign sqrt_noisePow_2_1[508] = 22'b0000000001010100100000;
  assign sqrt_noisePow_2_1[509] = 22'b0000000001010011100010;
  assign sqrt_noisePow_2_1[510] = 22'b0000000001010010100101;
  assign sqrt_noisePow_2_1[511] = 22'b0000000001010001101000;
  assign sqrt_noisePow_2_k = (Delay1_out1 <= 16'sb0000000000000000 ? 9'b000000000 :
              (Delay1_out1 >= 16'sb0000000111111111 ? 9'b111111111 :
              Delay1_out1[8:0]));
  assign sqrt_noisePow_2_out1 = sqrt_noisePow_2_1[sqrt_noisePow_2_k];



  assign noiseVar = sqrt_noisePow_2_out1;

endmodule  // alphadBtoLinearConverter

