// -------------------------------------------------------------
// 
// File Name: C:\Users\huber\Downloads\hdlsrc\HDLAWGNGenerator\HDLAWGNGenerator\RangeReconstruction_block.v
// Created: 2021-06-06 18:19:43
// 
// Generated by MATLAB 9.10 and HDL Coder 3.18
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: RangeReconstruction_block
// Source Path: HDLAWGNGenerator/AWGNGenerator/GaussianNoiseWithUnitVar/logImplementation/log/RangeReconstruction
// Hierarchy Level: 4
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module RangeReconstruction_block
          (y_e,
           exp_e,
           e);


  input   signed [30:0] y_e;  // sfix31_En27
  input   [7:0] exp_e;  // uint8
  output  [30:0] e;  // ufix31_En24


  wire signed [32:0] Constant_out1;  // sfix33_En32
  wire signed [8:0] Product_cast;  // sfix9
  wire signed [41:0] Product_mul_temp;  // sfix42_En32
  wire signed [40:0] Product_out1;  // sfix41_En32
  wire signed [34:0] Product_out1_1;  // sfix35_En28
  wire signed [35:0] Add1_sub_cast;  // sfix36_En28
  wire signed [35:0] Add1_sub_cast_1;  // sfix36_En28
  wire signed [35:0] Add1_sub_temp;  // sfix36_En28
  wire [30:0] Add1_out1;  // ufix31_En24
  wire [30:0] Bit_Shift_out1;  // ufix31_En24


  assign Constant_out1 = 33'sh0B17217F8;



  assign Product_cast = {1'b0, exp_e};
  assign Product_mul_temp = Product_cast * Constant_out1;
  assign Product_out1 = Product_mul_temp[40:0];



  assign Product_out1_1 = Product_out1[38:4];



  assign Add1_sub_cast = {Product_out1_1[34], Product_out1_1};
  assign Add1_sub_cast_1 = {{4{y_e[30]}}, {y_e, 1'b0}};
  assign Add1_sub_temp = Add1_sub_cast - Add1_sub_cast_1;
  assign Add1_out1 = Add1_sub_temp[34:4];



  assign Bit_Shift_out1 = Add1_out1 <<< 8'd1;



  assign e = Bit_Shift_out1;

endmodule  // RangeReconstruction_block

