// -------------------------------------------------------------
// 
// File Name: C:\Users\huber\Downloads\hdlsrc\HDLAWGNGenerator\HDLAWGNGenerator\Sine_HDL_Optimized1.v
// Created: 2021-06-06 18:19:42
// 
// Generated by MATLAB 9.10 and HDL Coder 3.18
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Sine_HDL_Optimized1
// Source Path: HDLAWGNGenerator/AWGNGenerator/GaussianNoiseWithUnitVar/SinCos/Sine HDL Optimized1
// Hierarchy Level: 3
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Sine_HDL_Optimized1
          (u,
           x);


  input   [15:0] u;  // ufix16_En16
  output  signed [15:0] x;  // sfix16_En15


  wire [11:0] insig_out1;  // ufix12_En12
  wire [15:0] Point25_out1;  // ufix16_En16
  wire [15:0] LTEp25_1_cast;  // ufix16_En16
  wire LTEp25_relop1;
  wire [15:0] Point75_out1;  // ufix16_En16
  wire [15:0] GTEp75_1_cast;  // ufix16_En16
  wire GTEp75_relop1;
  wire alpha1st_or_4th_Quad_bool;
  wire [7:0] alpha1st_or_4th_Quad_out1;  // uint8
  wire pow2switch_out1;
  wire [15:0] Point50_out1;  // ufix16_En16
  wire signed [16:0] p75mA_sub_cast;  // sfix17_En16
  wire signed [16:0] p75mA_sub_cast_1;  // sfix17_En16
  wire signed [16:0] p75mA_out1;  // sfix17_En16
  wire signed [16:0] Amp75_sub_cast;  // sfix17_En16
  wire signed [16:0] Amp75_sub_cast_1;  // sfix17_En16
  wire signed [16:0] Amp75_out1;  // sfix17_En16
  wire signed [16:0] Amp25_sub_cast;  // sfix17_En16
  wire signed [16:0] Amp25_sub_cast_1;  // sfix17_En16
  wire signed [16:0] Amp25_out1;  // sfix17_En16
  wire signed [16:0] p25mA_sub_cast;  // sfix17_En16
  wire signed [16:0] p25mA_sub_cast_1;  // sfix17_En16
  wire signed [16:0] p25mA_out1;  // sfix17_En16
  wire [15:0] LTEp50_1_cast;  // ufix16_En16
  wire LTEp50_relop1;
  wire signed [16:0] QuadHandle1b_out1;  // sfix17_En16
  wire [11:0] QuadHandle1b_out1_dtc;  // ufix12_En12
  wire signed [16:0] QuadHandle1a_out1;  // sfix17_En16
  wire [11:0] QuadHandle1a_out1_dtc;  // ufix12_En12
  wire [11:0] QuadHandle2_out1;  // ufix12_En12
  wire [11:0] CastU16En1_out1;  // ufix12
  wire [12:0] CastU16En3_out1;  // ufix13
  wire [11:0] CastU16En2_out1;  // ufix12
  wire [11:0] Saturation_out1;  // ufix12
  wire [11:0] Switch_out1;  // ufix12
  wire [9:0] Look_Up_Table_k;  // ufix10
  wire signed [15:0] Look_Up_Table_1 [0:1023];  // sfix16_En15 [1024]
  wire signed [15:0] Look_Up_Table_out1;  // sfix16_En15
  wire signed [16:0] Negate_cast;  // sfix17_En15
  wire signed [16:0] Negate_cast_1;  // sfix17_En15
  wire signed [15:0] Negate_out1;  // sfix16_En15
  wire signed [15:0] Cosine;  // sfix16_En15
  wire signed [15:0] Cosine_1;  // sfix16_En15

  // (C) 2016 Mathworks, Inc


  assign insig_out1 = u[15:4];



  assign Point25_out1 = 16'b0100000000000000;



  assign LTEp25_1_cast = {insig_out1, 4'b0000};
  assign LTEp25_relop1 = LTEp25_1_cast <= Point25_out1;



  assign Point75_out1 = 16'b1100000000000000;



  assign GTEp75_1_cast = {insig_out1, 4'b0000};
  assign GTEp75_relop1 = GTEp75_1_cast >= Point75_out1;



  assign alpha1st_or_4th_Quad_bool = LTEp25_relop1 | GTEp75_relop1;



  assign alpha1st_or_4th_Quad_out1 = {7'b0, alpha1st_or_4th_Quad_bool};



  assign pow2switch_out1 = 1'b1;



  assign Point50_out1 = 16'b1000000000000000;



  assign p75mA_sub_cast = {1'b0, Point75_out1};
  assign p75mA_sub_cast_1 = {1'b0, {insig_out1, 4'b0000}};
  assign p75mA_out1 = p75mA_sub_cast - p75mA_sub_cast_1;



  assign Amp75_sub_cast = {1'b0, {insig_out1, 4'b0000}};
  assign Amp75_sub_cast_1 = {1'b0, Point75_out1};
  assign Amp75_out1 = Amp75_sub_cast - Amp75_sub_cast_1;



  assign Amp25_sub_cast = {1'b0, {insig_out1, 4'b0000}};
  assign Amp25_sub_cast_1 = {1'b0, Point25_out1};
  assign Amp25_out1 = Amp25_sub_cast - Amp25_sub_cast_1;



  assign p25mA_sub_cast = {1'b0, Point25_out1};
  assign p25mA_sub_cast_1 = {1'b0, {insig_out1, 4'b0000}};
  assign p25mA_out1 = p25mA_sub_cast - p25mA_sub_cast_1;



  assign LTEp50_1_cast = {insig_out1, 4'b0000};
  assign LTEp50_relop1 = LTEp50_1_cast <= Point50_out1;



  assign QuadHandle1b_out1 = (GTEp75_relop1 == 1'b0 ? p75mA_out1 :
              Amp75_out1);



  assign QuadHandle1b_out1_dtc = ((QuadHandle1b_out1[16] == 1'b0) && (QuadHandle1b_out1[15:4] == 12'b111111111111) ? 12'b111111111111 :
              (QuadHandle1b_out1[16] == 1'b1 ? 12'b000000000000 :
              QuadHandle1b_out1[15:4]));



  assign QuadHandle1a_out1 = (LTEp25_relop1 == 1'b0 ? Amp25_out1 :
              p25mA_out1);



  assign QuadHandle1a_out1_dtc = ((QuadHandle1a_out1[16] == 1'b0) && (QuadHandle1a_out1[15:4] == 12'b111111111111) ? 12'b111111111111 :
              (QuadHandle1a_out1[16] == 1'b1 ? 12'b000000000000 :
              QuadHandle1a_out1[15:4]));



  assign QuadHandle2_out1 = (LTEp50_relop1 == 1'b0 ? QuadHandle1b_out1_dtc :
              QuadHandle1a_out1_dtc);



  assign CastU16En1_out1 = QuadHandle2_out1;



  assign CastU16En3_out1 = {1'b0, CastU16En1_out1};



  assign CastU16En2_out1 = (CastU16En3_out1[12] != 1'b0 ? 12'b111111111111 :
              CastU16En3_out1[11:0]);



  // saturation block maybe optimized away
  // if the NumDataPoints is a power of 2
  assign Saturation_out1 = (CastU16En2_out1 > 12'b001111111111 ? 12'b001111111111 :
              CastU16En2_out1);



  assign Switch_out1 = (pow2switch_out1 == 1'b0 ? CastU16En2_out1 :
              Saturation_out1);



  assign Look_Up_Table_1[0] = 16'sb0000000000000000;
  assign Look_Up_Table_1[1] = 16'sb0000000000110010;
  assign Look_Up_Table_1[2] = 16'sb0000000001100101;
  assign Look_Up_Table_1[3] = 16'sb0000000010010111;
  assign Look_Up_Table_1[4] = 16'sb0000000011001001;
  assign Look_Up_Table_1[5] = 16'sb0000000011111011;
  assign Look_Up_Table_1[6] = 16'sb0000000100101110;
  assign Look_Up_Table_1[7] = 16'sb0000000101100000;
  assign Look_Up_Table_1[8] = 16'sb0000000110010010;
  assign Look_Up_Table_1[9] = 16'sb0000000111000100;
  assign Look_Up_Table_1[10] = 16'sb0000000111110111;
  assign Look_Up_Table_1[11] = 16'sb0000001000101001;
  assign Look_Up_Table_1[12] = 16'sb0000001001011011;
  assign Look_Up_Table_1[13] = 16'sb0000001010001101;
  assign Look_Up_Table_1[14] = 16'sb0000001011000000;
  assign Look_Up_Table_1[15] = 16'sb0000001011110010;
  assign Look_Up_Table_1[16] = 16'sb0000001100100100;
  assign Look_Up_Table_1[17] = 16'sb0000001101010110;
  assign Look_Up_Table_1[18] = 16'sb0000001110001001;
  assign Look_Up_Table_1[19] = 16'sb0000001110111011;
  assign Look_Up_Table_1[20] = 16'sb0000001111101101;
  assign Look_Up_Table_1[21] = 16'sb0000010000011111;
  assign Look_Up_Table_1[22] = 16'sb0000010001010010;
  assign Look_Up_Table_1[23] = 16'sb0000010010000100;
  assign Look_Up_Table_1[24] = 16'sb0000010010110110;
  assign Look_Up_Table_1[25] = 16'sb0000010011101000;
  assign Look_Up_Table_1[26] = 16'sb0000010100011011;
  assign Look_Up_Table_1[27] = 16'sb0000010101001101;
  assign Look_Up_Table_1[28] = 16'sb0000010101111111;
  assign Look_Up_Table_1[29] = 16'sb0000010110110001;
  assign Look_Up_Table_1[30] = 16'sb0000010111100011;
  assign Look_Up_Table_1[31] = 16'sb0000011000010110;
  assign Look_Up_Table_1[32] = 16'sb0000011001001000;
  assign Look_Up_Table_1[33] = 16'sb0000011001111010;
  assign Look_Up_Table_1[34] = 16'sb0000011010101100;
  assign Look_Up_Table_1[35] = 16'sb0000011011011110;
  assign Look_Up_Table_1[36] = 16'sb0000011100010001;
  assign Look_Up_Table_1[37] = 16'sb0000011101000011;
  assign Look_Up_Table_1[38] = 16'sb0000011101110101;
  assign Look_Up_Table_1[39] = 16'sb0000011110100111;
  assign Look_Up_Table_1[40] = 16'sb0000011111011001;
  assign Look_Up_Table_1[41] = 16'sb0000100000001100;
  assign Look_Up_Table_1[42] = 16'sb0000100000111110;
  assign Look_Up_Table_1[43] = 16'sb0000100001110000;
  assign Look_Up_Table_1[44] = 16'sb0000100010100010;
  assign Look_Up_Table_1[45] = 16'sb0000100011010100;
  assign Look_Up_Table_1[46] = 16'sb0000100100000110;
  assign Look_Up_Table_1[47] = 16'sb0000100100111000;
  assign Look_Up_Table_1[48] = 16'sb0000100101101011;
  assign Look_Up_Table_1[49] = 16'sb0000100110011101;
  assign Look_Up_Table_1[50] = 16'sb0000100111001111;
  assign Look_Up_Table_1[51] = 16'sb0000101000000001;
  assign Look_Up_Table_1[52] = 16'sb0000101000110011;
  assign Look_Up_Table_1[53] = 16'sb0000101001100101;
  assign Look_Up_Table_1[54] = 16'sb0000101010010111;
  assign Look_Up_Table_1[55] = 16'sb0000101011001001;
  assign Look_Up_Table_1[56] = 16'sb0000101011111011;
  assign Look_Up_Table_1[57] = 16'sb0000101100101101;
  assign Look_Up_Table_1[58] = 16'sb0000101101100000;
  assign Look_Up_Table_1[59] = 16'sb0000101110010010;
  assign Look_Up_Table_1[60] = 16'sb0000101111000100;
  assign Look_Up_Table_1[61] = 16'sb0000101111110110;
  assign Look_Up_Table_1[62] = 16'sb0000110000101000;
  assign Look_Up_Table_1[63] = 16'sb0000110001011010;
  assign Look_Up_Table_1[64] = 16'sb0000110010001100;
  assign Look_Up_Table_1[65] = 16'sb0000110010111110;
  assign Look_Up_Table_1[66] = 16'sb0000110011110000;
  assign Look_Up_Table_1[67] = 16'sb0000110100100010;
  assign Look_Up_Table_1[68] = 16'sb0000110101010100;
  assign Look_Up_Table_1[69] = 16'sb0000110110000110;
  assign Look_Up_Table_1[70] = 16'sb0000110110111000;
  assign Look_Up_Table_1[71] = 16'sb0000110111101010;
  assign Look_Up_Table_1[72] = 16'sb0000111000011100;
  assign Look_Up_Table_1[73] = 16'sb0000111001001110;
  assign Look_Up_Table_1[74] = 16'sb0000111010000000;
  assign Look_Up_Table_1[75] = 16'sb0000111010110010;
  assign Look_Up_Table_1[76] = 16'sb0000111011100100;
  assign Look_Up_Table_1[77] = 16'sb0000111100010101;
  assign Look_Up_Table_1[78] = 16'sb0000111101000111;
  assign Look_Up_Table_1[79] = 16'sb0000111101111001;
  assign Look_Up_Table_1[80] = 16'sb0000111110101011;
  assign Look_Up_Table_1[81] = 16'sb0000111111011101;
  assign Look_Up_Table_1[82] = 16'sb0001000000001111;
  assign Look_Up_Table_1[83] = 16'sb0001000001000001;
  assign Look_Up_Table_1[84] = 16'sb0001000001110011;
  assign Look_Up_Table_1[85] = 16'sb0001000010100100;
  assign Look_Up_Table_1[86] = 16'sb0001000011010110;
  assign Look_Up_Table_1[87] = 16'sb0001000100001000;
  assign Look_Up_Table_1[88] = 16'sb0001000100111010;
  assign Look_Up_Table_1[89] = 16'sb0001000101101100;
  assign Look_Up_Table_1[90] = 16'sb0001000110011110;
  assign Look_Up_Table_1[91] = 16'sb0001000111001111;
  assign Look_Up_Table_1[92] = 16'sb0001001000000001;
  assign Look_Up_Table_1[93] = 16'sb0001001000110011;
  assign Look_Up_Table_1[94] = 16'sb0001001001100101;
  assign Look_Up_Table_1[95] = 16'sb0001001010010110;
  assign Look_Up_Table_1[96] = 16'sb0001001011001000;
  assign Look_Up_Table_1[97] = 16'sb0001001011111010;
  assign Look_Up_Table_1[98] = 16'sb0001001100101011;
  assign Look_Up_Table_1[99] = 16'sb0001001101011101;
  assign Look_Up_Table_1[100] = 16'sb0001001110001111;
  assign Look_Up_Table_1[101] = 16'sb0001001111000001;
  assign Look_Up_Table_1[102] = 16'sb0001001111110010;
  assign Look_Up_Table_1[103] = 16'sb0001010000100100;
  assign Look_Up_Table_1[104] = 16'sb0001010001010101;
  assign Look_Up_Table_1[105] = 16'sb0001010010000111;
  assign Look_Up_Table_1[106] = 16'sb0001010010111001;
  assign Look_Up_Table_1[107] = 16'sb0001010011101010;
  assign Look_Up_Table_1[108] = 16'sb0001010100011100;
  assign Look_Up_Table_1[109] = 16'sb0001010101001101;
  assign Look_Up_Table_1[110] = 16'sb0001010101111111;
  assign Look_Up_Table_1[111] = 16'sb0001010110110001;
  assign Look_Up_Table_1[112] = 16'sb0001010111100010;
  assign Look_Up_Table_1[113] = 16'sb0001011000010100;
  assign Look_Up_Table_1[114] = 16'sb0001011001000101;
  assign Look_Up_Table_1[115] = 16'sb0001011001110111;
  assign Look_Up_Table_1[116] = 16'sb0001011010101000;
  assign Look_Up_Table_1[117] = 16'sb0001011011011010;
  assign Look_Up_Table_1[118] = 16'sb0001011100001011;
  assign Look_Up_Table_1[119] = 16'sb0001011100111100;
  assign Look_Up_Table_1[120] = 16'sb0001011101101110;
  assign Look_Up_Table_1[121] = 16'sb0001011110011111;
  assign Look_Up_Table_1[122] = 16'sb0001011111010001;
  assign Look_Up_Table_1[123] = 16'sb0001100000000010;
  assign Look_Up_Table_1[124] = 16'sb0001100000110011;
  assign Look_Up_Table_1[125] = 16'sb0001100001100101;
  assign Look_Up_Table_1[126] = 16'sb0001100010010110;
  assign Look_Up_Table_1[127] = 16'sb0001100011000111;
  assign Look_Up_Table_1[128] = 16'sb0001100011111001;
  assign Look_Up_Table_1[129] = 16'sb0001100100101010;
  assign Look_Up_Table_1[130] = 16'sb0001100101011011;
  assign Look_Up_Table_1[131] = 16'sb0001100110001101;
  assign Look_Up_Table_1[132] = 16'sb0001100110111110;
  assign Look_Up_Table_1[133] = 16'sb0001100111101111;
  assign Look_Up_Table_1[134] = 16'sb0001101000100000;
  assign Look_Up_Table_1[135] = 16'sb0001101001010001;
  assign Look_Up_Table_1[136] = 16'sb0001101010000011;
  assign Look_Up_Table_1[137] = 16'sb0001101010110100;
  assign Look_Up_Table_1[138] = 16'sb0001101011100101;
  assign Look_Up_Table_1[139] = 16'sb0001101100010110;
  assign Look_Up_Table_1[140] = 16'sb0001101101000111;
  assign Look_Up_Table_1[141] = 16'sb0001101101111000;
  assign Look_Up_Table_1[142] = 16'sb0001101110101001;
  assign Look_Up_Table_1[143] = 16'sb0001101111011010;
  assign Look_Up_Table_1[144] = 16'sb0001110000001100;
  assign Look_Up_Table_1[145] = 16'sb0001110000111101;
  assign Look_Up_Table_1[146] = 16'sb0001110001101110;
  assign Look_Up_Table_1[147] = 16'sb0001110010011111;
  assign Look_Up_Table_1[148] = 16'sb0001110011010000;
  assign Look_Up_Table_1[149] = 16'sb0001110100000001;
  assign Look_Up_Table_1[150] = 16'sb0001110100110001;
  assign Look_Up_Table_1[151] = 16'sb0001110101100010;
  assign Look_Up_Table_1[152] = 16'sb0001110110010011;
  assign Look_Up_Table_1[153] = 16'sb0001110111000100;
  assign Look_Up_Table_1[154] = 16'sb0001110111110101;
  assign Look_Up_Table_1[155] = 16'sb0001111000100110;
  assign Look_Up_Table_1[156] = 16'sb0001111001010111;
  assign Look_Up_Table_1[157] = 16'sb0001111010001000;
  assign Look_Up_Table_1[158] = 16'sb0001111010111000;
  assign Look_Up_Table_1[159] = 16'sb0001111011101001;
  assign Look_Up_Table_1[160] = 16'sb0001111100011010;
  assign Look_Up_Table_1[161] = 16'sb0001111101001011;
  assign Look_Up_Table_1[162] = 16'sb0001111101111011;
  assign Look_Up_Table_1[163] = 16'sb0001111110101100;
  assign Look_Up_Table_1[164] = 16'sb0001111111011101;
  assign Look_Up_Table_1[165] = 16'sb0010000000001110;
  assign Look_Up_Table_1[166] = 16'sb0010000000111110;
  assign Look_Up_Table_1[167] = 16'sb0010000001101111;
  assign Look_Up_Table_1[168] = 16'sb0010000010011111;
  assign Look_Up_Table_1[169] = 16'sb0010000011010000;
  assign Look_Up_Table_1[170] = 16'sb0010000100000001;
  assign Look_Up_Table_1[171] = 16'sb0010000100110001;
  assign Look_Up_Table_1[172] = 16'sb0010000101100010;
  assign Look_Up_Table_1[173] = 16'sb0010000110010010;
  assign Look_Up_Table_1[174] = 16'sb0010000111000011;
  assign Look_Up_Table_1[175] = 16'sb0010000111110011;
  assign Look_Up_Table_1[176] = 16'sb0010001000100100;
  assign Look_Up_Table_1[177] = 16'sb0010001001010100;
  assign Look_Up_Table_1[178] = 16'sb0010001010000100;
  assign Look_Up_Table_1[179] = 16'sb0010001010110101;
  assign Look_Up_Table_1[180] = 16'sb0010001011100101;
  assign Look_Up_Table_1[181] = 16'sb0010001100010110;
  assign Look_Up_Table_1[182] = 16'sb0010001101000110;
  assign Look_Up_Table_1[183] = 16'sb0010001101110110;
  assign Look_Up_Table_1[184] = 16'sb0010001110100111;
  assign Look_Up_Table_1[185] = 16'sb0010001111010111;
  assign Look_Up_Table_1[186] = 16'sb0010010000000111;
  assign Look_Up_Table_1[187] = 16'sb0010010000110111;
  assign Look_Up_Table_1[188] = 16'sb0010010001100111;
  assign Look_Up_Table_1[189] = 16'sb0010010010011000;
  assign Look_Up_Table_1[190] = 16'sb0010010011001000;
  assign Look_Up_Table_1[191] = 16'sb0010010011111000;
  assign Look_Up_Table_1[192] = 16'sb0010010100101000;
  assign Look_Up_Table_1[193] = 16'sb0010010101011000;
  assign Look_Up_Table_1[194] = 16'sb0010010110001000;
  assign Look_Up_Table_1[195] = 16'sb0010010110111000;
  assign Look_Up_Table_1[196] = 16'sb0010010111101000;
  assign Look_Up_Table_1[197] = 16'sb0010011000011000;
  assign Look_Up_Table_1[198] = 16'sb0010011001001000;
  assign Look_Up_Table_1[199] = 16'sb0010011001111000;
  assign Look_Up_Table_1[200] = 16'sb0010011010101000;
  assign Look_Up_Table_1[201] = 16'sb0010011011011000;
  assign Look_Up_Table_1[202] = 16'sb0010011100001000;
  assign Look_Up_Table_1[203] = 16'sb0010011100111000;
  assign Look_Up_Table_1[204] = 16'sb0010011101101000;
  assign Look_Up_Table_1[205] = 16'sb0010011110010111;
  assign Look_Up_Table_1[206] = 16'sb0010011111000111;
  assign Look_Up_Table_1[207] = 16'sb0010011111110111;
  assign Look_Up_Table_1[208] = 16'sb0010100000100111;
  assign Look_Up_Table_1[209] = 16'sb0010100001010110;
  assign Look_Up_Table_1[210] = 16'sb0010100010000110;
  assign Look_Up_Table_1[211] = 16'sb0010100010110110;
  assign Look_Up_Table_1[212] = 16'sb0010100011100101;
  assign Look_Up_Table_1[213] = 16'sb0010100100010101;
  assign Look_Up_Table_1[214] = 16'sb0010100101000101;
  assign Look_Up_Table_1[215] = 16'sb0010100101110100;
  assign Look_Up_Table_1[216] = 16'sb0010100110100100;
  assign Look_Up_Table_1[217] = 16'sb0010100111010011;
  assign Look_Up_Table_1[218] = 16'sb0010101000000011;
  assign Look_Up_Table_1[219] = 16'sb0010101000110010;
  assign Look_Up_Table_1[220] = 16'sb0010101001100010;
  assign Look_Up_Table_1[221] = 16'sb0010101010010001;
  assign Look_Up_Table_1[222] = 16'sb0010101011000001;
  assign Look_Up_Table_1[223] = 16'sb0010101011110000;
  assign Look_Up_Table_1[224] = 16'sb0010101100011111;
  assign Look_Up_Table_1[225] = 16'sb0010101101001111;
  assign Look_Up_Table_1[226] = 16'sb0010101101111110;
  assign Look_Up_Table_1[227] = 16'sb0010101110101101;
  assign Look_Up_Table_1[228] = 16'sb0010101111011100;
  assign Look_Up_Table_1[229] = 16'sb0010110000001100;
  assign Look_Up_Table_1[230] = 16'sb0010110000111011;
  assign Look_Up_Table_1[231] = 16'sb0010110001101010;
  assign Look_Up_Table_1[232] = 16'sb0010110010011001;
  assign Look_Up_Table_1[233] = 16'sb0010110011001000;
  assign Look_Up_Table_1[234] = 16'sb0010110011110111;
  assign Look_Up_Table_1[235] = 16'sb0010110100100110;
  assign Look_Up_Table_1[236] = 16'sb0010110101010101;
  assign Look_Up_Table_1[237] = 16'sb0010110110000100;
  assign Look_Up_Table_1[238] = 16'sb0010110110110011;
  assign Look_Up_Table_1[239] = 16'sb0010110111100010;
  assign Look_Up_Table_1[240] = 16'sb0010111000010001;
  assign Look_Up_Table_1[241] = 16'sb0010111001000000;
  assign Look_Up_Table_1[242] = 16'sb0010111001101111;
  assign Look_Up_Table_1[243] = 16'sb0010111010011110;
  assign Look_Up_Table_1[244] = 16'sb0010111011001100;
  assign Look_Up_Table_1[245] = 16'sb0010111011111011;
  assign Look_Up_Table_1[246] = 16'sb0010111100101010;
  assign Look_Up_Table_1[247] = 16'sb0010111101011001;
  assign Look_Up_Table_1[248] = 16'sb0010111110000111;
  assign Look_Up_Table_1[249] = 16'sb0010111110110110;
  assign Look_Up_Table_1[250] = 16'sb0010111111100101;
  assign Look_Up_Table_1[251] = 16'sb0011000000010011;
  assign Look_Up_Table_1[252] = 16'sb0011000001000010;
  assign Look_Up_Table_1[253] = 16'sb0011000001110000;
  assign Look_Up_Table_1[254] = 16'sb0011000010011111;
  assign Look_Up_Table_1[255] = 16'sb0011000011001101;
  assign Look_Up_Table_1[256] = 16'sb0011000011111100;
  assign Look_Up_Table_1[257] = 16'sb0011000100101010;
  assign Look_Up_Table_1[258] = 16'sb0011000101011001;
  assign Look_Up_Table_1[259] = 16'sb0011000110000111;
  assign Look_Up_Table_1[260] = 16'sb0011000110110101;
  assign Look_Up_Table_1[261] = 16'sb0011000111100100;
  assign Look_Up_Table_1[262] = 16'sb0011001000010010;
  assign Look_Up_Table_1[263] = 16'sb0011001001000000;
  assign Look_Up_Table_1[264] = 16'sb0011001001101110;
  assign Look_Up_Table_1[265] = 16'sb0011001010011101;
  assign Look_Up_Table_1[266] = 16'sb0011001011001011;
  assign Look_Up_Table_1[267] = 16'sb0011001011111001;
  assign Look_Up_Table_1[268] = 16'sb0011001100100111;
  assign Look_Up_Table_1[269] = 16'sb0011001101010101;
  assign Look_Up_Table_1[270] = 16'sb0011001110000011;
  assign Look_Up_Table_1[271] = 16'sb0011001110110001;
  assign Look_Up_Table_1[272] = 16'sb0011001111011111;
  assign Look_Up_Table_1[273] = 16'sb0011010000001101;
  assign Look_Up_Table_1[274] = 16'sb0011010000111011;
  assign Look_Up_Table_1[275] = 16'sb0011010001101001;
  assign Look_Up_Table_1[276] = 16'sb0011010010010111;
  assign Look_Up_Table_1[277] = 16'sb0011010011000100;
  assign Look_Up_Table_1[278] = 16'sb0011010011110010;
  assign Look_Up_Table_1[279] = 16'sb0011010100100000;
  assign Look_Up_Table_1[280] = 16'sb0011010101001110;
  assign Look_Up_Table_1[281] = 16'sb0011010101111011;
  assign Look_Up_Table_1[282] = 16'sb0011010110101001;
  assign Look_Up_Table_1[283] = 16'sb0011010111010111;
  assign Look_Up_Table_1[284] = 16'sb0011011000000100;
  assign Look_Up_Table_1[285] = 16'sb0011011000110010;
  assign Look_Up_Table_1[286] = 16'sb0011011001011111;
  assign Look_Up_Table_1[287] = 16'sb0011011010001101;
  assign Look_Up_Table_1[288] = 16'sb0011011010111010;
  assign Look_Up_Table_1[289] = 16'sb0011011011101000;
  assign Look_Up_Table_1[290] = 16'sb0011011100010101;
  assign Look_Up_Table_1[291] = 16'sb0011011101000010;
  assign Look_Up_Table_1[292] = 16'sb0011011101110000;
  assign Look_Up_Table_1[293] = 16'sb0011011110011101;
  assign Look_Up_Table_1[294] = 16'sb0011011111001010;
  assign Look_Up_Table_1[295] = 16'sb0011011111110111;
  assign Look_Up_Table_1[296] = 16'sb0011100000100101;
  assign Look_Up_Table_1[297] = 16'sb0011100001010010;
  assign Look_Up_Table_1[298] = 16'sb0011100001111111;
  assign Look_Up_Table_1[299] = 16'sb0011100010101100;
  assign Look_Up_Table_1[300] = 16'sb0011100011011001;
  assign Look_Up_Table_1[301] = 16'sb0011100100000110;
  assign Look_Up_Table_1[302] = 16'sb0011100100110011;
  assign Look_Up_Table_1[303] = 16'sb0011100101100000;
  assign Look_Up_Table_1[304] = 16'sb0011100110001101;
  assign Look_Up_Table_1[305] = 16'sb0011100110111010;
  assign Look_Up_Table_1[306] = 16'sb0011100111100111;
  assign Look_Up_Table_1[307] = 16'sb0011101000010011;
  assign Look_Up_Table_1[308] = 16'sb0011101001000000;
  assign Look_Up_Table_1[309] = 16'sb0011101001101101;
  assign Look_Up_Table_1[310] = 16'sb0011101010011010;
  assign Look_Up_Table_1[311] = 16'sb0011101011000110;
  assign Look_Up_Table_1[312] = 16'sb0011101011110011;
  assign Look_Up_Table_1[313] = 16'sb0011101100100000;
  assign Look_Up_Table_1[314] = 16'sb0011101101001100;
  assign Look_Up_Table_1[315] = 16'sb0011101101111001;
  assign Look_Up_Table_1[316] = 16'sb0011101110100101;
  assign Look_Up_Table_1[317] = 16'sb0011101111010010;
  assign Look_Up_Table_1[318] = 16'sb0011101111111110;
  assign Look_Up_Table_1[319] = 16'sb0011110000101010;
  assign Look_Up_Table_1[320] = 16'sb0011110001010111;
  assign Look_Up_Table_1[321] = 16'sb0011110010000011;
  assign Look_Up_Table_1[322] = 16'sb0011110010101111;
  assign Look_Up_Table_1[323] = 16'sb0011110011011100;
  assign Look_Up_Table_1[324] = 16'sb0011110100001000;
  assign Look_Up_Table_1[325] = 16'sb0011110100110100;
  assign Look_Up_Table_1[326] = 16'sb0011110101100000;
  assign Look_Up_Table_1[327] = 16'sb0011110110001100;
  assign Look_Up_Table_1[328] = 16'sb0011110110111000;
  assign Look_Up_Table_1[329] = 16'sb0011110111100100;
  assign Look_Up_Table_1[330] = 16'sb0011111000010000;
  assign Look_Up_Table_1[331] = 16'sb0011111000111100;
  assign Look_Up_Table_1[332] = 16'sb0011111001101000;
  assign Look_Up_Table_1[333] = 16'sb0011111010010100;
  assign Look_Up_Table_1[334] = 16'sb0011111011000000;
  assign Look_Up_Table_1[335] = 16'sb0011111011101100;
  assign Look_Up_Table_1[336] = 16'sb0011111100010111;
  assign Look_Up_Table_1[337] = 16'sb0011111101000011;
  assign Look_Up_Table_1[338] = 16'sb0011111101101111;
  assign Look_Up_Table_1[339] = 16'sb0011111110011010;
  assign Look_Up_Table_1[340] = 16'sb0011111111000110;
  assign Look_Up_Table_1[341] = 16'sb0011111111110001;
  assign Look_Up_Table_1[342] = 16'sb0100000000011101;
  assign Look_Up_Table_1[343] = 16'sb0100000001001000;
  assign Look_Up_Table_1[344] = 16'sb0100000001110100;
  assign Look_Up_Table_1[345] = 16'sb0100000010011111;
  assign Look_Up_Table_1[346] = 16'sb0100000011001011;
  assign Look_Up_Table_1[347] = 16'sb0100000011110110;
  assign Look_Up_Table_1[348] = 16'sb0100000100100001;
  assign Look_Up_Table_1[349] = 16'sb0100000101001101;
  assign Look_Up_Table_1[350] = 16'sb0100000101111000;
  assign Look_Up_Table_1[351] = 16'sb0100000110100011;
  assign Look_Up_Table_1[352] = 16'sb0100000111001110;
  assign Look_Up_Table_1[353] = 16'sb0100000111111001;
  assign Look_Up_Table_1[354] = 16'sb0100001000100100;
  assign Look_Up_Table_1[355] = 16'sb0100001001001111;
  assign Look_Up_Table_1[356] = 16'sb0100001001111010;
  assign Look_Up_Table_1[357] = 16'sb0100001010100101;
  assign Look_Up_Table_1[358] = 16'sb0100001011010000;
  assign Look_Up_Table_1[359] = 16'sb0100001011111011;
  assign Look_Up_Table_1[360] = 16'sb0100001100100110;
  assign Look_Up_Table_1[361] = 16'sb0100001101010001;
  assign Look_Up_Table_1[362] = 16'sb0100001101111011;
  assign Look_Up_Table_1[363] = 16'sb0100001110100110;
  assign Look_Up_Table_1[364] = 16'sb0100001111010001;
  assign Look_Up_Table_1[365] = 16'sb0100001111111011;
  assign Look_Up_Table_1[366] = 16'sb0100010000100110;
  assign Look_Up_Table_1[367] = 16'sb0100010001010000;
  assign Look_Up_Table_1[368] = 16'sb0100010001111011;
  assign Look_Up_Table_1[369] = 16'sb0100010010100101;
  assign Look_Up_Table_1[370] = 16'sb0100010011010000;
  assign Look_Up_Table_1[371] = 16'sb0100010011111010;
  assign Look_Up_Table_1[372] = 16'sb0100010100100100;
  assign Look_Up_Table_1[373] = 16'sb0100010101001111;
  assign Look_Up_Table_1[374] = 16'sb0100010101111001;
  assign Look_Up_Table_1[375] = 16'sb0100010110100011;
  assign Look_Up_Table_1[376] = 16'sb0100010111001101;
  assign Look_Up_Table_1[377] = 16'sb0100010111110111;
  assign Look_Up_Table_1[378] = 16'sb0100011000100001;
  assign Look_Up_Table_1[379] = 16'sb0100011001001011;
  assign Look_Up_Table_1[380] = 16'sb0100011001110101;
  assign Look_Up_Table_1[381] = 16'sb0100011010011111;
  assign Look_Up_Table_1[382] = 16'sb0100011011001001;
  assign Look_Up_Table_1[383] = 16'sb0100011011110011;
  assign Look_Up_Table_1[384] = 16'sb0100011100011101;
  assign Look_Up_Table_1[385] = 16'sb0100011101000111;
  assign Look_Up_Table_1[386] = 16'sb0100011101110000;
  assign Look_Up_Table_1[387] = 16'sb0100011110011010;
  assign Look_Up_Table_1[388] = 16'sb0100011111000100;
  assign Look_Up_Table_1[389] = 16'sb0100011111101101;
  assign Look_Up_Table_1[390] = 16'sb0100100000010111;
  assign Look_Up_Table_1[391] = 16'sb0100100001000000;
  assign Look_Up_Table_1[392] = 16'sb0100100001101010;
  assign Look_Up_Table_1[393] = 16'sb0100100010010011;
  assign Look_Up_Table_1[394] = 16'sb0100100010111101;
  assign Look_Up_Table_1[395] = 16'sb0100100011100110;
  assign Look_Up_Table_1[396] = 16'sb0100100100001111;
  assign Look_Up_Table_1[397] = 16'sb0100100100111001;
  assign Look_Up_Table_1[398] = 16'sb0100100101100010;
  assign Look_Up_Table_1[399] = 16'sb0100100110001011;
  assign Look_Up_Table_1[400] = 16'sb0100100110110100;
  assign Look_Up_Table_1[401] = 16'sb0100100111011101;
  assign Look_Up_Table_1[402] = 16'sb0100101000000110;
  assign Look_Up_Table_1[403] = 16'sb0100101000101111;
  assign Look_Up_Table_1[404] = 16'sb0100101001011000;
  assign Look_Up_Table_1[405] = 16'sb0100101010000001;
  assign Look_Up_Table_1[406] = 16'sb0100101010101010;
  assign Look_Up_Table_1[407] = 16'sb0100101011010011;
  assign Look_Up_Table_1[408] = 16'sb0100101011111011;
  assign Look_Up_Table_1[409] = 16'sb0100101100100100;
  assign Look_Up_Table_1[410] = 16'sb0100101101001101;
  assign Look_Up_Table_1[411] = 16'sb0100101101110101;
  assign Look_Up_Table_1[412] = 16'sb0100101110011110;
  assign Look_Up_Table_1[413] = 16'sb0100101111000111;
  assign Look_Up_Table_1[414] = 16'sb0100101111101111;
  assign Look_Up_Table_1[415] = 16'sb0100110000010111;
  assign Look_Up_Table_1[416] = 16'sb0100110001000000;
  assign Look_Up_Table_1[417] = 16'sb0100110001101000;
  assign Look_Up_Table_1[418] = 16'sb0100110010010001;
  assign Look_Up_Table_1[419] = 16'sb0100110010111001;
  assign Look_Up_Table_1[420] = 16'sb0100110011100001;
  assign Look_Up_Table_1[421] = 16'sb0100110100001001;
  assign Look_Up_Table_1[422] = 16'sb0100110100110001;
  assign Look_Up_Table_1[423] = 16'sb0100110101011001;
  assign Look_Up_Table_1[424] = 16'sb0100110110000001;
  assign Look_Up_Table_1[425] = 16'sb0100110110101001;
  assign Look_Up_Table_1[426] = 16'sb0100110111010001;
  assign Look_Up_Table_1[427] = 16'sb0100110111111001;
  assign Look_Up_Table_1[428] = 16'sb0100111000100001;
  assign Look_Up_Table_1[429] = 16'sb0100111001001001;
  assign Look_Up_Table_1[430] = 16'sb0100111001110001;
  assign Look_Up_Table_1[431] = 16'sb0100111010011000;
  assign Look_Up_Table_1[432] = 16'sb0100111011000000;
  assign Look_Up_Table_1[433] = 16'sb0100111011101000;
  assign Look_Up_Table_1[434] = 16'sb0100111100001111;
  assign Look_Up_Table_1[435] = 16'sb0100111100110111;
  assign Look_Up_Table_1[436] = 16'sb0100111101011110;
  assign Look_Up_Table_1[437] = 16'sb0100111110000101;
  assign Look_Up_Table_1[438] = 16'sb0100111110101101;
  assign Look_Up_Table_1[439] = 16'sb0100111111010100;
  assign Look_Up_Table_1[440] = 16'sb0100111111111011;
  assign Look_Up_Table_1[441] = 16'sb0101000000100011;
  assign Look_Up_Table_1[442] = 16'sb0101000001001010;
  assign Look_Up_Table_1[443] = 16'sb0101000001110001;
  assign Look_Up_Table_1[444] = 16'sb0101000010011000;
  assign Look_Up_Table_1[445] = 16'sb0101000010111111;
  assign Look_Up_Table_1[446] = 16'sb0101000011100110;
  assign Look_Up_Table_1[447] = 16'sb0101000100001101;
  assign Look_Up_Table_1[448] = 16'sb0101000100110100;
  assign Look_Up_Table_1[449] = 16'sb0101000101011011;
  assign Look_Up_Table_1[450] = 16'sb0101000110000001;
  assign Look_Up_Table_1[451] = 16'sb0101000110101000;
  assign Look_Up_Table_1[452] = 16'sb0101000111001111;
  assign Look_Up_Table_1[453] = 16'sb0101000111110101;
  assign Look_Up_Table_1[454] = 16'sb0101001000011100;
  assign Look_Up_Table_1[455] = 16'sb0101001001000011;
  assign Look_Up_Table_1[456] = 16'sb0101001001101001;
  assign Look_Up_Table_1[457] = 16'sb0101001010010000;
  assign Look_Up_Table_1[458] = 16'sb0101001010110110;
  assign Look_Up_Table_1[459] = 16'sb0101001011011100;
  assign Look_Up_Table_1[460] = 16'sb0101001100000011;
  assign Look_Up_Table_1[461] = 16'sb0101001100101001;
  assign Look_Up_Table_1[462] = 16'sb0101001101001111;
  assign Look_Up_Table_1[463] = 16'sb0101001101110101;
  assign Look_Up_Table_1[464] = 16'sb0101001110011011;
  assign Look_Up_Table_1[465] = 16'sb0101001111000001;
  assign Look_Up_Table_1[466] = 16'sb0101001111100111;
  assign Look_Up_Table_1[467] = 16'sb0101010000001101;
  assign Look_Up_Table_1[468] = 16'sb0101010000110011;
  assign Look_Up_Table_1[469] = 16'sb0101010001011001;
  assign Look_Up_Table_1[470] = 16'sb0101010001111111;
  assign Look_Up_Table_1[471] = 16'sb0101010010100100;
  assign Look_Up_Table_1[472] = 16'sb0101010011001010;
  assign Look_Up_Table_1[473] = 16'sb0101010011110000;
  assign Look_Up_Table_1[474] = 16'sb0101010100010101;
  assign Look_Up_Table_1[475] = 16'sb0101010100111011;
  assign Look_Up_Table_1[476] = 16'sb0101010101100000;
  assign Look_Up_Table_1[477] = 16'sb0101010110000110;
  assign Look_Up_Table_1[478] = 16'sb0101010110101011;
  assign Look_Up_Table_1[479] = 16'sb0101010111010000;
  assign Look_Up_Table_1[480] = 16'sb0101010111110110;
  assign Look_Up_Table_1[481] = 16'sb0101011000011011;
  assign Look_Up_Table_1[482] = 16'sb0101011001000000;
  assign Look_Up_Table_1[483] = 16'sb0101011001100101;
  assign Look_Up_Table_1[484] = 16'sb0101011010001010;
  assign Look_Up_Table_1[485] = 16'sb0101011010101111;
  assign Look_Up_Table_1[486] = 16'sb0101011011010100;
  assign Look_Up_Table_1[487] = 16'sb0101011011111001;
  assign Look_Up_Table_1[488] = 16'sb0101011100011110;
  assign Look_Up_Table_1[489] = 16'sb0101011101000011;
  assign Look_Up_Table_1[490] = 16'sb0101011101100111;
  assign Look_Up_Table_1[491] = 16'sb0101011110001100;
  assign Look_Up_Table_1[492] = 16'sb0101011110110001;
  assign Look_Up_Table_1[493] = 16'sb0101011111010101;
  assign Look_Up_Table_1[494] = 16'sb0101011111111010;
  assign Look_Up_Table_1[495] = 16'sb0101100000011110;
  assign Look_Up_Table_1[496] = 16'sb0101100001000011;
  assign Look_Up_Table_1[497] = 16'sb0101100001100111;
  assign Look_Up_Table_1[498] = 16'sb0101100010001100;
  assign Look_Up_Table_1[499] = 16'sb0101100010110000;
  assign Look_Up_Table_1[500] = 16'sb0101100011010100;
  assign Look_Up_Table_1[501] = 16'sb0101100011111000;
  assign Look_Up_Table_1[502] = 16'sb0101100100011100;
  assign Look_Up_Table_1[503] = 16'sb0101100101000000;
  assign Look_Up_Table_1[504] = 16'sb0101100101100100;
  assign Look_Up_Table_1[505] = 16'sb0101100110001000;
  assign Look_Up_Table_1[506] = 16'sb0101100110101100;
  assign Look_Up_Table_1[507] = 16'sb0101100111010000;
  assign Look_Up_Table_1[508] = 16'sb0101100111110100;
  assign Look_Up_Table_1[509] = 16'sb0101101000011000;
  assign Look_Up_Table_1[510] = 16'sb0101101000111011;
  assign Look_Up_Table_1[511] = 16'sb0101101001011111;
  assign Look_Up_Table_1[512] = 16'sb0101101010000010;
  assign Look_Up_Table_1[513] = 16'sb0101101010100110;
  assign Look_Up_Table_1[514] = 16'sb0101101011001001;
  assign Look_Up_Table_1[515] = 16'sb0101101011101101;
  assign Look_Up_Table_1[516] = 16'sb0101101100010000;
  assign Look_Up_Table_1[517] = 16'sb0101101100110100;
  assign Look_Up_Table_1[518] = 16'sb0101101101010111;
  assign Look_Up_Table_1[519] = 16'sb0101101101111010;
  assign Look_Up_Table_1[520] = 16'sb0101101110011101;
  assign Look_Up_Table_1[521] = 16'sb0101101111000000;
  assign Look_Up_Table_1[522] = 16'sb0101101111100011;
  assign Look_Up_Table_1[523] = 16'sb0101110000000110;
  assign Look_Up_Table_1[524] = 16'sb0101110000101001;
  assign Look_Up_Table_1[525] = 16'sb0101110001001100;
  assign Look_Up_Table_1[526] = 16'sb0101110001101111;
  assign Look_Up_Table_1[527] = 16'sb0101110010010001;
  assign Look_Up_Table_1[528] = 16'sb0101110010110100;
  assign Look_Up_Table_1[529] = 16'sb0101110011010111;
  assign Look_Up_Table_1[530] = 16'sb0101110011111001;
  assign Look_Up_Table_1[531] = 16'sb0101110100011100;
  assign Look_Up_Table_1[532] = 16'sb0101110100111110;
  assign Look_Up_Table_1[533] = 16'sb0101110101100001;
  assign Look_Up_Table_1[534] = 16'sb0101110110000011;
  assign Look_Up_Table_1[535] = 16'sb0101110110100101;
  assign Look_Up_Table_1[536] = 16'sb0101110111001000;
  assign Look_Up_Table_1[537] = 16'sb0101110111101010;
  assign Look_Up_Table_1[538] = 16'sb0101111000001100;
  assign Look_Up_Table_1[539] = 16'sb0101111000101110;
  assign Look_Up_Table_1[540] = 16'sb0101111001010000;
  assign Look_Up_Table_1[541] = 16'sb0101111001110010;
  assign Look_Up_Table_1[542] = 16'sb0101111010010100;
  assign Look_Up_Table_1[543] = 16'sb0101111010110110;
  assign Look_Up_Table_1[544] = 16'sb0101111011010111;
  assign Look_Up_Table_1[545] = 16'sb0101111011111001;
  assign Look_Up_Table_1[546] = 16'sb0101111100011011;
  assign Look_Up_Table_1[547] = 16'sb0101111100111100;
  assign Look_Up_Table_1[548] = 16'sb0101111101011110;
  assign Look_Up_Table_1[549] = 16'sb0101111110000000;
  assign Look_Up_Table_1[550] = 16'sb0101111110100001;
  assign Look_Up_Table_1[551] = 16'sb0101111111000010;
  assign Look_Up_Table_1[552] = 16'sb0101111111100100;
  assign Look_Up_Table_1[553] = 16'sb0110000000000101;
  assign Look_Up_Table_1[554] = 16'sb0110000000100110;
  assign Look_Up_Table_1[555] = 16'sb0110000001000111;
  assign Look_Up_Table_1[556] = 16'sb0110000001101000;
  assign Look_Up_Table_1[557] = 16'sb0110000010001001;
  assign Look_Up_Table_1[558] = 16'sb0110000010101010;
  assign Look_Up_Table_1[559] = 16'sb0110000011001011;
  assign Look_Up_Table_1[560] = 16'sb0110000011101100;
  assign Look_Up_Table_1[561] = 16'sb0110000100001101;
  assign Look_Up_Table_1[562] = 16'sb0110000100101110;
  assign Look_Up_Table_1[563] = 16'sb0110000101001110;
  assign Look_Up_Table_1[564] = 16'sb0110000101101111;
  assign Look_Up_Table_1[565] = 16'sb0110000110010000;
  assign Look_Up_Table_1[566] = 16'sb0110000110110000;
  assign Look_Up_Table_1[567] = 16'sb0110000111010001;
  assign Look_Up_Table_1[568] = 16'sb0110000111110001;
  assign Look_Up_Table_1[569] = 16'sb0110001000010001;
  assign Look_Up_Table_1[570] = 16'sb0110001000110010;
  assign Look_Up_Table_1[571] = 16'sb0110001001010010;
  assign Look_Up_Table_1[572] = 16'sb0110001001110010;
  assign Look_Up_Table_1[573] = 16'sb0110001010010010;
  assign Look_Up_Table_1[574] = 16'sb0110001010110010;
  assign Look_Up_Table_1[575] = 16'sb0110001011010010;
  assign Look_Up_Table_1[576] = 16'sb0110001011110010;
  assign Look_Up_Table_1[577] = 16'sb0110001100010010;
  assign Look_Up_Table_1[578] = 16'sb0110001100110010;
  assign Look_Up_Table_1[579] = 16'sb0110001101010001;
  assign Look_Up_Table_1[580] = 16'sb0110001101110001;
  assign Look_Up_Table_1[581] = 16'sb0110001110010001;
  assign Look_Up_Table_1[582] = 16'sb0110001110110000;
  assign Look_Up_Table_1[583] = 16'sb0110001111010000;
  assign Look_Up_Table_1[584] = 16'sb0110001111101111;
  assign Look_Up_Table_1[585] = 16'sb0110010000001111;
  assign Look_Up_Table_1[586] = 16'sb0110010000101110;
  assign Look_Up_Table_1[587] = 16'sb0110010001001101;
  assign Look_Up_Table_1[588] = 16'sb0110010001101100;
  assign Look_Up_Table_1[589] = 16'sb0110010010001011;
  assign Look_Up_Table_1[590] = 16'sb0110010010101011;
  assign Look_Up_Table_1[591] = 16'sb0110010011001010;
  assign Look_Up_Table_1[592] = 16'sb0110010011101001;
  assign Look_Up_Table_1[593] = 16'sb0110010100000111;
  assign Look_Up_Table_1[594] = 16'sb0110010100100110;
  assign Look_Up_Table_1[595] = 16'sb0110010101000101;
  assign Look_Up_Table_1[596] = 16'sb0110010101100100;
  assign Look_Up_Table_1[597] = 16'sb0110010110000010;
  assign Look_Up_Table_1[598] = 16'sb0110010110100001;
  assign Look_Up_Table_1[599] = 16'sb0110010111000000;
  assign Look_Up_Table_1[600] = 16'sb0110010111011110;
  assign Look_Up_Table_1[601] = 16'sb0110010111111100;
  assign Look_Up_Table_1[602] = 16'sb0110011000011011;
  assign Look_Up_Table_1[603] = 16'sb0110011000111001;
  assign Look_Up_Table_1[604] = 16'sb0110011001010111;
  assign Look_Up_Table_1[605] = 16'sb0110011001110101;
  assign Look_Up_Table_1[606] = 16'sb0110011010010011;
  assign Look_Up_Table_1[607] = 16'sb0110011010110010;
  assign Look_Up_Table_1[608] = 16'sb0110011011010000;
  assign Look_Up_Table_1[609] = 16'sb0110011011101101;
  assign Look_Up_Table_1[610] = 16'sb0110011100001011;
  assign Look_Up_Table_1[611] = 16'sb0110011100101001;
  assign Look_Up_Table_1[612] = 16'sb0110011101000111;
  assign Look_Up_Table_1[613] = 16'sb0110011101100100;
  assign Look_Up_Table_1[614] = 16'sb0110011110000010;
  assign Look_Up_Table_1[615] = 16'sb0110011110100000;
  assign Look_Up_Table_1[616] = 16'sb0110011110111101;
  assign Look_Up_Table_1[617] = 16'sb0110011111011010;
  assign Look_Up_Table_1[618] = 16'sb0110011111111000;
  assign Look_Up_Table_1[619] = 16'sb0110100000010101;
  assign Look_Up_Table_1[620] = 16'sb0110100000110010;
  assign Look_Up_Table_1[621] = 16'sb0110100001010000;
  assign Look_Up_Table_1[622] = 16'sb0110100001101101;
  assign Look_Up_Table_1[623] = 16'sb0110100010001010;
  assign Look_Up_Table_1[624] = 16'sb0110100010100111;
  assign Look_Up_Table_1[625] = 16'sb0110100011000100;
  assign Look_Up_Table_1[626] = 16'sb0110100011100000;
  assign Look_Up_Table_1[627] = 16'sb0110100011111101;
  assign Look_Up_Table_1[628] = 16'sb0110100100011010;
  assign Look_Up_Table_1[629] = 16'sb0110100100110111;
  assign Look_Up_Table_1[630] = 16'sb0110100101010011;
  assign Look_Up_Table_1[631] = 16'sb0110100101110000;
  assign Look_Up_Table_1[632] = 16'sb0110100110001100;
  assign Look_Up_Table_1[633] = 16'sb0110100110101001;
  assign Look_Up_Table_1[634] = 16'sb0110100111000101;
  assign Look_Up_Table_1[635] = 16'sb0110100111100001;
  assign Look_Up_Table_1[636] = 16'sb0110100111111101;
  assign Look_Up_Table_1[637] = 16'sb0110101000011010;
  assign Look_Up_Table_1[638] = 16'sb0110101000110110;
  assign Look_Up_Table_1[639] = 16'sb0110101001010010;
  assign Look_Up_Table_1[640] = 16'sb0110101001101110;
  assign Look_Up_Table_1[641] = 16'sb0110101010001001;
  assign Look_Up_Table_1[642] = 16'sb0110101010100101;
  assign Look_Up_Table_1[643] = 16'sb0110101011000001;
  assign Look_Up_Table_1[644] = 16'sb0110101011011101;
  assign Look_Up_Table_1[645] = 16'sb0110101011111000;
  assign Look_Up_Table_1[646] = 16'sb0110101100010100;
  assign Look_Up_Table_1[647] = 16'sb0110101100110000;
  assign Look_Up_Table_1[648] = 16'sb0110101101001011;
  assign Look_Up_Table_1[649] = 16'sb0110101101100110;
  assign Look_Up_Table_1[650] = 16'sb0110101110000010;
  assign Look_Up_Table_1[651] = 16'sb0110101110011101;
  assign Look_Up_Table_1[652] = 16'sb0110101110111000;
  assign Look_Up_Table_1[653] = 16'sb0110101111010011;
  assign Look_Up_Table_1[654] = 16'sb0110101111101110;
  assign Look_Up_Table_1[655] = 16'sb0110110000001001;
  assign Look_Up_Table_1[656] = 16'sb0110110000100100;
  assign Look_Up_Table_1[657] = 16'sb0110110000111111;
  assign Look_Up_Table_1[658] = 16'sb0110110001011010;
  assign Look_Up_Table_1[659] = 16'sb0110110001110101;
  assign Look_Up_Table_1[660] = 16'sb0110110010001111;
  assign Look_Up_Table_1[661] = 16'sb0110110010101010;
  assign Look_Up_Table_1[662] = 16'sb0110110011000100;
  assign Look_Up_Table_1[663] = 16'sb0110110011011111;
  assign Look_Up_Table_1[664] = 16'sb0110110011111001;
  assign Look_Up_Table_1[665] = 16'sb0110110100010100;
  assign Look_Up_Table_1[666] = 16'sb0110110100101110;
  assign Look_Up_Table_1[667] = 16'sb0110110101001000;
  assign Look_Up_Table_1[668] = 16'sb0110110101100010;
  assign Look_Up_Table_1[669] = 16'sb0110110101111100;
  assign Look_Up_Table_1[670] = 16'sb0110110110010110;
  assign Look_Up_Table_1[671] = 16'sb0110110110110000;
  assign Look_Up_Table_1[672] = 16'sb0110110111001010;
  assign Look_Up_Table_1[673] = 16'sb0110110111100100;
  assign Look_Up_Table_1[674] = 16'sb0110110111111110;
  assign Look_Up_Table_1[675] = 16'sb0110111000010111;
  assign Look_Up_Table_1[676] = 16'sb0110111000110001;
  assign Look_Up_Table_1[677] = 16'sb0110111001001010;
  assign Look_Up_Table_1[678] = 16'sb0110111001100100;
  assign Look_Up_Table_1[679] = 16'sb0110111001111101;
  assign Look_Up_Table_1[680] = 16'sb0110111010010111;
  assign Look_Up_Table_1[681] = 16'sb0110111010110000;
  assign Look_Up_Table_1[682] = 16'sb0110111011001001;
  assign Look_Up_Table_1[683] = 16'sb0110111011100010;
  assign Look_Up_Table_1[684] = 16'sb0110111011111011;
  assign Look_Up_Table_1[685] = 16'sb0110111100010100;
  assign Look_Up_Table_1[686] = 16'sb0110111100101101;
  assign Look_Up_Table_1[687] = 16'sb0110111101000110;
  assign Look_Up_Table_1[688] = 16'sb0110111101011111;
  assign Look_Up_Table_1[689] = 16'sb0110111101111000;
  assign Look_Up_Table_1[690] = 16'sb0110111110010000;
  assign Look_Up_Table_1[691] = 16'sb0110111110101001;
  assign Look_Up_Table_1[692] = 16'sb0110111111000010;
  assign Look_Up_Table_1[693] = 16'sb0110111111011010;
  assign Look_Up_Table_1[694] = 16'sb0110111111110010;
  assign Look_Up_Table_1[695] = 16'sb0111000000001011;
  assign Look_Up_Table_1[696] = 16'sb0111000000100011;
  assign Look_Up_Table_1[697] = 16'sb0111000000111011;
  assign Look_Up_Table_1[698] = 16'sb0111000001010011;
  assign Look_Up_Table_1[699] = 16'sb0111000001101011;
  assign Look_Up_Table_1[700] = 16'sb0111000010000011;
  assign Look_Up_Table_1[701] = 16'sb0111000010011011;
  assign Look_Up_Table_1[702] = 16'sb0111000010110011;
  assign Look_Up_Table_1[703] = 16'sb0111000011001011;
  assign Look_Up_Table_1[704] = 16'sb0111000011100011;
  assign Look_Up_Table_1[705] = 16'sb0111000011111010;
  assign Look_Up_Table_1[706] = 16'sb0111000100010010;
  assign Look_Up_Table_1[707] = 16'sb0111000100101010;
  assign Look_Up_Table_1[708] = 16'sb0111000101000001;
  assign Look_Up_Table_1[709] = 16'sb0111000101011000;
  assign Look_Up_Table_1[710] = 16'sb0111000101110000;
  assign Look_Up_Table_1[711] = 16'sb0111000110000111;
  assign Look_Up_Table_1[712] = 16'sb0111000110011110;
  assign Look_Up_Table_1[713] = 16'sb0111000110110101;
  assign Look_Up_Table_1[714] = 16'sb0111000111001100;
  assign Look_Up_Table_1[715] = 16'sb0111000111100011;
  assign Look_Up_Table_1[716] = 16'sb0111000111111010;
  assign Look_Up_Table_1[717] = 16'sb0111001000010001;
  assign Look_Up_Table_1[718] = 16'sb0111001000101000;
  assign Look_Up_Table_1[719] = 16'sb0111001000111111;
  assign Look_Up_Table_1[720] = 16'sb0111001001010101;
  assign Look_Up_Table_1[721] = 16'sb0111001001101100;
  assign Look_Up_Table_1[722] = 16'sb0111001010000010;
  assign Look_Up_Table_1[723] = 16'sb0111001010011001;
  assign Look_Up_Table_1[724] = 16'sb0111001010101111;
  assign Look_Up_Table_1[725] = 16'sb0111001011000101;
  assign Look_Up_Table_1[726] = 16'sb0111001011011100;
  assign Look_Up_Table_1[727] = 16'sb0111001011110010;
  assign Look_Up_Table_1[728] = 16'sb0111001100001000;
  assign Look_Up_Table_1[729] = 16'sb0111001100011110;
  assign Look_Up_Table_1[730] = 16'sb0111001100110100;
  assign Look_Up_Table_1[731] = 16'sb0111001101001010;
  assign Look_Up_Table_1[732] = 16'sb0111001101011111;
  assign Look_Up_Table_1[733] = 16'sb0111001101110101;
  assign Look_Up_Table_1[734] = 16'sb0111001110001011;
  assign Look_Up_Table_1[735] = 16'sb0111001110100000;
  assign Look_Up_Table_1[736] = 16'sb0111001110110110;
  assign Look_Up_Table_1[737] = 16'sb0111001111001011;
  assign Look_Up_Table_1[738] = 16'sb0111001111100001;
  assign Look_Up_Table_1[739] = 16'sb0111001111110110;
  assign Look_Up_Table_1[740] = 16'sb0111010000001011;
  assign Look_Up_Table_1[741] = 16'sb0111010000100001;
  assign Look_Up_Table_1[742] = 16'sb0111010000110110;
  assign Look_Up_Table_1[743] = 16'sb0111010001001011;
  assign Look_Up_Table_1[744] = 16'sb0111010001100000;
  assign Look_Up_Table_1[745] = 16'sb0111010001110101;
  assign Look_Up_Table_1[746] = 16'sb0111010010001001;
  assign Look_Up_Table_1[747] = 16'sb0111010010011110;
  assign Look_Up_Table_1[748] = 16'sb0111010010110011;
  assign Look_Up_Table_1[749] = 16'sb0111010011000111;
  assign Look_Up_Table_1[750] = 16'sb0111010011011100;
  assign Look_Up_Table_1[751] = 16'sb0111010011110000;
  assign Look_Up_Table_1[752] = 16'sb0111010100000101;
  assign Look_Up_Table_1[753] = 16'sb0111010100011001;
  assign Look_Up_Table_1[754] = 16'sb0111010100101101;
  assign Look_Up_Table_1[755] = 16'sb0111010101000010;
  assign Look_Up_Table_1[756] = 16'sb0111010101010110;
  assign Look_Up_Table_1[757] = 16'sb0111010101101010;
  assign Look_Up_Table_1[758] = 16'sb0111010101111110;
  assign Look_Up_Table_1[759] = 16'sb0111010110010010;
  assign Look_Up_Table_1[760] = 16'sb0111010110100110;
  assign Look_Up_Table_1[761] = 16'sb0111010110111001;
  assign Look_Up_Table_1[762] = 16'sb0111010111001101;
  assign Look_Up_Table_1[763] = 16'sb0111010111100001;
  assign Look_Up_Table_1[764] = 16'sb0111010111110100;
  assign Look_Up_Table_1[765] = 16'sb0111011000001000;
  assign Look_Up_Table_1[766] = 16'sb0111011000011011;
  assign Look_Up_Table_1[767] = 16'sb0111011000101110;
  assign Look_Up_Table_1[768] = 16'sb0111011001000010;
  assign Look_Up_Table_1[769] = 16'sb0111011001010101;
  assign Look_Up_Table_1[770] = 16'sb0111011001101000;
  assign Look_Up_Table_1[771] = 16'sb0111011001111011;
  assign Look_Up_Table_1[772] = 16'sb0111011010001110;
  assign Look_Up_Table_1[773] = 16'sb0111011010100001;
  assign Look_Up_Table_1[774] = 16'sb0111011010110100;
  assign Look_Up_Table_1[775] = 16'sb0111011011000111;
  assign Look_Up_Table_1[776] = 16'sb0111011011011001;
  assign Look_Up_Table_1[777] = 16'sb0111011011101100;
  assign Look_Up_Table_1[778] = 16'sb0111011011111110;
  assign Look_Up_Table_1[779] = 16'sb0111011100010001;
  assign Look_Up_Table_1[780] = 16'sb0111011100100011;
  assign Look_Up_Table_1[781] = 16'sb0111011100110110;
  assign Look_Up_Table_1[782] = 16'sb0111011101001000;
  assign Look_Up_Table_1[783] = 16'sb0111011101011010;
  assign Look_Up_Table_1[784] = 16'sb0111011101101100;
  assign Look_Up_Table_1[785] = 16'sb0111011101111110;
  assign Look_Up_Table_1[786] = 16'sb0111011110010000;
  assign Look_Up_Table_1[787] = 16'sb0111011110100010;
  assign Look_Up_Table_1[788] = 16'sb0111011110110100;
  assign Look_Up_Table_1[789] = 16'sb0111011111000110;
  assign Look_Up_Table_1[790] = 16'sb0111011111011000;
  assign Look_Up_Table_1[791] = 16'sb0111011111101001;
  assign Look_Up_Table_1[792] = 16'sb0111011111111011;
  assign Look_Up_Table_1[793] = 16'sb0111100000001100;
  assign Look_Up_Table_1[794] = 16'sb0111100000011110;
  assign Look_Up_Table_1[795] = 16'sb0111100000101111;
  assign Look_Up_Table_1[796] = 16'sb0111100001000000;
  assign Look_Up_Table_1[797] = 16'sb0111100001010001;
  assign Look_Up_Table_1[798] = 16'sb0111100001100011;
  assign Look_Up_Table_1[799] = 16'sb0111100001110100;
  assign Look_Up_Table_1[800] = 16'sb0111100010000101;
  assign Look_Up_Table_1[801] = 16'sb0111100010010101;
  assign Look_Up_Table_1[802] = 16'sb0111100010100110;
  assign Look_Up_Table_1[803] = 16'sb0111100010110111;
  assign Look_Up_Table_1[804] = 16'sb0111100011001000;
  assign Look_Up_Table_1[805] = 16'sb0111100011011000;
  assign Look_Up_Table_1[806] = 16'sb0111100011101001;
  assign Look_Up_Table_1[807] = 16'sb0111100011111001;
  assign Look_Up_Table_1[808] = 16'sb0111100100001010;
  assign Look_Up_Table_1[809] = 16'sb0111100100011010;
  assign Look_Up_Table_1[810] = 16'sb0111100100101010;
  assign Look_Up_Table_1[811] = 16'sb0111100100111010;
  assign Look_Up_Table_1[812] = 16'sb0111100101001010;
  assign Look_Up_Table_1[813] = 16'sb0111100101011011;
  assign Look_Up_Table_1[814] = 16'sb0111100101101010;
  assign Look_Up_Table_1[815] = 16'sb0111100101111010;
  assign Look_Up_Table_1[816] = 16'sb0111100110001010;
  assign Look_Up_Table_1[817] = 16'sb0111100110011010;
  assign Look_Up_Table_1[818] = 16'sb0111100110101010;
  assign Look_Up_Table_1[819] = 16'sb0111100110111001;
  assign Look_Up_Table_1[820] = 16'sb0111100111001001;
  assign Look_Up_Table_1[821] = 16'sb0111100111011000;
  assign Look_Up_Table_1[822] = 16'sb0111100111100111;
  assign Look_Up_Table_1[823] = 16'sb0111100111110111;
  assign Look_Up_Table_1[824] = 16'sb0111101000000110;
  assign Look_Up_Table_1[825] = 16'sb0111101000010101;
  assign Look_Up_Table_1[826] = 16'sb0111101000100100;
  assign Look_Up_Table_1[827] = 16'sb0111101000110011;
  assign Look_Up_Table_1[828] = 16'sb0111101001000010;
  assign Look_Up_Table_1[829] = 16'sb0111101001010001;
  assign Look_Up_Table_1[830] = 16'sb0111101001100000;
  assign Look_Up_Table_1[831] = 16'sb0111101001101110;
  assign Look_Up_Table_1[832] = 16'sb0111101001111101;
  assign Look_Up_Table_1[833] = 16'sb0111101010001100;
  assign Look_Up_Table_1[834] = 16'sb0111101010011010;
  assign Look_Up_Table_1[835] = 16'sb0111101010101000;
  assign Look_Up_Table_1[836] = 16'sb0111101010110111;
  assign Look_Up_Table_1[837] = 16'sb0111101011000101;
  assign Look_Up_Table_1[838] = 16'sb0111101011010011;
  assign Look_Up_Table_1[839] = 16'sb0111101011100001;
  assign Look_Up_Table_1[840] = 16'sb0111101011101111;
  assign Look_Up_Table_1[841] = 16'sb0111101011111101;
  assign Look_Up_Table_1[842] = 16'sb0111101100001011;
  assign Look_Up_Table_1[843] = 16'sb0111101100011001;
  assign Look_Up_Table_1[844] = 16'sb0111101100100111;
  assign Look_Up_Table_1[845] = 16'sb0111101100110100;
  assign Look_Up_Table_1[846] = 16'sb0111101101000010;
  assign Look_Up_Table_1[847] = 16'sb0111101101010000;
  assign Look_Up_Table_1[848] = 16'sb0111101101011101;
  assign Look_Up_Table_1[849] = 16'sb0111101101101010;
  assign Look_Up_Table_1[850] = 16'sb0111101101111000;
  assign Look_Up_Table_1[851] = 16'sb0111101110000101;
  assign Look_Up_Table_1[852] = 16'sb0111101110010010;
  assign Look_Up_Table_1[853] = 16'sb0111101110011111;
  assign Look_Up_Table_1[854] = 16'sb0111101110101100;
  assign Look_Up_Table_1[855] = 16'sb0111101110111001;
  assign Look_Up_Table_1[856] = 16'sb0111101111000110;
  assign Look_Up_Table_1[857] = 16'sb0111101111010011;
  assign Look_Up_Table_1[858] = 16'sb0111101111011111;
  assign Look_Up_Table_1[859] = 16'sb0111101111101100;
  assign Look_Up_Table_1[860] = 16'sb0111101111111001;
  assign Look_Up_Table_1[861] = 16'sb0111110000000101;
  assign Look_Up_Table_1[862] = 16'sb0111110000010001;
  assign Look_Up_Table_1[863] = 16'sb0111110000011110;
  assign Look_Up_Table_1[864] = 16'sb0111110000101010;
  assign Look_Up_Table_1[865] = 16'sb0111110000110110;
  assign Look_Up_Table_1[866] = 16'sb0111110001000010;
  assign Look_Up_Table_1[867] = 16'sb0111110001001110;
  assign Look_Up_Table_1[868] = 16'sb0111110001011010;
  assign Look_Up_Table_1[869] = 16'sb0111110001100110;
  assign Look_Up_Table_1[870] = 16'sb0111110001110010;
  assign Look_Up_Table_1[871] = 16'sb0111110001111110;
  assign Look_Up_Table_1[872] = 16'sb0111110010001001;
  assign Look_Up_Table_1[873] = 16'sb0111110010010101;
  assign Look_Up_Table_1[874] = 16'sb0111110010100000;
  assign Look_Up_Table_1[875] = 16'sb0111110010101100;
  assign Look_Up_Table_1[876] = 16'sb0111110010110111;
  assign Look_Up_Table_1[877] = 16'sb0111110011000010;
  assign Look_Up_Table_1[878] = 16'sb0111110011001110;
  assign Look_Up_Table_1[879] = 16'sb0111110011011001;
  assign Look_Up_Table_1[880] = 16'sb0111110011100100;
  assign Look_Up_Table_1[881] = 16'sb0111110011101111;
  assign Look_Up_Table_1[882] = 16'sb0111110011111010;
  assign Look_Up_Table_1[883] = 16'sb0111110100000101;
  assign Look_Up_Table_1[884] = 16'sb0111110100001111;
  assign Look_Up_Table_1[885] = 16'sb0111110100011010;
  assign Look_Up_Table_1[886] = 16'sb0111110100100101;
  assign Look_Up_Table_1[887] = 16'sb0111110100101111;
  assign Look_Up_Table_1[888] = 16'sb0111110100111010;
  assign Look_Up_Table_1[889] = 16'sb0111110101000100;
  assign Look_Up_Table_1[890] = 16'sb0111110101001110;
  assign Look_Up_Table_1[891] = 16'sb0111110101011000;
  assign Look_Up_Table_1[892] = 16'sb0111110101100011;
  assign Look_Up_Table_1[893] = 16'sb0111110101101101;
  assign Look_Up_Table_1[894] = 16'sb0111110101110111;
  assign Look_Up_Table_1[895] = 16'sb0111110110000001;
  assign Look_Up_Table_1[896] = 16'sb0111110110001010;
  assign Look_Up_Table_1[897] = 16'sb0111110110010100;
  assign Look_Up_Table_1[898] = 16'sb0111110110011110;
  assign Look_Up_Table_1[899] = 16'sb0111110110100111;
  assign Look_Up_Table_1[900] = 16'sb0111110110110001;
  assign Look_Up_Table_1[901] = 16'sb0111110110111010;
  assign Look_Up_Table_1[902] = 16'sb0111110111000100;
  assign Look_Up_Table_1[903] = 16'sb0111110111001101;
  assign Look_Up_Table_1[904] = 16'sb0111110111010110;
  assign Look_Up_Table_1[905] = 16'sb0111110111100000;
  assign Look_Up_Table_1[906] = 16'sb0111110111101001;
  assign Look_Up_Table_1[907] = 16'sb0111110111110010;
  assign Look_Up_Table_1[908] = 16'sb0111110111111011;
  assign Look_Up_Table_1[909] = 16'sb0111111000000011;
  assign Look_Up_Table_1[910] = 16'sb0111111000001100;
  assign Look_Up_Table_1[911] = 16'sb0111111000010101;
  assign Look_Up_Table_1[912] = 16'sb0111111000011110;
  assign Look_Up_Table_1[913] = 16'sb0111111000100110;
  assign Look_Up_Table_1[914] = 16'sb0111111000101111;
  assign Look_Up_Table_1[915] = 16'sb0111111000110111;
  assign Look_Up_Table_1[916] = 16'sb0111111000111111;
  assign Look_Up_Table_1[917] = 16'sb0111111001001000;
  assign Look_Up_Table_1[918] = 16'sb0111111001010000;
  assign Look_Up_Table_1[919] = 16'sb0111111001011000;
  assign Look_Up_Table_1[920] = 16'sb0111111001100000;
  assign Look_Up_Table_1[921] = 16'sb0111111001101000;
  assign Look_Up_Table_1[922] = 16'sb0111111001110000;
  assign Look_Up_Table_1[923] = 16'sb0111111001111000;
  assign Look_Up_Table_1[924] = 16'sb0111111001111111;
  assign Look_Up_Table_1[925] = 16'sb0111111010000111;
  assign Look_Up_Table_1[926] = 16'sb0111111010001110;
  assign Look_Up_Table_1[927] = 16'sb0111111010010110;
  assign Look_Up_Table_1[928] = 16'sb0111111010011101;
  assign Look_Up_Table_1[929] = 16'sb0111111010100101;
  assign Look_Up_Table_1[930] = 16'sb0111111010101100;
  assign Look_Up_Table_1[931] = 16'sb0111111010110011;
  assign Look_Up_Table_1[932] = 16'sb0111111010111010;
  assign Look_Up_Table_1[933] = 16'sb0111111011000001;
  assign Look_Up_Table_1[934] = 16'sb0111111011001000;
  assign Look_Up_Table_1[935] = 16'sb0111111011001111;
  assign Look_Up_Table_1[936] = 16'sb0111111011010110;
  assign Look_Up_Table_1[937] = 16'sb0111111011011101;
  assign Look_Up_Table_1[938] = 16'sb0111111011100011;
  assign Look_Up_Table_1[939] = 16'sb0111111011101010;
  assign Look_Up_Table_1[940] = 16'sb0111111011110000;
  assign Look_Up_Table_1[941] = 16'sb0111111011110111;
  assign Look_Up_Table_1[942] = 16'sb0111111011111101;
  assign Look_Up_Table_1[943] = 16'sb0111111100000011;
  assign Look_Up_Table_1[944] = 16'sb0111111100001010;
  assign Look_Up_Table_1[945] = 16'sb0111111100010000;
  assign Look_Up_Table_1[946] = 16'sb0111111100010110;
  assign Look_Up_Table_1[947] = 16'sb0111111100011100;
  assign Look_Up_Table_1[948] = 16'sb0111111100100010;
  assign Look_Up_Table_1[949] = 16'sb0111111100100111;
  assign Look_Up_Table_1[950] = 16'sb0111111100101101;
  assign Look_Up_Table_1[951] = 16'sb0111111100110011;
  assign Look_Up_Table_1[952] = 16'sb0111111100111000;
  assign Look_Up_Table_1[953] = 16'sb0111111100111110;
  assign Look_Up_Table_1[954] = 16'sb0111111101000011;
  assign Look_Up_Table_1[955] = 16'sb0111111101001001;
  assign Look_Up_Table_1[956] = 16'sb0111111101001110;
  assign Look_Up_Table_1[957] = 16'sb0111111101010011;
  assign Look_Up_Table_1[958] = 16'sb0111111101011000;
  assign Look_Up_Table_1[959] = 16'sb0111111101011101;
  assign Look_Up_Table_1[960] = 16'sb0111111101100010;
  assign Look_Up_Table_1[961] = 16'sb0111111101100111;
  assign Look_Up_Table_1[962] = 16'sb0111111101101100;
  assign Look_Up_Table_1[963] = 16'sb0111111101110001;
  assign Look_Up_Table_1[964] = 16'sb0111111101110101;
  assign Look_Up_Table_1[965] = 16'sb0111111101111010;
  assign Look_Up_Table_1[966] = 16'sb0111111101111110;
  assign Look_Up_Table_1[967] = 16'sb0111111110000011;
  assign Look_Up_Table_1[968] = 16'sb0111111110000111;
  assign Look_Up_Table_1[969] = 16'sb0111111110001011;
  assign Look_Up_Table_1[970] = 16'sb0111111110010000;
  assign Look_Up_Table_1[971] = 16'sb0111111110010100;
  assign Look_Up_Table_1[972] = 16'sb0111111110011000;
  assign Look_Up_Table_1[973] = 16'sb0111111110011100;
  assign Look_Up_Table_1[974] = 16'sb0111111110100000;
  assign Look_Up_Table_1[975] = 16'sb0111111110100011;
  assign Look_Up_Table_1[976] = 16'sb0111111110100111;
  assign Look_Up_Table_1[977] = 16'sb0111111110101011;
  assign Look_Up_Table_1[978] = 16'sb0111111110101110;
  assign Look_Up_Table_1[979] = 16'sb0111111110110010;
  assign Look_Up_Table_1[980] = 16'sb0111111110110101;
  assign Look_Up_Table_1[981] = 16'sb0111111110111001;
  assign Look_Up_Table_1[982] = 16'sb0111111110111100;
  assign Look_Up_Table_1[983] = 16'sb0111111110111111;
  assign Look_Up_Table_1[984] = 16'sb0111111111000010;
  assign Look_Up_Table_1[985] = 16'sb0111111111000101;
  assign Look_Up_Table_1[986] = 16'sb0111111111001000;
  assign Look_Up_Table_1[987] = 16'sb0111111111001011;
  assign Look_Up_Table_1[988] = 16'sb0111111111001110;
  assign Look_Up_Table_1[989] = 16'sb0111111111010001;
  assign Look_Up_Table_1[990] = 16'sb0111111111010011;
  assign Look_Up_Table_1[991] = 16'sb0111111111010110;
  assign Look_Up_Table_1[992] = 16'sb0111111111011001;
  assign Look_Up_Table_1[993] = 16'sb0111111111011011;
  assign Look_Up_Table_1[994] = 16'sb0111111111011101;
  assign Look_Up_Table_1[995] = 16'sb0111111111100000;
  assign Look_Up_Table_1[996] = 16'sb0111111111100010;
  assign Look_Up_Table_1[997] = 16'sb0111111111100100;
  assign Look_Up_Table_1[998] = 16'sb0111111111100110;
  assign Look_Up_Table_1[999] = 16'sb0111111111101000;
  assign Look_Up_Table_1[1000] = 16'sb0111111111101010;
  assign Look_Up_Table_1[1001] = 16'sb0111111111101100;
  assign Look_Up_Table_1[1002] = 16'sb0111111111101101;
  assign Look_Up_Table_1[1003] = 16'sb0111111111101111;
  assign Look_Up_Table_1[1004] = 16'sb0111111111110001;
  assign Look_Up_Table_1[1005] = 16'sb0111111111110010;
  assign Look_Up_Table_1[1006] = 16'sb0111111111110100;
  assign Look_Up_Table_1[1007] = 16'sb0111111111110101;
  assign Look_Up_Table_1[1008] = 16'sb0111111111110110;
  assign Look_Up_Table_1[1009] = 16'sb0111111111110111;
  assign Look_Up_Table_1[1010] = 16'sb0111111111111000;
  assign Look_Up_Table_1[1011] = 16'sb0111111111111001;
  assign Look_Up_Table_1[1012] = 16'sb0111111111111010;
  assign Look_Up_Table_1[1013] = 16'sb0111111111111011;
  assign Look_Up_Table_1[1014] = 16'sb0111111111111100;
  assign Look_Up_Table_1[1015] = 16'sb0111111111111101;
  assign Look_Up_Table_1[1016] = 16'sb0111111111111110;
  assign Look_Up_Table_1[1017] = 16'sb0111111111111110;
  assign Look_Up_Table_1[1018] = 16'sb0111111111111111;
  assign Look_Up_Table_1[1019] = 16'sb0111111111111111;
  assign Look_Up_Table_1[1020] = 16'sb0111111111111111;
  assign Look_Up_Table_1[1021] = 16'sb0111111111111111;
  assign Look_Up_Table_1[1022] = 16'sb0111111111111111;
  assign Look_Up_Table_1[1023] = 16'sb0111111111111111;
  assign Look_Up_Table_k = (Switch_out1 == 12'b000000000000 ? 10'b0000000000 :
              (Switch_out1 >= 12'b001111111111 ? 10'b1111111111 :
              Switch_out1[9:0]));
  assign Look_Up_Table_out1 = Look_Up_Table_1[Look_Up_Table_k];



  assign Negate_cast = {Look_Up_Table_out1[15], Look_Up_Table_out1};
  assign Negate_cast_1 =  - (Negate_cast);
  assign Negate_out1 = Negate_cast_1[15:0];



  assign Cosine = (alpha1st_or_4th_Quad_out1 == 8'b00000000 ? Negate_out1 :
              Look_Up_Table_out1);



  assign Cosine_1 = Cosine;

  assign x = Cosine_1;

endmodule  // Sine_HDL_Optimized1

