// -------------------------------------------------------------
// 
// File Name: C:\Users\huber\Downloads\hdlsrc\HDLAWGNGenerator\HDLAWGNGenerator\SqrtEval.v
// Created: 2021-06-06 18:19:42
// 
// Generated by MATLAB 9.10 and HDL Coder 3.18
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: SqrtEval
// Source Path: HDLAWGNGenerator/AWGNGenerator/GaussianNoiseWithUnitVar/SqrtImplementation/SqrtEval
// Hierarchy Level: 3
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module SqrtEval
          (clk,
           reset,
           enb,
           u,
           f);


  input   clk;
  input   reset;
  input   enb;
  input   [30:0] u;  // ufix31_En24
  output  [16:0] f;  // ufix17_En13


  wire [30:0] RangeReduction_out1;  // ufix31_En24
  wire signed [8:0] RangeReduction_out2;  // sfix9
  wire signed [7:0] RangeReduction_out3;  // int8
  wire [16:0] FunctionEvaluation_out1;  // ufix17_En13
  wire signed [8:0] FunctionEvaluation_out2;  // sfix9
  wire signed [7:0] FunctionEvaluation_out3;  // int8
  wire [16:0] RangeReconstruction_out1;  // ufix17_En13


  RangeReduction u_RangeReduction (.clk(clk),
                                   .reset(reset),
                                   .enb(enb),
                                   .u(u),  // ufix31_En24
                                   .x_f(RangeReduction_out1),  // ufix31_En24
                                   .pass(RangeReduction_out2),  // sfix9
                                   .exp_f(RangeReduction_out3)  // int8
                                   );

  FunctionEvaluation u_FunctionEvaluation (.clk(clk),
                                           .reset(reset),
                                           .enb(enb),
                                           .x_f(RangeReduction_out1),  // ufix31_En24
                                           .passIn(RangeReduction_out2),  // sfix9
                                           .exp_fIn(RangeReduction_out3),  // int8
                                           .y_f(FunctionEvaluation_out1),  // ufix17_En13
                                           .passOut(FunctionEvaluation_out2),  // sfix9
                                           .exp_fOut(FunctionEvaluation_out3)  // int8
                                           );

  RangeReconstruction u_RangeReconstruction (.y_f(FunctionEvaluation_out1),  // ufix17_En13
                                             .pass(FunctionEvaluation_out2),  // sfix9
                                             .exp_f(FunctionEvaluation_out3),  // int8
                                             .f(RangeReconstruction_out1)  // ufix17_En13
                                             );

  assign f = RangeReconstruction_out1;

endmodule  // SqrtEval

