// -------------------------------------------------------------
// 
// File Name: C:\Users\huber\Downloads\hdlsrc\HDLAWGNGenerator\HDLAWGNGenerator\TausUniformRandGen.v
// Created: 2021-06-06 18:19:42
// 
// Generated by MATLAB 9.10 and HDL Coder 3.18
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: TausUniformRandGen
// Source Path: HDLAWGNGenerator/AWGNGenerator/GaussianNoiseWithUnitVar/TausUniformRandGen
// Hierarchy Level: 2
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module TausUniformRandGen
          (clk,
           reset,
           enb,
           u0_16_16,
           u1_16_16);


  input   clk;
  input   reset;
  input   enb;
  output  [47:0] u0_16_16;  // ufix48_En48
  output  [15:0] u1_16_16;  // ufix16_En16


  wire [31:0] a_32_0;  // uint32
  wire [31:0] b_32_0;  // uint32
  wire [47:0] u0_48_48;  // ufix48_En48


  TausURNG1 u_TausURNG1 (.clk(clk),
                         .reset(reset),
                         .enb(enb),
                         .a(a_32_0)  // uint32
                         );

  TausURNG2 u_TausURNG2 (.clk(clk),
                         .reset(reset),
                         .enb(enb),
                         .b(b_32_0)  // uint32
                         );

  ConcatandExtract u_ConcatandExtract (.a(a_32_0),  // uint32
                                       .b(b_32_0),  // uint32
                                       .u0_48_48(u0_48_48),  // ufix48_En48
                                       .u1_16_16(u1_16_16)  // ufix16_En16
                                       );

  assign u0_16_16 = u0_48_48;

endmodule  // TausUniformRandGen

