// RSencoder_highspeed_rs_0.v

// This file was auto-generated from altera_highspeed_rs_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 16.1 196

`timescale 1 ps / 1 ps
module RSencoder_highspeed_rs_0 #(
		parameter CHANNEL        = 1,
		parameter BITSPERSYMBOL  = 8,
		parameter N              = 255,
		parameter IRRPOL         = 285,
		parameter PAR            = 10,
		parameter BMSPEED        = 4,
		parameter USERAM         = 1,
		parameter USETRUEDUALRAM = 1,
		parameter USEECCFORRAM   = 0,
		parameter USE_BKP        = 0,
		parameter USE_BYPASS     = 0
	) (
		input  wire        clk_clk,           //   clk.clk
		input  wire        reset_reset_n,     // reset.reset_n
		input  wire        in_startofpacket,  //    in.startofpacket
		input  wire        in_endofpacket,    //      .endofpacket
		input  wire        in_valid,          //      .valid
		output wire        in_ready,          //      .ready
		input  wire [79:0] in_data,           //      .data
		output wire        out_startofpacket, //   out.startofpacket
		output wire        out_endofpacket,   //      .endofpacket
		output wire        out_valid,         //      .valid
		output wire [79:0] out_data           //      .data
	);

	generate
		// If any of the display statements (or deliberately broken
		// instantiations) within this generate block triggers then this module
		// has been instantiated this module with a set of parameters different
		// from those it was generated for.  This will usually result in a
		// non-functioning system.
		if (CHANNEL != 1)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					channel_check ( .error(1'b1) );
		end
		if (BITSPERSYMBOL != 8)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					bitspersymbol_check ( .error(1'b1) );
		end
		if (N != 255)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					n_check ( .error(1'b1) );
		end
		if (IRRPOL != 285)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					irrpol_check ( .error(1'b1) );
		end
		if (PAR != 10)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					par_check ( .error(1'b1) );
		end
		if (BMSPEED != 4)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					bmspeed_check ( .error(1'b1) );
		end
		if (USERAM != 1)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					useram_check ( .error(1'b1) );
		end
		if (USETRUEDUALRAM != 1)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					usetruedualram_check ( .error(1'b1) );
		end
		if (USEECCFORRAM != 0)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					useeccforram_check ( .error(1'b1) );
		end
		if (USE_BKP != 0)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					use_bkp_check ( .error(1'b1) );
		end
		if (USE_BYPASS != 0)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					use_bypass_check ( .error(1'b1) );
		end
	endgenerate

	altera_highspeed_rs_enc #(
		.BITSPERSYMBOL (8),
		.N             (255),
		.CHECK         (32),
		.IRRPOL        (285),
		.PAR           (10),
		.USE_BKP       (0)
	) encoder (
		.clk               (clk_clk),           // clk.clk
		.rst               (~reset_reset_n),    // rst.reset
		.in_startofpacket  (in_startofpacket),  //  in.startofpacket
		.in_endofpacket    (in_endofpacket),    //    .endofpacket
		.in_valid          (in_valid),          //    .valid
		.in_ready          (in_ready),          //    .ready
		.in_data           (in_data),           //    .data
		.out_startofpacket (out_startofpacket), // out.startofpacket
		.out_endofpacket   (out_endofpacket),   //    .endofpacket
		.out_valid         (out_valid),         //    .valid
		.out_data          (out_data),          //    .data
		.out_ready         (1'b1)               // (terminated)
	);

endmodule
