// -------------------------------------------------------------
// 
// File Name: C:\UBC Summer 2021\gitproject\ELEC391_Final_Project\mike\V_Normal_RC\Filter_for_16PSK\hdlcoder\receiver2\gm_gm_Modulation_test\Raised_Cosine_Receive_Filter.v
// Created: 2021-06-16 00:04:21
// 
// Generated by MATLAB 9.10 and HDL Coder 3.18
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 0.125
// Target subsystem base rate: 0.125
// 
// 
// Clock Enable  Sample Time
// -- -------------------------------------------------------------
// ce_out        1
// -- -------------------------------------------------------------
// 
// 
// Output Signal                 Clock Enable  Sample Time
// -- -------------------------------------------------------------
// Out1                          ce_out        1
// -- -------------------------------------------------------------
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Raised_Cosine_Receive_Filter
// Source Path: gm_gm_Modulation_test/Subsystem/Raised Cosine Receive Filter
// Hierarchy Level: 0
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Raised_Cosine_Receive_Filter
          (clk,
           reset,
           clk_enable,
           In1,
           ce_out,
           Out1);


  input   clk;
  input   reset;
  input   clk_enable;
  input   signed [31:0] In1;  // int32
  output  ce_out;
  output  signed [31:0] Out1;  // int32


  wire enb_1_1_1;
  wire enb_1_8_1;
  wire signed [31:0] FIR_Decimation_out1;  // int32


  Raised_Cosine_Receive_Filter_tc u_Raised_Cosine_Receive_Filter_tc (.clk(clk),
                                                                     .reset(reset),
                                                                     .clk_enable(clk_enable),
                                                                     .enb_1_1_1(enb_1_1_1),
                                                                     .enb_1_8_1(enb_1_8_1)
                                                                     );

  FIR_Decimation u_FIR_Decimation (.clk(clk),
                                   .enb_1_1_1(enb_1_1_1),
                                   .reset(reset),
                                   .FIR_Decimation_in(In1),  // int32
                                   .FIR_Decimation_out(FIR_Decimation_out1)  // int32
                                   );

  assign Out1 = FIR_Decimation_out1;

  assign ce_out = enb_1_8_1;

endmodule  // Raised_Cosine_Receive_Filter

