// ------------------------------------------------------------
// 
// File Name: C:\UBC Summer 2021\gitproject\ELEC391_Final_Project\mike\V_Normal_RC\Filter_for_16PSK\hdlcoder\transmitter3\gm_gm_Modulation_test\FIR_Interpolation
// Created: 2021-06-16 10:43:19
// Generated by MATLAB 9.10 and HDL Coder 3.18
// 
// ------------------------------------------------------------
// 
// 
// ------------------------------------------------------------
// 
// Module: FIR_Interpolation
// Source Path: /FIR_Interpolation
// 
// ------------------------------------------------------------
// 
// HDL Implementation    : Fully parallel
// Folding Factor        : 1
// Multipliers           : 11



`timescale 1 ns / 1 ns

module FIR_Interpolation
               (
                clk,
                enb_1_1_1,
                reset,
                FIR_Interpolation_in,
                FIR_Interpolation_out
                );

  input   clk; 
  input   enb_1_1_1; 
  input   reset; 
  input   signed [15:0] FIR_Interpolation_in; //sfix16
  output  signed [15:0] FIR_Interpolation_out; //sfix16

////////////////////////////////////////////////////////////////
//Module Architecture: FIR_Interpolation
////////////////////////////////////////////////////////////////
  // Local Functions
  // Type Definitions
  // Constants
  parameter signed [15:0] coeffphase1_1 = 16'b1111111001110111; //sfix16_En16
  parameter signed [15:0] coeffphase1_2 = 16'b0000001001111010; //sfix16_En16
  parameter signed [15:0] coeffphase1_3 = 16'b1111110010010110; //sfix16_En16
  parameter signed [15:0] coeffphase1_4 = 16'b0000010000111000; //sfix16_En16
  parameter signed [15:0] coeffphase1_5 = 16'b1111101100111110; //sfix16_En16
  parameter signed [15:0] coeffphase1_6 = 16'b0101111101111001; //sfix16_En16
  parameter signed [15:0] coeffphase1_7 = 16'b1111101100111110; //sfix16_En16
  parameter signed [15:0] coeffphase1_8 = 16'b0000010000111000; //sfix16_En16
  parameter signed [15:0] coeffphase1_9 = 16'b1111110010010110; //sfix16_En16
  parameter signed [15:0] coeffphase1_10 = 16'b0000001001111010; //sfix16_En16
  parameter signed [15:0] coeffphase1_11 = 16'b1111111001110111; //sfix16_En16
  parameter signed [15:0] coeffphase2_1 = 16'b1111111010101111; //sfix16_En16
  parameter signed [15:0] coeffphase2_2 = 16'b0000000101111011; //sfix16_En16
  parameter signed [15:0] coeffphase2_3 = 16'b1111111011110011; //sfix16_En16
  parameter signed [15:0] coeffphase2_4 = 16'b1111111101000001; //sfix16_En16
  parameter signed [15:0] coeffphase2_5 = 16'b0000011110011001; //sfix16_En16
  parameter signed [15:0] coeffphase2_6 = 16'b0101110010110100; //sfix16_En16
  parameter signed [15:0] coeffphase2_7 = 16'b1111001010010100; //sfix16_En16
  parameter signed [15:0] coeffphase2_8 = 16'b0000011110110110; //sfix16_En16
  parameter signed [15:0] coeffphase2_9 = 16'b1111101100100100; //sfix16_En16
  parameter signed [15:0] coeffphase2_10 = 16'b0000001011100000; //sfix16_En16
  parameter signed [15:0] coeffphase2_11 = 16'b0000000000000000; //sfix16_En16
  parameter signed [15:0] coeffphase3_1 = 16'b1111111101000010; //sfix16_En16
  parameter signed [15:0] coeffphase3_2 = 16'b0000000000000000; //sfix16_En16
  parameter signed [15:0] coeffphase3_3 = 16'b0000000111101101; //sfix16_En16
  parameter signed [15:0] coeffphase3_4 = 16'b1111100101111010; //sfix16_En16
  parameter signed [15:0] coeffphase3_5 = 16'b0001011011010110; //sfix16_En16
  parameter signed [15:0] coeffphase3_6 = 16'b0101010010110000; //sfix16_En16
  parameter signed [15:0] coeffphase3_7 = 16'b1110110111100101; //sfix16_En16
  parameter signed [15:0] coeffphase3_8 = 16'b0000100101101001; //sfix16_En16
  parameter signed [15:0] coeffphase3_9 = 16'b1111101010111011; //sfix16_En16
  parameter signed [15:0] coeffphase3_10 = 16'b0000001010110000; //sfix16_En16
  parameter signed [15:0] coeffphase3_11 = 16'b0000000000000000; //sfix16_En16
  parameter signed [15:0] coeffphase4_1 = 16'b0000000000011101; //sfix16_En16
  parameter signed [15:0] coeffphase4_2 = 16'b1111111001000010; //sfix16_En16
  parameter signed [15:0] coeffphase4_3 = 16'b0000010100000111; //sfix16_En16
  parameter signed [15:0] coeffphase4_4 = 16'b1111001111001011; //sfix16_En16
  parameter signed [15:0] coeffphase4_5 = 16'b0010011110111101; //sfix16_En16
  parameter signed [15:0] coeffphase4_6 = 16'b0100100001000111; //sfix16_En16
  parameter signed [15:0] coeffphase4_7 = 16'b1110110100000000; //sfix16_En16
  parameter signed [15:0] coeffphase4_8 = 16'b0000100101001110; //sfix16_En16
  parameter signed [15:0] coeffphase4_9 = 16'b1111101101001000; //sfix16_En16
  parameter signed [15:0] coeffphase4_10 = 16'b0000001000001001; //sfix16_En16
  parameter signed [15:0] coeffphase4_11 = 16'b0000000000000000; //sfix16_En16
  parameter signed [15:0] coeffphase5_1 = 16'b0000000100011011; //sfix16_En16
  parameter signed [15:0] coeffphase5_2 = 16'b1111110010010001; //sfix16_En16
  parameter signed [15:0] coeffphase5_3 = 16'b0000011110101111; //sfix16_En16
  parameter signed [15:0] coeffphase5_4 = 16'b1110111101000111; //sfix16_En16
  parameter signed [15:0] coeffphase5_5 = 16'b0011100011000101; //sfix16_En16
  parameter signed [15:0] coeffphase5_6 = 16'b0011100011000101; //sfix16_En16
  parameter signed [15:0] coeffphase5_7 = 16'b1110111101000111; //sfix16_En16
  parameter signed [15:0] coeffphase5_8 = 16'b0000011110101111; //sfix16_En16
  parameter signed [15:0] coeffphase5_9 = 16'b1111110010010001; //sfix16_En16
  parameter signed [15:0] coeffphase5_10 = 16'b0000000100011011; //sfix16_En16
  parameter signed [15:0] coeffphase5_11 = 16'b0000000000000000; //sfix16_En16
  parameter signed [15:0] coeffphase6_1 = 16'b0000001000001001; //sfix16_En16
  parameter signed [15:0] coeffphase6_2 = 16'b1111101101001000; //sfix16_En16
  parameter signed [15:0] coeffphase6_3 = 16'b0000100101001110; //sfix16_En16
  parameter signed [15:0] coeffphase6_4 = 16'b1110110100000000; //sfix16_En16
  parameter signed [15:0] coeffphase6_5 = 16'b0100100001000111; //sfix16_En16
  parameter signed [15:0] coeffphase6_6 = 16'b0010011110111101; //sfix16_En16
  parameter signed [15:0] coeffphase6_7 = 16'b1111001111001011; //sfix16_En16
  parameter signed [15:0] coeffphase6_8 = 16'b0000010100000111; //sfix16_En16
  parameter signed [15:0] coeffphase6_9 = 16'b1111111001000010; //sfix16_En16
  parameter signed [15:0] coeffphase6_10 = 16'b0000000000011101; //sfix16_En16
  parameter signed [15:0] coeffphase6_11 = 16'b0000000000000000; //sfix16_En16
  parameter signed [15:0] coeffphase7_1 = 16'b0000001010110000; //sfix16_En16
  parameter signed [15:0] coeffphase7_2 = 16'b1111101010111011; //sfix16_En16
  parameter signed [15:0] coeffphase7_3 = 16'b0000100101101001; //sfix16_En16
  parameter signed [15:0] coeffphase7_4 = 16'b1110110111100101; //sfix16_En16
  parameter signed [15:0] coeffphase7_5 = 16'b0101010010110000; //sfix16_En16
  parameter signed [15:0] coeffphase7_6 = 16'b0001011011010110; //sfix16_En16
  parameter signed [15:0] coeffphase7_7 = 16'b1111100101111010; //sfix16_En16
  parameter signed [15:0] coeffphase7_8 = 16'b0000000111101101; //sfix16_En16
  parameter signed [15:0] coeffphase7_9 = 16'b0000000000000000; //sfix16_En16
  parameter signed [15:0] coeffphase7_10 = 16'b1111111101000010; //sfix16_En16
  parameter signed [15:0] coeffphase7_11 = 16'b0000000000000000; //sfix16_En16
  parameter signed [15:0] coeffphase8_1 = 16'b0000001011100000; //sfix16_En16
  parameter signed [15:0] coeffphase8_2 = 16'b1111101100100100; //sfix16_En16
  parameter signed [15:0] coeffphase8_3 = 16'b0000011110110110; //sfix16_En16
  parameter signed [15:0] coeffphase8_4 = 16'b1111001010010100; //sfix16_En16
  parameter signed [15:0] coeffphase8_5 = 16'b0101110010110100; //sfix16_En16
  parameter signed [15:0] coeffphase8_6 = 16'b0000011110011001; //sfix16_En16
  parameter signed [15:0] coeffphase8_7 = 16'b1111111101000001; //sfix16_En16
  parameter signed [15:0] coeffphase8_8 = 16'b1111111011110011; //sfix16_En16
  parameter signed [15:0] coeffphase8_9 = 16'b0000000101111011; //sfix16_En16
  parameter signed [15:0] coeffphase8_10 = 16'b1111111010101111; //sfix16_En16
  parameter signed [15:0] coeffphase8_11 = 16'b0000000000000000; //sfix16_En16

  // Signals
  reg  [2:0] cur_count; // ufix3
  wire phase_7; // boolean
  reg  signed [15:0] delay_pipeline [0:9] ; // sfix16
  wire signed [15:0] product; // sfix16
  wire signed [15:0] product_mux; // sfix16_En16
  wire signed [31:0] mul_temp; // sfix32_En16
  wire signed [15:0] product_1; // sfix16
  wire signed [15:0] product_mux_1; // sfix16_En16
  wire signed [31:0] mul_temp_1; // sfix32_En16
  wire signed [15:0] product_2; // sfix16
  wire signed [15:0] product_mux_2; // sfix16_En16
  wire signed [31:0] mul_temp_2; // sfix32_En16
  wire signed [15:0] product_3; // sfix16
  wire signed [15:0] product_mux_3; // sfix16_En16
  wire signed [31:0] mul_temp_3; // sfix32_En16
  wire signed [15:0] product_4; // sfix16
  wire signed [15:0] product_mux_4; // sfix16_En16
  wire signed [31:0] mul_temp_4; // sfix32_En16
  wire signed [15:0] product_5; // sfix16
  wire signed [15:0] product_mux_5; // sfix16_En16
  wire signed [31:0] mul_temp_5; // sfix32_En16
  wire signed [15:0] product_6; // sfix16
  wire signed [15:0] product_mux_6; // sfix16_En16
  wire signed [31:0] mul_temp_6; // sfix32_En16
  wire signed [15:0] product_7; // sfix16
  wire signed [15:0] product_mux_7; // sfix16_En16
  wire signed [31:0] mul_temp_7; // sfix32_En16
  wire signed [15:0] product_8; // sfix16
  wire signed [15:0] product_mux_8; // sfix16_En16
  wire signed [31:0] mul_temp_8; // sfix32_En16
  wire signed [15:0] product_9; // sfix16
  wire signed [15:0] product_mux_9; // sfix16_En16
  wire signed [31:0] mul_temp_9; // sfix32_En16
  wire signed [15:0] product_10; // sfix16
  wire signed [15:0] product_mux_10; // sfix16_En16
  wire signed [31:0] mul_temp_10; // sfix32_En16
  wire signed [15:0] sum1; // sfix16
  wire signed [15:0] add_cast; // sfix16
  wire signed [15:0] add_cast_1; // sfix16
  wire signed [16:0] add_temp; // sfix17
  wire signed [15:0] sum2; // sfix16
  wire signed [15:0] add_cast_2; // sfix16
  wire signed [15:0] add_cast_3; // sfix16
  wire signed [16:0] add_temp_1; // sfix17
  wire signed [15:0] sum3; // sfix16
  wire signed [15:0] add_cast_4; // sfix16
  wire signed [15:0] add_cast_5; // sfix16
  wire signed [16:0] add_temp_2; // sfix17
  wire signed [15:0] sum4; // sfix16
  wire signed [15:0] add_cast_6; // sfix16
  wire signed [15:0] add_cast_7; // sfix16
  wire signed [16:0] add_temp_3; // sfix17
  wire signed [15:0] sum5; // sfix16
  wire signed [15:0] add_cast_8; // sfix16
  wire signed [15:0] add_cast_9; // sfix16
  wire signed [16:0] add_temp_4; // sfix17
  wire signed [15:0] sum6; // sfix16
  wire signed [15:0] add_cast_10; // sfix16
  wire signed [15:0] add_cast_11; // sfix16
  wire signed [16:0] add_temp_5; // sfix17
  wire signed [15:0] sum7; // sfix16
  wire signed [15:0] add_cast_12; // sfix16
  wire signed [15:0] add_cast_13; // sfix16
  wire signed [16:0] add_temp_6; // sfix17
  wire signed [15:0] sum8; // sfix16
  wire signed [15:0] add_cast_14; // sfix16
  wire signed [15:0] add_cast_15; // sfix16
  wire signed [16:0] add_temp_7; // sfix17
  wire signed [15:0] sum9; // sfix16
  wire signed [15:0] add_cast_16; // sfix16
  wire signed [15:0] add_cast_17; // sfix16
  wire signed [16:0] add_temp_8; // sfix17
  wire signed [15:0] sum10; // sfix16
  wire signed [15:0] add_cast_18; // sfix16
  wire signed [15:0] add_cast_19; // sfix16
  wire signed [16:0] add_temp_9; // sfix17
  reg  signed [15:0] regout; // sfix16
  wire signed [15:0] muxout; // sfix16

  // Block Statements
  always @ (posedge clk or posedge reset)
    begin: ce_output
      if (reset == 1'b1) begin
        cur_count <= 3'b000;
      end
      else begin
        if (enb_1_1_1 == 1'b1) begin
          if (cur_count >= 3'b111) begin
            cur_count <= 3'b000;
          end
          else begin
            cur_count <= cur_count + 3'b001;
          end
        end
      end
    end // ce_output

  assign  phase_7 = (cur_count == 3'b111 && enb_1_1_1 == 1'b1) ? 1'b1 : 1'b0;

  //   ---------------- Delay Registers ----------------

  always @( posedge clk or posedge reset)
    begin: Delay_Pipeline_process
      if (reset == 1'b1) begin
        delay_pipeline[0] <= 0;
        delay_pipeline[1] <= 0;
        delay_pipeline[2] <= 0;
        delay_pipeline[3] <= 0;
        delay_pipeline[4] <= 0;
        delay_pipeline[5] <= 0;
        delay_pipeline[6] <= 0;
        delay_pipeline[7] <= 0;
        delay_pipeline[8] <= 0;
        delay_pipeline[9] <= 0;
      end
      else begin
        if (phase_7 == 1'b1) begin
          delay_pipeline[0] <= FIR_Interpolation_in;
          delay_pipeline[1] <= delay_pipeline[0];
          delay_pipeline[2] <= delay_pipeline[1];
          delay_pipeline[3] <= delay_pipeline[2];
          delay_pipeline[4] <= delay_pipeline[3];
          delay_pipeline[5] <= delay_pipeline[4];
          delay_pipeline[6] <= delay_pipeline[5];
          delay_pipeline[7] <= delay_pipeline[6];
          delay_pipeline[8] <= delay_pipeline[7];
          delay_pipeline[9] <= delay_pipeline[8];
        end
      end
    end // Delay_Pipeline_process


  assign product_mux = (cur_count == 3'b000) ? coeffphase1_11 :
                      (cur_count == 3'b001) ? coeffphase2_11 :
                      (cur_count == 3'b010) ? coeffphase3_11 :
                      (cur_count == 3'b011) ? coeffphase4_11 :
                      (cur_count == 3'b100) ? coeffphase5_11 :
                      (cur_count == 3'b101) ? coeffphase6_11 :
                      (cur_count == 3'b110) ? coeffphase7_11 :
                      coeffphase8_11;
  assign mul_temp = delay_pipeline[9] * product_mux;
  assign product = mul_temp[31:16];

  assign product_mux_1 = (cur_count == 3'b000) ? coeffphase1_10 :
                        (cur_count == 3'b001) ? coeffphase2_10 :
                        (cur_count == 3'b010) ? coeffphase3_10 :
                        (cur_count == 3'b011) ? coeffphase4_10 :
                        (cur_count == 3'b100) ? coeffphase5_10 :
                        (cur_count == 3'b101) ? coeffphase6_10 :
                        (cur_count == 3'b110) ? coeffphase7_10 :
                        coeffphase8_10;
  assign mul_temp_1 = delay_pipeline[8] * product_mux_1;
  assign product_1 = mul_temp_1[31:16];

  assign product_mux_2 = (cur_count == 3'b000) ? coeffphase1_9 :
                        (cur_count == 3'b001) ? coeffphase2_9 :
                        (cur_count == 3'b010) ? coeffphase3_9 :
                        (cur_count == 3'b011) ? coeffphase4_9 :
                        (cur_count == 3'b100) ? coeffphase5_9 :
                        (cur_count == 3'b101) ? coeffphase6_9 :
                        (cur_count == 3'b110) ? coeffphase7_9 :
                        coeffphase8_9;
  assign mul_temp_2 = delay_pipeline[7] * product_mux_2;
  assign product_2 = mul_temp_2[31:16];

  assign product_mux_3 = (cur_count == 3'b000) ? coeffphase1_8 :
                        (cur_count == 3'b001) ? coeffphase2_8 :
                        (cur_count == 3'b010) ? coeffphase3_8 :
                        (cur_count == 3'b011) ? coeffphase4_8 :
                        (cur_count == 3'b100) ? coeffphase5_8 :
                        (cur_count == 3'b101) ? coeffphase6_8 :
                        (cur_count == 3'b110) ? coeffphase7_8 :
                        coeffphase8_8;
  assign mul_temp_3 = delay_pipeline[6] * product_mux_3;
  assign product_3 = mul_temp_3[31:16];

  assign product_mux_4 = (cur_count == 3'b000) ? coeffphase1_7 :
                        (cur_count == 3'b001) ? coeffphase2_7 :
                        (cur_count == 3'b010) ? coeffphase3_7 :
                        (cur_count == 3'b011) ? coeffphase4_7 :
                        (cur_count == 3'b100) ? coeffphase5_7 :
                        (cur_count == 3'b101) ? coeffphase6_7 :
                        (cur_count == 3'b110) ? coeffphase7_7 :
                        coeffphase8_7;
  assign mul_temp_4 = delay_pipeline[5] * product_mux_4;
  assign product_4 = mul_temp_4[31:16];

  assign product_mux_5 = (cur_count == 3'b000) ? coeffphase1_6 :
                        (cur_count == 3'b001) ? coeffphase2_6 :
                        (cur_count == 3'b010) ? coeffphase3_6 :
                        (cur_count == 3'b011) ? coeffphase4_6 :
                        (cur_count == 3'b100) ? coeffphase5_6 :
                        (cur_count == 3'b101) ? coeffphase6_6 :
                        (cur_count == 3'b110) ? coeffphase7_6 :
                        coeffphase8_6;
  assign mul_temp_5 = delay_pipeline[4] * product_mux_5;
  assign product_5 = mul_temp_5[31:16];

  assign product_mux_6 = (cur_count == 3'b000) ? coeffphase1_5 :
                        (cur_count == 3'b001) ? coeffphase2_5 :
                        (cur_count == 3'b010) ? coeffphase3_5 :
                        (cur_count == 3'b011) ? coeffphase4_5 :
                        (cur_count == 3'b100) ? coeffphase5_5 :
                        (cur_count == 3'b101) ? coeffphase6_5 :
                        (cur_count == 3'b110) ? coeffphase7_5 :
                        coeffphase8_5;
  assign mul_temp_6 = delay_pipeline[3] * product_mux_6;
  assign product_6 = mul_temp_6[31:16];

  assign product_mux_7 = (cur_count == 3'b000) ? coeffphase1_4 :
                        (cur_count == 3'b001) ? coeffphase2_4 :
                        (cur_count == 3'b010) ? coeffphase3_4 :
                        (cur_count == 3'b011) ? coeffphase4_4 :
                        (cur_count == 3'b100) ? coeffphase5_4 :
                        (cur_count == 3'b101) ? coeffphase6_4 :
                        (cur_count == 3'b110) ? coeffphase7_4 :
                        coeffphase8_4;
  assign mul_temp_7 = delay_pipeline[2] * product_mux_7;
  assign product_7 = mul_temp_7[31:16];

  assign product_mux_8 = (cur_count == 3'b000) ? coeffphase1_3 :
                        (cur_count == 3'b001) ? coeffphase2_3 :
                        (cur_count == 3'b010) ? coeffphase3_3 :
                        (cur_count == 3'b011) ? coeffphase4_3 :
                        (cur_count == 3'b100) ? coeffphase5_3 :
                        (cur_count == 3'b101) ? coeffphase6_3 :
                        (cur_count == 3'b110) ? coeffphase7_3 :
                        coeffphase8_3;
  assign mul_temp_8 = delay_pipeline[1] * product_mux_8;
  assign product_8 = mul_temp_8[31:16];

  assign product_mux_9 = (cur_count == 3'b000) ? coeffphase1_2 :
                        (cur_count == 3'b001) ? coeffphase2_2 :
                        (cur_count == 3'b010) ? coeffphase3_2 :
                        (cur_count == 3'b011) ? coeffphase4_2 :
                        (cur_count == 3'b100) ? coeffphase5_2 :
                        (cur_count == 3'b101) ? coeffphase6_2 :
                        (cur_count == 3'b110) ? coeffphase7_2 :
                        coeffphase8_2;
  assign mul_temp_9 = delay_pipeline[0] * product_mux_9;
  assign product_9 = mul_temp_9[31:16];

  assign product_mux_10 = (cur_count == 3'b000) ? coeffphase1_1 :
                         (cur_count == 3'b001) ? coeffphase2_1 :
                         (cur_count == 3'b010) ? coeffphase3_1 :
                         (cur_count == 3'b011) ? coeffphase4_1 :
                         (cur_count == 3'b100) ? coeffphase5_1 :
                         (cur_count == 3'b101) ? coeffphase6_1 :
                         (cur_count == 3'b110) ? coeffphase7_1 :
                         coeffphase8_1;
  assign mul_temp_10 = FIR_Interpolation_in * product_mux_10;
  assign product_10 = mul_temp_10[31:16];

  assign add_cast = product_10;
  assign add_cast_1 = product_9;
  assign add_temp = add_cast + add_cast_1;
  assign sum1 = add_temp[15:0];

  assign add_cast_2 = sum1;
  assign add_cast_3 = product_8;
  assign add_temp_1 = add_cast_2 + add_cast_3;
  assign sum2 = add_temp_1[15:0];

  assign add_cast_4 = sum2;
  assign add_cast_5 = product_7;
  assign add_temp_2 = add_cast_4 + add_cast_5;
  assign sum3 = add_temp_2[15:0];

  assign add_cast_6 = sum3;
  assign add_cast_7 = product_6;
  assign add_temp_3 = add_cast_6 + add_cast_7;
  assign sum4 = add_temp_3[15:0];

  assign add_cast_8 = sum4;
  assign add_cast_9 = product_5;
  assign add_temp_4 = add_cast_8 + add_cast_9;
  assign sum5 = add_temp_4[15:0];

  assign add_cast_10 = sum5;
  assign add_cast_11 = product_4;
  assign add_temp_5 = add_cast_10 + add_cast_11;
  assign sum6 = add_temp_5[15:0];

  assign add_cast_12 = sum6;
  assign add_cast_13 = product_3;
  assign add_temp_6 = add_cast_12 + add_cast_13;
  assign sum7 = add_temp_6[15:0];

  assign add_cast_14 = sum7;
  assign add_cast_15 = product_2;
  assign add_temp_7 = add_cast_14 + add_cast_15;
  assign sum8 = add_temp_7[15:0];

  assign add_cast_16 = sum8;
  assign add_cast_17 = product_1;
  assign add_temp_8 = add_cast_16 + add_cast_17;
  assign sum9 = add_temp_8[15:0];

  assign add_cast_18 = sum9;
  assign add_cast_19 = product;
  assign add_temp_9 = add_cast_18 + add_cast_19;
  assign sum10 = add_temp_9[15:0];

  always @ (posedge clk or posedge reset)
    begin: DataHoldRegister_process
      if (reset == 1'b1) begin
        regout <= 0;
      end
      else begin
        if (enb_1_1_1 == 1'b1) begin
          regout <= sum10;
        end
      end
    end // DataHoldRegister_process

  assign muxout = (enb_1_1_1 == 1'b1) ? sum10 :
            regout;
  // Assignment Statements
  assign FIR_Interpolation_out = muxout;
endmodule  // FIR_Interpolation
