// -------------------------------------------------------------
// 
// File Name: C:\UBC Summer 2021\gitproject\ELEC391_Final_Project\mike\V_Normal_RC\Filter_for_16PSK\hdlcoder\t4\gm_gm_Modulation_test\Raised_Cosine_Transmit_Filter.v
// Created: 2021-06-16 12:13:09
// 
// Generated by MATLAB 9.10 and HDL Coder 3.18
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 0.125
// Target subsystem base rate: 0.125
// 
// 
// Clock Enable  Sample Time
// -- -------------------------------------------------------------
// ce_out        0.125
// -- -------------------------------------------------------------
// 
// 
// Output Signal                 Clock Enable  Sample Time
// -- -------------------------------------------------------------
// Out1                          ce_out        0.125
// -- -------------------------------------------------------------
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Raised_Cosine_Transmit_Filter
// Source Path: gm_gm_Modulation_test/Subsystem/Raised Cosine Transmit Filter
// Hierarchy Level: 0
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Raised_Cosine_Transmit_Filter
          (clk,
           reset,
           clk_enable,
           In1,
           ce_out,
           Out1);


  input   clk;
  input   reset;
  input   clk_enable;
  input   [31:0] In1;  // uint32
  output  ce_out;
  output  [31:0] Out1;  // uint32


  wire enb_1_1_1;
  wire signed [31:0] FIR_Interpolation_out1;  // int32
  wire [31:0] Data_Type_Conversion_out1;  // uint32


  assign enb_1_1_1 = clk_enable;

  FIR_Interpolation u_FIR_Interpolation (.clk(clk),
                                         .enb_1_1_1(enb_1_1_1),
                                         .reset(reset),
                                         .FIR_Interpolation_in(In1),  // uint32
                                         .FIR_Interpolation_out(FIR_Interpolation_out1)  // int32
                                         );

  assign Data_Type_Conversion_out1 = FIR_Interpolation_out1;



  assign Out1 = Data_Type_Conversion_out1;

  assign ce_out = enb_1_1_1;

endmodule  // Raised_Cosine_Transmit_Filter

