// ------------------------------------------------------------
// 
// File Name: C:\UBC Summer 2021\gitproject\ELEC391_Final_Project\mike\V_Normal_RC\Filter_for_16PSK\hdlcoder\receiver1\gm_gm_Modulation_test\FIR_Decimation
// Created: 2021-06-15 22:33:46
// Generated by MATLAB 9.10 and HDL Coder 3.18
// 
// ------------------------------------------------------------
// 
// 
// ------------------------------------------------------------
// 
// Module: FIR_Decimation
// Source Path: /FIR_Decimation
// 
// ------------------------------------------------------------
// 
// HDL Implementation    : Fully parallel
// Folding Factor        : 1
// Multipliers           : 81



`timescale 1 ns / 1 ns

module FIR_Decimation
               (
                clk,
                enb_1_1_1,
                reset,
                FIR_Decimation_in,
                FIR_Decimation_out
                );

  input   clk; 
  input   enb_1_1_1; 
  input   reset; 
  input   signed [63:0] FIR_Decimation_in; //sfix64
  output  signed [63:0] FIR_Decimation_out; //sfix64

////////////////////////////////////////////////////////////////
//Module Architecture: FIR_Decimation
////////////////////////////////////////////////////////////////
  // Local Functions
  // Type Definitions
  // Constants
  parameter signed [63:0] coeffphase1_1 = 64'hFE769190700B3ED0; //sfix64_En64
  parameter signed [63:0] coeffphase1_2 = 64'h027A065B4DA622E0; //sfix64_En64
  parameter signed [63:0] coeffphase1_3 = 64'hFC9593D0781F3820; //sfix64_En64
  parameter signed [63:0] coeffphase1_4 = 64'h0437A42B5A7B2680; //sfix64_En64
  parameter signed [63:0] coeffphase1_5 = 64'hFB3E3DA86835D080; //sfix64_En64
  parameter signed [63:0] coeffphase1_6 = 64'h5F797D0199F19000; //sfix64_En64
  parameter signed [63:0] coeffphase1_7 = 64'hFB3E3DA86835D080; //sfix64_En64
  parameter signed [63:0] coeffphase1_8 = 64'h0437A42B5A7B2680; //sfix64_En64
  parameter signed [63:0] coeffphase1_9 = 64'hFC9593D0781F3820; //sfix64_En64
  parameter signed [63:0] coeffphase1_10 = 64'h027A065B4DA622E0; //sfix64_En64
  parameter signed [63:0] coeffphase1_11 = 64'hFE769190700B3ED0; //sfix64_En64
  parameter signed [63:0] coeffphase2_1 = 64'hFEAEDE377A722920; //sfix64_En64
  parameter signed [63:0] coeffphase2_2 = 64'h017B7FC66C68BB10; //sfix64_En64
  parameter signed [63:0] coeffphase2_3 = 64'hFEF352720A5DEAA0; //sfix64_En64
  parameter signed [63:0] coeffphase2_4 = 64'hFF41133814DF92A8; //sfix64_En64
  parameter signed [63:0] coeffphase2_5 = 64'h0798985725FDFA00; //sfix64_En64
  parameter signed [63:0] coeffphase2_6 = 64'h5CB41E381266AC00; //sfix64_En64
  parameter signed [63:0] coeffphase2_7 = 64'hF293889D61922A80; //sfix64_En64
  parameter signed [63:0] coeffphase2_8 = 64'h07B66C1FDCB06880; //sfix64_En64
  parameter signed [63:0] coeffphase2_9 = 64'hFB23833F72D16A40; //sfix64_En64
  parameter signed [63:0] coeffphase2_10 = 64'h02DFA6ED4F81E400; //sfix64_En64
  parameter signed [63:0] coeffphase2_11 = 64'h0000000000000000; //sfix64_En64
  parameter signed [63:0] coeffphase3_1 = 64'hFF41D31F53FE45A0; //sfix64_En64
  parameter signed [63:0] coeffphase3_2 = 64'hFFFFFFFFFFFFFF74; //sfix64_En64
  parameter signed [63:0] coeffphase3_3 = 64'h01ECBA178F1BBFB0; //sfix64_En64
  parameter signed [63:0] coeffphase3_4 = 64'hF97992DF3C225EC0; //sfix64_En64
  parameter signed [63:0] coeffphase3_5 = 64'h16D67DF2AD87B200; //sfix64_En64
  parameter signed [63:0] coeffphase3_6 = 64'h54AFFC0C98C4D800; //sfix64_En64
  parameter signed [63:0] coeffphase3_7 = 64'hEDE4FEE1F5597000; //sfix64_En64
  parameter signed [63:0] coeffphase3_8 = 64'h0968E31DD815DE80; //sfix64_En64
  parameter signed [63:0] coeffphase3_9 = 64'hFABACF3E26B94D40; //sfix64_En64
  parameter signed [63:0] coeffphase3_10 = 64'h02AFD295055B4280; //sfix64_En64
  parameter signed [63:0] coeffphase3_11 = 64'h0000000000000000; //sfix64_En64
  parameter signed [63:0] coeffphase4_1 = 64'h001CEF4D6CB5DE34; //sfix64_En64
  parameter signed [63:0] coeffphase4_2 = 64'hFE4191827BEEDDE0; //sfix64_En64
  parameter signed [63:0] coeffphase4_3 = 64'h050757FC26E45C80; //sfix64_En64
  parameter signed [63:0] coeffphase4_4 = 64'hF3CB1049F3277580; //sfix64_En64
  parameter signed [63:0] coeffphase4_5 = 64'h27BD4BA7219E1600; //sfix64_En64
  parameter signed [63:0] coeffphase4_6 = 64'h48471B6ABB87FC00; //sfix64_En64
  parameter signed [63:0] coeffphase4_7 = 64'hED0075609038A800; //sfix64_En64
  parameter signed [63:0] coeffphase4_8 = 64'h094E66BA1ED25780; //sfix64_En64
  parameter signed [63:0] coeffphase4_9 = 64'hFB483162541BB9C0; //sfix64_En64
  parameter signed [63:0] coeffphase4_10 = 64'h0208CF2E09D0C040; //sfix64_En64
  parameter signed [63:0] coeffphase4_11 = 64'h0000000000000000; //sfix64_En64
  parameter signed [63:0] coeffphase5_1 = 64'h011AD608386CC900; //sfix64_En64
  parameter signed [63:0] coeffphase5_2 = 64'hFC90DED27EC77640; //sfix64_En64
  parameter signed [63:0] coeffphase5_3 = 64'h07AF282DCFC7C640; //sfix64_En64
  parameter signed [63:0] coeffphase5_4 = 64'hEF46CE328BB12100; //sfix64_En64
  parameter signed [63:0] coeffphase5_5 = 64'h38C53EC640753800; //sfix64_En64
  parameter signed [63:0] coeffphase5_6 = 64'h38C53EC640753800; //sfix64_En64
  parameter signed [63:0] coeffphase5_7 = 64'hEF46CE328BB12100; //sfix64_En64
  parameter signed [63:0] coeffphase5_8 = 64'h07AF282DCFC7C640; //sfix64_En64
  parameter signed [63:0] coeffphase5_9 = 64'hFC90DED27EC77640; //sfix64_En64
  parameter signed [63:0] coeffphase5_10 = 64'h011AD608386CC900; //sfix64_En64
  parameter signed [63:0] coeffphase5_11 = 64'h0000000000000000; //sfix64_En64
  parameter signed [63:0] coeffphase6_1 = 64'h0208CF2E09D0C040; //sfix64_En64
  parameter signed [63:0] coeffphase6_2 = 64'hFB483162541BB9C0; //sfix64_En64
  parameter signed [63:0] coeffphase6_3 = 64'h094E66BA1ED25780; //sfix64_En64
  parameter signed [63:0] coeffphase6_4 = 64'hED0075609038A800; //sfix64_En64
  parameter signed [63:0] coeffphase6_5 = 64'h48471B6ABB87FC00; //sfix64_En64
  parameter signed [63:0] coeffphase6_6 = 64'h27BD4BA7219E1600; //sfix64_En64
  parameter signed [63:0] coeffphase6_7 = 64'hF3CB1049F3277580; //sfix64_En64
  parameter signed [63:0] coeffphase6_8 = 64'h050757FC26E45C80; //sfix64_En64
  parameter signed [63:0] coeffphase6_9 = 64'hFE4191827BEEDDE0; //sfix64_En64
  parameter signed [63:0] coeffphase6_10 = 64'h001CEF4D6CB5DE34; //sfix64_En64
  parameter signed [63:0] coeffphase6_11 = 64'h0000000000000000; //sfix64_En64
  parameter signed [63:0] coeffphase7_1 = 64'h02AFD295055B4280; //sfix64_En64
  parameter signed [63:0] coeffphase7_2 = 64'hFABACF3E26B94D40; //sfix64_En64
  parameter signed [63:0] coeffphase7_3 = 64'h0968E31DD815DE80; //sfix64_En64
  parameter signed [63:0] coeffphase7_4 = 64'hEDE4FEE1F5597000; //sfix64_En64
  parameter signed [63:0] coeffphase7_5 = 64'h54AFFC0C98C4D800; //sfix64_En64
  parameter signed [63:0] coeffphase7_6 = 64'h16D67DF2AD87B200; //sfix64_En64
  parameter signed [63:0] coeffphase7_7 = 64'hF97992DF3C225EC0; //sfix64_En64
  parameter signed [63:0] coeffphase7_8 = 64'h01ECBA178F1BBFB0; //sfix64_En64
  parameter signed [63:0] coeffphase7_9 = 64'hFFFFFFFFFFFFFF74; //sfix64_En64
  parameter signed [63:0] coeffphase7_10 = 64'hFF41D31F53FE45A0; //sfix64_En64
  parameter signed [63:0] coeffphase7_11 = 64'h0000000000000000; //sfix64_En64
  parameter signed [63:0] coeffphase8_1 = 64'h02DFA6ED4F81E400; //sfix64_En64
  parameter signed [63:0] coeffphase8_2 = 64'hFB23833F72D16A40; //sfix64_En64
  parameter signed [63:0] coeffphase8_3 = 64'h07B66C1FDCB06880; //sfix64_En64
  parameter signed [63:0] coeffphase8_4 = 64'hF293889D61922A80; //sfix64_En64
  parameter signed [63:0] coeffphase8_5 = 64'h5CB41E381266AC00; //sfix64_En64
  parameter signed [63:0] coeffphase8_6 = 64'h0798985725FDFA00; //sfix64_En64
  parameter signed [63:0] coeffphase8_7 = 64'hFF41133814DF92A8; //sfix64_En64
  parameter signed [63:0] coeffphase8_8 = 64'hFEF352720A5DEAA0; //sfix64_En64
  parameter signed [63:0] coeffphase8_9 = 64'h017B7FC66C68BB10; //sfix64_En64
  parameter signed [63:0] coeffphase8_10 = 64'hFEAEDE377A722920; //sfix64_En64
  parameter signed [63:0] coeffphase8_11 = 64'h0000000000000000; //sfix64_En64

  // Signals
  reg  [7:0] ring_count; // ufix8
  wire phase_0; // boolean
  wire phase_1; // boolean
  wire phase_2; // boolean
  wire phase_3; // boolean
  wire phase_4; // boolean
  wire phase_5; // boolean
  wire phase_6; // boolean
  wire phase_7; // boolean
  wire signed [63:0] input_typeconvert; // sfix64
  reg  signed [63:0] input_pipeline_phase0 [0:9] ; // sfix64
  reg  signed [63:0] input_pipeline_phase1 [0:9] ; // sfix64
  reg  signed [63:0] input_pipeline_phase2 [0:9] ; // sfix64
  reg  signed [63:0] input_pipeline_phase3 [0:9] ; // sfix64
  reg  signed [63:0] input_pipeline_phase4 [0:9] ; // sfix64
  reg  signed [63:0] input_pipeline_phase5 [0:9] ; // sfix64
  reg  signed [63:0] input_pipeline_phase6 [0:9] ; // sfix64
  reg  signed [63:0] input_pipeline_phase7 [0:9] ; // sfix64
  wire signed [63:0] product_phase0_1; // sfix64
  wire signed [127:0] mul_temp; // sfix128_En64
  wire signed [63:0] product_phase0_2; // sfix64
  wire signed [127:0] mul_temp_1; // sfix128_En64
  wire signed [63:0] product_phase0_3; // sfix64
  wire signed [127:0] mul_temp_2; // sfix128_En64
  wire signed [63:0] product_phase0_4; // sfix64
  wire signed [127:0] mul_temp_3; // sfix128_En64
  wire signed [63:0] product_phase0_5; // sfix64
  wire signed [127:0] mul_temp_4; // sfix128_En64
  wire signed [63:0] product_phase0_6; // sfix64
  wire signed [127:0] mul_temp_5; // sfix128_En64
  wire signed [63:0] product_phase0_7; // sfix64
  wire signed [127:0] mul_temp_6; // sfix128_En64
  wire signed [63:0] product_phase0_8; // sfix64
  wire signed [127:0] mul_temp_7; // sfix128_En64
  wire signed [63:0] product_phase0_9; // sfix64
  wire signed [127:0] mul_temp_8; // sfix128_En64
  wire signed [63:0] product_phase0_10; // sfix64
  wire signed [127:0] mul_temp_9; // sfix128_En64
  wire signed [63:0] product_phase0_11; // sfix64
  wire signed [127:0] mul_temp_10; // sfix128_En64
  wire signed [63:0] product_phase1_1; // sfix64
  wire signed [127:0] mul_temp_11; // sfix128_En64
  wire signed [63:0] product_phase1_2; // sfix64
  wire signed [127:0] mul_temp_12; // sfix128_En64
  wire signed [63:0] product_phase1_3; // sfix64
  wire signed [127:0] mul_temp_13; // sfix128_En64
  wire signed [63:0] product_phase1_4; // sfix64
  wire signed [127:0] mul_temp_14; // sfix128_En64
  wire signed [63:0] product_phase1_5; // sfix64
  wire signed [127:0] mul_temp_15; // sfix128_En64
  wire signed [63:0] product_phase1_6; // sfix64
  wire signed [127:0] mul_temp_16; // sfix128_En64
  wire signed [63:0] product_phase1_7; // sfix64
  wire signed [127:0] mul_temp_17; // sfix128_En64
  wire signed [63:0] product_phase1_8; // sfix64
  wire signed [127:0] mul_temp_18; // sfix128_En64
  wire signed [63:0] product_phase1_9; // sfix64
  wire signed [127:0] mul_temp_19; // sfix128_En64
  wire signed [63:0] product_phase1_10; // sfix64
  wire signed [127:0] mul_temp_20; // sfix128_En64
  wire signed [63:0] product_phase2_1; // sfix64
  wire signed [127:0] mul_temp_21; // sfix128_En64
  wire signed [63:0] product_phase2_2; // sfix64
  wire signed [127:0] mul_temp_22; // sfix128_En64
  wire signed [63:0] product_phase2_3; // sfix64
  wire signed [127:0] mul_temp_23; // sfix128_En64
  wire signed [63:0] product_phase2_4; // sfix64
  wire signed [127:0] mul_temp_24; // sfix128_En64
  wire signed [63:0] product_phase2_5; // sfix64
  wire signed [127:0] mul_temp_25; // sfix128_En64
  wire signed [63:0] product_phase2_6; // sfix64
  wire signed [127:0] mul_temp_26; // sfix128_En64
  wire signed [63:0] product_phase2_7; // sfix64
  wire signed [127:0] mul_temp_27; // sfix128_En64
  wire signed [63:0] product_phase2_8; // sfix64
  wire signed [127:0] mul_temp_28; // sfix128_En64
  wire signed [63:0] product_phase2_9; // sfix64
  wire signed [127:0] mul_temp_29; // sfix128_En64
  wire signed [63:0] product_phase2_10; // sfix64
  wire signed [127:0] mul_temp_30; // sfix128_En64
  wire signed [63:0] product_phase3_1; // sfix64
  wire signed [127:0] mul_temp_31; // sfix128_En64
  wire signed [63:0] product_phase3_2; // sfix64
  wire signed [127:0] mul_temp_32; // sfix128_En64
  wire signed [63:0] product_phase3_3; // sfix64
  wire signed [127:0] mul_temp_33; // sfix128_En64
  wire signed [63:0] product_phase3_4; // sfix64
  wire signed [127:0] mul_temp_34; // sfix128_En64
  wire signed [63:0] product_phase3_5; // sfix64
  wire signed [127:0] mul_temp_35; // sfix128_En64
  wire signed [63:0] product_phase3_6; // sfix64
  wire signed [127:0] mul_temp_36; // sfix128_En64
  wire signed [63:0] product_phase3_7; // sfix64
  wire signed [127:0] mul_temp_37; // sfix128_En64
  wire signed [63:0] product_phase3_8; // sfix64
  wire signed [127:0] mul_temp_38; // sfix128_En64
  wire signed [63:0] product_phase3_9; // sfix64
  wire signed [127:0] mul_temp_39; // sfix128_En64
  wire signed [63:0] product_phase3_10; // sfix64
  wire signed [127:0] mul_temp_40; // sfix128_En64
  wire signed [63:0] product_phase4_1; // sfix64
  wire signed [127:0] mul_temp_41; // sfix128_En64
  wire signed [63:0] product_phase4_2; // sfix64
  wire signed [127:0] mul_temp_42; // sfix128_En64
  wire signed [63:0] product_phase4_3; // sfix64
  wire signed [127:0] mul_temp_43; // sfix128_En64
  wire signed [63:0] product_phase4_4; // sfix64
  wire signed [127:0] mul_temp_44; // sfix128_En64
  wire signed [63:0] product_phase4_5; // sfix64
  wire signed [127:0] mul_temp_45; // sfix128_En64
  wire signed [63:0] product_phase4_6; // sfix64
  wire signed [127:0] mul_temp_46; // sfix128_En64
  wire signed [63:0] product_phase4_7; // sfix64
  wire signed [127:0] mul_temp_47; // sfix128_En64
  wire signed [63:0] product_phase4_8; // sfix64
  wire signed [127:0] mul_temp_48; // sfix128_En64
  wire signed [63:0] product_phase4_9; // sfix64
  wire signed [127:0] mul_temp_49; // sfix128_En64
  wire signed [63:0] product_phase4_10; // sfix64
  wire signed [127:0] mul_temp_50; // sfix128_En64
  wire signed [63:0] product_phase5_1; // sfix64
  wire signed [127:0] mul_temp_51; // sfix128_En64
  wire signed [63:0] product_phase5_2; // sfix64
  wire signed [127:0] mul_temp_52; // sfix128_En64
  wire signed [63:0] product_phase5_3; // sfix64
  wire signed [127:0] mul_temp_53; // sfix128_En64
  wire signed [63:0] product_phase5_4; // sfix64
  wire signed [127:0] mul_temp_54; // sfix128_En64
  wire signed [63:0] product_phase5_5; // sfix64
  wire signed [127:0] mul_temp_55; // sfix128_En64
  wire signed [63:0] product_phase5_6; // sfix64
  wire signed [127:0] mul_temp_56; // sfix128_En64
  wire signed [63:0] product_phase5_7; // sfix64
  wire signed [127:0] mul_temp_57; // sfix128_En64
  wire signed [63:0] product_phase5_8; // sfix64
  wire signed [127:0] mul_temp_58; // sfix128_En64
  wire signed [63:0] product_phase5_9; // sfix64
  wire signed [127:0] mul_temp_59; // sfix128_En64
  wire signed [63:0] product_phase5_10; // sfix64
  wire signed [127:0] mul_temp_60; // sfix128_En64
  wire signed [63:0] product_phase6_1; // sfix64
  wire signed [127:0] mul_temp_61; // sfix128_En64
  wire signed [63:0] product_phase6_2; // sfix64
  wire signed [127:0] mul_temp_62; // sfix128_En64
  wire signed [63:0] product_phase6_3; // sfix64
  wire signed [127:0] mul_temp_63; // sfix128_En64
  wire signed [63:0] product_phase6_4; // sfix64
  wire signed [127:0] mul_temp_64; // sfix128_En64
  wire signed [63:0] product_phase6_5; // sfix64
  wire signed [127:0] mul_temp_65; // sfix128_En64
  wire signed [63:0] product_phase6_6; // sfix64
  wire signed [127:0] mul_temp_66; // sfix128_En64
  wire signed [63:0] product_phase6_7; // sfix64
  wire signed [127:0] mul_temp_67; // sfix128_En64
  wire signed [63:0] product_phase6_8; // sfix64
  wire signed [127:0] mul_temp_68; // sfix128_En64
  wire signed [63:0] product_phase6_9; // sfix64
  wire signed [127:0] mul_temp_69; // sfix128_En64
  wire signed [63:0] product_phase6_10; // sfix64
  wire signed [127:0] mul_temp_70; // sfix128_En64
  wire signed [63:0] product_phase7_1; // sfix64
  wire signed [127:0] mul_temp_71; // sfix128_En64
  wire signed [63:0] product_phase7_2; // sfix64
  wire signed [127:0] mul_temp_72; // sfix128_En64
  wire signed [63:0] product_phase7_3; // sfix64
  wire signed [127:0] mul_temp_73; // sfix128_En64
  wire signed [63:0] product_phase7_4; // sfix64
  wire signed [127:0] mul_temp_74; // sfix128_En64
  wire signed [63:0] product_phase7_5; // sfix64
  wire signed [127:0] mul_temp_75; // sfix128_En64
  wire signed [63:0] product_phase7_6; // sfix64
  wire signed [127:0] mul_temp_76; // sfix128_En64
  wire signed [63:0] product_phase7_7; // sfix64
  wire signed [127:0] mul_temp_77; // sfix128_En64
  wire signed [63:0] product_phase7_8; // sfix64
  wire signed [127:0] mul_temp_78; // sfix128_En64
  wire signed [63:0] product_phase7_9; // sfix64
  wire signed [127:0] mul_temp_79; // sfix128_En64
  wire signed [63:0] product_phase7_10; // sfix64
  wire signed [127:0] mul_temp_80; // sfix128_En64
  wire signed [63:0] quantized_sum; // sfix64
  wire signed [63:0] sum1; // sfix64
  wire signed [63:0] add_cast; // sfix64
  wire signed [63:0] add_cast_1; // sfix64
  wire signed [64:0] add_temp; // sfix65
  wire signed [63:0] sum2; // sfix64
  wire signed [63:0] add_cast_2; // sfix64
  wire signed [63:0] add_cast_3; // sfix64
  wire signed [64:0] add_temp_1; // sfix65
  wire signed [63:0] sum3; // sfix64
  wire signed [63:0] add_cast_4; // sfix64
  wire signed [63:0] add_cast_5; // sfix64
  wire signed [64:0] add_temp_2; // sfix65
  wire signed [63:0] sum4; // sfix64
  wire signed [63:0] add_cast_6; // sfix64
  wire signed [63:0] add_cast_7; // sfix64
  wire signed [64:0] add_temp_3; // sfix65
  wire signed [63:0] sum5; // sfix64
  wire signed [63:0] add_cast_8; // sfix64
  wire signed [63:0] add_cast_9; // sfix64
  wire signed [64:0] add_temp_4; // sfix65
  wire signed [63:0] sum6; // sfix64
  wire signed [63:0] add_cast_10; // sfix64
  wire signed [63:0] add_cast_11; // sfix64
  wire signed [64:0] add_temp_5; // sfix65
  wire signed [63:0] sum7; // sfix64
  wire signed [63:0] add_cast_12; // sfix64
  wire signed [63:0] add_cast_13; // sfix64
  wire signed [64:0] add_temp_6; // sfix65
  wire signed [63:0] sum8; // sfix64
  wire signed [63:0] add_cast_14; // sfix64
  wire signed [63:0] add_cast_15; // sfix64
  wire signed [64:0] add_temp_7; // sfix65
  wire signed [63:0] sum9; // sfix64
  wire signed [63:0] add_cast_16; // sfix64
  wire signed [63:0] add_cast_17; // sfix64
  wire signed [64:0] add_temp_8; // sfix65
  wire signed [63:0] sum10; // sfix64
  wire signed [63:0] add_cast_18; // sfix64
  wire signed [63:0] add_cast_19; // sfix64
  wire signed [64:0] add_temp_9; // sfix65
  wire signed [63:0] sum11; // sfix64
  wire signed [63:0] add_cast_20; // sfix64
  wire signed [63:0] add_cast_21; // sfix64
  wire signed [64:0] add_temp_10; // sfix65
  wire signed [63:0] sum12; // sfix64
  wire signed [63:0] add_cast_22; // sfix64
  wire signed [63:0] add_cast_23; // sfix64
  wire signed [64:0] add_temp_11; // sfix65
  wire signed [63:0] sum13; // sfix64
  wire signed [63:0] add_cast_24; // sfix64
  wire signed [63:0] add_cast_25; // sfix64
  wire signed [64:0] add_temp_12; // sfix65
  wire signed [63:0] sum14; // sfix64
  wire signed [63:0] add_cast_26; // sfix64
  wire signed [63:0] add_cast_27; // sfix64
  wire signed [64:0] add_temp_13; // sfix65
  wire signed [63:0] sum15; // sfix64
  wire signed [63:0] add_cast_28; // sfix64
  wire signed [63:0] add_cast_29; // sfix64
  wire signed [64:0] add_temp_14; // sfix65
  wire signed [63:0] sum16; // sfix64
  wire signed [63:0] add_cast_30; // sfix64
  wire signed [63:0] add_cast_31; // sfix64
  wire signed [64:0] add_temp_15; // sfix65
  wire signed [63:0] sum17; // sfix64
  wire signed [63:0] add_cast_32; // sfix64
  wire signed [63:0] add_cast_33; // sfix64
  wire signed [64:0] add_temp_16; // sfix65
  wire signed [63:0] sum18; // sfix64
  wire signed [63:0] add_cast_34; // sfix64
  wire signed [63:0] add_cast_35; // sfix64
  wire signed [64:0] add_temp_17; // sfix65
  wire signed [63:0] sum19; // sfix64
  wire signed [63:0] add_cast_36; // sfix64
  wire signed [63:0] add_cast_37; // sfix64
  wire signed [64:0] add_temp_18; // sfix65
  wire signed [63:0] sum20; // sfix64
  wire signed [63:0] add_cast_38; // sfix64
  wire signed [63:0] add_cast_39; // sfix64
  wire signed [64:0] add_temp_19; // sfix65
  wire signed [63:0] sum21; // sfix64
  wire signed [63:0] add_cast_40; // sfix64
  wire signed [63:0] add_cast_41; // sfix64
  wire signed [64:0] add_temp_20; // sfix65
  wire signed [63:0] sum22; // sfix64
  wire signed [63:0] add_cast_42; // sfix64
  wire signed [63:0] add_cast_43; // sfix64
  wire signed [64:0] add_temp_21; // sfix65
  wire signed [63:0] sum23; // sfix64
  wire signed [63:0] add_cast_44; // sfix64
  wire signed [63:0] add_cast_45; // sfix64
  wire signed [64:0] add_temp_22; // sfix65
  wire signed [63:0] sum24; // sfix64
  wire signed [63:0] add_cast_46; // sfix64
  wire signed [63:0] add_cast_47; // sfix64
  wire signed [64:0] add_temp_23; // sfix65
  wire signed [63:0] sum25; // sfix64
  wire signed [63:0] add_cast_48; // sfix64
  wire signed [63:0] add_cast_49; // sfix64
  wire signed [64:0] add_temp_24; // sfix65
  wire signed [63:0] sum26; // sfix64
  wire signed [63:0] add_cast_50; // sfix64
  wire signed [63:0] add_cast_51; // sfix64
  wire signed [64:0] add_temp_25; // sfix65
  wire signed [63:0] sum27; // sfix64
  wire signed [63:0] add_cast_52; // sfix64
  wire signed [63:0] add_cast_53; // sfix64
  wire signed [64:0] add_temp_26; // sfix65
  wire signed [63:0] sum28; // sfix64
  wire signed [63:0] add_cast_54; // sfix64
  wire signed [63:0] add_cast_55; // sfix64
  wire signed [64:0] add_temp_27; // sfix65
  wire signed [63:0] sum29; // sfix64
  wire signed [63:0] add_cast_56; // sfix64
  wire signed [63:0] add_cast_57; // sfix64
  wire signed [64:0] add_temp_28; // sfix65
  wire signed [63:0] sum30; // sfix64
  wire signed [63:0] add_cast_58; // sfix64
  wire signed [63:0] add_cast_59; // sfix64
  wire signed [64:0] add_temp_29; // sfix65
  wire signed [63:0] sum31; // sfix64
  wire signed [63:0] add_cast_60; // sfix64
  wire signed [63:0] add_cast_61; // sfix64
  wire signed [64:0] add_temp_30; // sfix65
  wire signed [63:0] sum32; // sfix64
  wire signed [63:0] add_cast_62; // sfix64
  wire signed [63:0] add_cast_63; // sfix64
  wire signed [64:0] add_temp_31; // sfix65
  wire signed [63:0] sum33; // sfix64
  wire signed [63:0] add_cast_64; // sfix64
  wire signed [63:0] add_cast_65; // sfix64
  wire signed [64:0] add_temp_32; // sfix65
  wire signed [63:0] sum34; // sfix64
  wire signed [63:0] add_cast_66; // sfix64
  wire signed [63:0] add_cast_67; // sfix64
  wire signed [64:0] add_temp_33; // sfix65
  wire signed [63:0] sum35; // sfix64
  wire signed [63:0] add_cast_68; // sfix64
  wire signed [63:0] add_cast_69; // sfix64
  wire signed [64:0] add_temp_34; // sfix65
  wire signed [63:0] sum36; // sfix64
  wire signed [63:0] add_cast_70; // sfix64
  wire signed [63:0] add_cast_71; // sfix64
  wire signed [64:0] add_temp_35; // sfix65
  wire signed [63:0] sum37; // sfix64
  wire signed [63:0] add_cast_72; // sfix64
  wire signed [63:0] add_cast_73; // sfix64
  wire signed [64:0] add_temp_36; // sfix65
  wire signed [63:0] sum38; // sfix64
  wire signed [63:0] add_cast_74; // sfix64
  wire signed [63:0] add_cast_75; // sfix64
  wire signed [64:0] add_temp_37; // sfix65
  wire signed [63:0] sum39; // sfix64
  wire signed [63:0] add_cast_76; // sfix64
  wire signed [63:0] add_cast_77; // sfix64
  wire signed [64:0] add_temp_38; // sfix65
  wire signed [63:0] sum40; // sfix64
  wire signed [63:0] add_cast_78; // sfix64
  wire signed [63:0] add_cast_79; // sfix64
  wire signed [64:0] add_temp_39; // sfix65
  wire signed [63:0] sum41; // sfix64
  wire signed [63:0] add_cast_80; // sfix64
  wire signed [63:0] add_cast_81; // sfix64
  wire signed [64:0] add_temp_40; // sfix65
  wire signed [63:0] sum42; // sfix64
  wire signed [63:0] add_cast_82; // sfix64
  wire signed [63:0] add_cast_83; // sfix64
  wire signed [64:0] add_temp_41; // sfix65
  wire signed [63:0] sum43; // sfix64
  wire signed [63:0] add_cast_84; // sfix64
  wire signed [63:0] add_cast_85; // sfix64
  wire signed [64:0] add_temp_42; // sfix65
  wire signed [63:0] sum44; // sfix64
  wire signed [63:0] add_cast_86; // sfix64
  wire signed [63:0] add_cast_87; // sfix64
  wire signed [64:0] add_temp_43; // sfix65
  wire signed [63:0] sum45; // sfix64
  wire signed [63:0] add_cast_88; // sfix64
  wire signed [63:0] add_cast_89; // sfix64
  wire signed [64:0] add_temp_44; // sfix65
  wire signed [63:0] sum46; // sfix64
  wire signed [63:0] add_cast_90; // sfix64
  wire signed [63:0] add_cast_91; // sfix64
  wire signed [64:0] add_temp_45; // sfix65
  wire signed [63:0] sum47; // sfix64
  wire signed [63:0] add_cast_92; // sfix64
  wire signed [63:0] add_cast_93; // sfix64
  wire signed [64:0] add_temp_46; // sfix65
  wire signed [63:0] sum48; // sfix64
  wire signed [63:0] add_cast_94; // sfix64
  wire signed [63:0] add_cast_95; // sfix64
  wire signed [64:0] add_temp_47; // sfix65
  wire signed [63:0] sum49; // sfix64
  wire signed [63:0] add_cast_96; // sfix64
  wire signed [63:0] add_cast_97; // sfix64
  wire signed [64:0] add_temp_48; // sfix65
  wire signed [63:0] sum50; // sfix64
  wire signed [63:0] add_cast_98; // sfix64
  wire signed [63:0] add_cast_99; // sfix64
  wire signed [64:0] add_temp_49; // sfix65
  wire signed [63:0] sum51; // sfix64
  wire signed [63:0] add_cast_100; // sfix64
  wire signed [63:0] add_cast_101; // sfix64
  wire signed [64:0] add_temp_50; // sfix65
  wire signed [63:0] sum52; // sfix64
  wire signed [63:0] add_cast_102; // sfix64
  wire signed [63:0] add_cast_103; // sfix64
  wire signed [64:0] add_temp_51; // sfix65
  wire signed [63:0] sum53; // sfix64
  wire signed [63:0] add_cast_104; // sfix64
  wire signed [63:0] add_cast_105; // sfix64
  wire signed [64:0] add_temp_52; // sfix65
  wire signed [63:0] sum54; // sfix64
  wire signed [63:0] add_cast_106; // sfix64
  wire signed [63:0] add_cast_107; // sfix64
  wire signed [64:0] add_temp_53; // sfix65
  wire signed [63:0] sum55; // sfix64
  wire signed [63:0] add_cast_108; // sfix64
  wire signed [63:0] add_cast_109; // sfix64
  wire signed [64:0] add_temp_54; // sfix65
  wire signed [63:0] sum56; // sfix64
  wire signed [63:0] add_cast_110; // sfix64
  wire signed [63:0] add_cast_111; // sfix64
  wire signed [64:0] add_temp_55; // sfix65
  wire signed [63:0] sum57; // sfix64
  wire signed [63:0] add_cast_112; // sfix64
  wire signed [63:0] add_cast_113; // sfix64
  wire signed [64:0] add_temp_56; // sfix65
  wire signed [63:0] sum58; // sfix64
  wire signed [63:0] add_cast_114; // sfix64
  wire signed [63:0] add_cast_115; // sfix64
  wire signed [64:0] add_temp_57; // sfix65
  wire signed [63:0] sum59; // sfix64
  wire signed [63:0] add_cast_116; // sfix64
  wire signed [63:0] add_cast_117; // sfix64
  wire signed [64:0] add_temp_58; // sfix65
  wire signed [63:0] sum60; // sfix64
  wire signed [63:0] add_cast_118; // sfix64
  wire signed [63:0] add_cast_119; // sfix64
  wire signed [64:0] add_temp_59; // sfix65
  wire signed [63:0] sum61; // sfix64
  wire signed [63:0] add_cast_120; // sfix64
  wire signed [63:0] add_cast_121; // sfix64
  wire signed [64:0] add_temp_60; // sfix65
  wire signed [63:0] sum62; // sfix64
  wire signed [63:0] add_cast_122; // sfix64
  wire signed [63:0] add_cast_123; // sfix64
  wire signed [64:0] add_temp_61; // sfix65
  wire signed [63:0] sum63; // sfix64
  wire signed [63:0] add_cast_124; // sfix64
  wire signed [63:0] add_cast_125; // sfix64
  wire signed [64:0] add_temp_62; // sfix65
  wire signed [63:0] sum64; // sfix64
  wire signed [63:0] add_cast_126; // sfix64
  wire signed [63:0] add_cast_127; // sfix64
  wire signed [64:0] add_temp_63; // sfix65
  wire signed [63:0] sum65; // sfix64
  wire signed [63:0] add_cast_128; // sfix64
  wire signed [63:0] add_cast_129; // sfix64
  wire signed [64:0] add_temp_64; // sfix65
  wire signed [63:0] sum66; // sfix64
  wire signed [63:0] add_cast_130; // sfix64
  wire signed [63:0] add_cast_131; // sfix64
  wire signed [64:0] add_temp_65; // sfix65
  wire signed [63:0] sum67; // sfix64
  wire signed [63:0] add_cast_132; // sfix64
  wire signed [63:0] add_cast_133; // sfix64
  wire signed [64:0] add_temp_66; // sfix65
  wire signed [63:0] sum68; // sfix64
  wire signed [63:0] add_cast_134; // sfix64
  wire signed [63:0] add_cast_135; // sfix64
  wire signed [64:0] add_temp_67; // sfix65
  wire signed [63:0] sum69; // sfix64
  wire signed [63:0] add_cast_136; // sfix64
  wire signed [63:0] add_cast_137; // sfix64
  wire signed [64:0] add_temp_68; // sfix65
  wire signed [63:0] sum70; // sfix64
  wire signed [63:0] add_cast_138; // sfix64
  wire signed [63:0] add_cast_139; // sfix64
  wire signed [64:0] add_temp_69; // sfix65
  wire signed [63:0] sum71; // sfix64
  wire signed [63:0] add_cast_140; // sfix64
  wire signed [63:0] add_cast_141; // sfix64
  wire signed [64:0] add_temp_70; // sfix65
  wire signed [63:0] sum72; // sfix64
  wire signed [63:0] add_cast_142; // sfix64
  wire signed [63:0] add_cast_143; // sfix64
  wire signed [64:0] add_temp_71; // sfix65
  wire signed [63:0] sum73; // sfix64
  wire signed [63:0] add_cast_144; // sfix64
  wire signed [63:0] add_cast_145; // sfix64
  wire signed [64:0] add_temp_72; // sfix65
  wire signed [63:0] sum74; // sfix64
  wire signed [63:0] add_cast_146; // sfix64
  wire signed [63:0] add_cast_147; // sfix64
  wire signed [64:0] add_temp_73; // sfix65
  wire signed [63:0] sum75; // sfix64
  wire signed [63:0] add_cast_148; // sfix64
  wire signed [63:0] add_cast_149; // sfix64
  wire signed [64:0] add_temp_74; // sfix65
  wire signed [63:0] sum76; // sfix64
  wire signed [63:0] add_cast_150; // sfix64
  wire signed [63:0] add_cast_151; // sfix64
  wire signed [64:0] add_temp_75; // sfix65
  wire signed [63:0] sum77; // sfix64
  wire signed [63:0] add_cast_152; // sfix64
  wire signed [63:0] add_cast_153; // sfix64
  wire signed [64:0] add_temp_76; // sfix65
  wire signed [63:0] sum78; // sfix64
  wire signed [63:0] add_cast_154; // sfix64
  wire signed [63:0] add_cast_155; // sfix64
  wire signed [64:0] add_temp_77; // sfix65
  wire signed [63:0] sum79; // sfix64
  wire signed [63:0] add_cast_156; // sfix64
  wire signed [63:0] add_cast_157; // sfix64
  wire signed [64:0] add_temp_78; // sfix65
  wire signed [63:0] sum80; // sfix64
  wire signed [63:0] add_cast_158; // sfix64
  wire signed [63:0] add_cast_159; // sfix64
  wire signed [64:0] add_temp_79; // sfix65
  reg  signed [63:0] regout; // sfix64
  wire signed [63:0] muxout; // sfix64

  // Block Statements
  always @ (posedge clk or posedge reset)
    begin: ce_output
      if (reset == 1'b1) begin
        ring_count <= 1;
      end
      else begin
                if (enb_1_1_1 == 1'b1) begin
        ring_count <= {ring_count[0], ring_count[7 : 1]};
              end
            end
    end // ce_output

  assign  phase_0 = ring_count[0]  && enb_1_1_1;

  assign  phase_1 = ring_count[1]  && enb_1_1_1;

  assign  phase_2 = ring_count[2]  && enb_1_1_1;

  assign  phase_3 = ring_count[3]  && enb_1_1_1;

  assign  phase_4 = ring_count[4]  && enb_1_1_1;

  assign  phase_5 = ring_count[5]  && enb_1_1_1;

  assign  phase_6 = ring_count[6]  && enb_1_1_1;

  assign  phase_7 = ring_count[7]  && enb_1_1_1;

  assign input_typeconvert = FIR_Decimation_in;

  always @( posedge clk or posedge reset)
    begin: Delay_Pipeline_Phase0_process
      if (reset == 1'b1) begin
        input_pipeline_phase0[0] <= 0;
        input_pipeline_phase0[1] <= 0;
        input_pipeline_phase0[2] <= 0;
        input_pipeline_phase0[3] <= 0;
        input_pipeline_phase0[4] <= 0;
        input_pipeline_phase0[5] <= 0;
        input_pipeline_phase0[6] <= 0;
        input_pipeline_phase0[7] <= 0;
        input_pipeline_phase0[8] <= 0;
        input_pipeline_phase0[9] <= 0;
      end
      else begin
        if (phase_0 == 1'b1) begin
          input_pipeline_phase0[0] <= input_typeconvert;
          input_pipeline_phase0[1] <= input_pipeline_phase0[0];
          input_pipeline_phase0[2] <= input_pipeline_phase0[1];
          input_pipeline_phase0[3] <= input_pipeline_phase0[2];
          input_pipeline_phase0[4] <= input_pipeline_phase0[3];
          input_pipeline_phase0[5] <= input_pipeline_phase0[4];
          input_pipeline_phase0[6] <= input_pipeline_phase0[5];
          input_pipeline_phase0[7] <= input_pipeline_phase0[6];
          input_pipeline_phase0[8] <= input_pipeline_phase0[7];
          input_pipeline_phase0[9] <= input_pipeline_phase0[8];
        end
      end
    end // Delay_Pipeline_Phase0_process


  always @( posedge clk or posedge reset)
    begin: Delay_Pipeline_Phase1_process
      if (reset == 1'b1) begin
        input_pipeline_phase1[0] <= 0;
        input_pipeline_phase1[1] <= 0;
        input_pipeline_phase1[2] <= 0;
        input_pipeline_phase1[3] <= 0;
        input_pipeline_phase1[4] <= 0;
        input_pipeline_phase1[5] <= 0;
        input_pipeline_phase1[6] <= 0;
        input_pipeline_phase1[7] <= 0;
        input_pipeline_phase1[8] <= 0;
        input_pipeline_phase1[9] <= 0;
      end
      else begin
        if (phase_1 == 1'b1) begin
          input_pipeline_phase1[0] <= input_typeconvert;
          input_pipeline_phase1[1] <= input_pipeline_phase1[0];
          input_pipeline_phase1[2] <= input_pipeline_phase1[1];
          input_pipeline_phase1[3] <= input_pipeline_phase1[2];
          input_pipeline_phase1[4] <= input_pipeline_phase1[3];
          input_pipeline_phase1[5] <= input_pipeline_phase1[4];
          input_pipeline_phase1[6] <= input_pipeline_phase1[5];
          input_pipeline_phase1[7] <= input_pipeline_phase1[6];
          input_pipeline_phase1[8] <= input_pipeline_phase1[7];
          input_pipeline_phase1[9] <= input_pipeline_phase1[8];
        end
      end
    end // Delay_Pipeline_Phase1_process


  always @( posedge clk or posedge reset)
    begin: Delay_Pipeline_Phase2_process
      if (reset == 1'b1) begin
        input_pipeline_phase2[0] <= 0;
        input_pipeline_phase2[1] <= 0;
        input_pipeline_phase2[2] <= 0;
        input_pipeline_phase2[3] <= 0;
        input_pipeline_phase2[4] <= 0;
        input_pipeline_phase2[5] <= 0;
        input_pipeline_phase2[6] <= 0;
        input_pipeline_phase2[7] <= 0;
        input_pipeline_phase2[8] <= 0;
        input_pipeline_phase2[9] <= 0;
      end
      else begin
        if (phase_2 == 1'b1) begin
          input_pipeline_phase2[0] <= input_typeconvert;
          input_pipeline_phase2[1] <= input_pipeline_phase2[0];
          input_pipeline_phase2[2] <= input_pipeline_phase2[1];
          input_pipeline_phase2[3] <= input_pipeline_phase2[2];
          input_pipeline_phase2[4] <= input_pipeline_phase2[3];
          input_pipeline_phase2[5] <= input_pipeline_phase2[4];
          input_pipeline_phase2[6] <= input_pipeline_phase2[5];
          input_pipeline_phase2[7] <= input_pipeline_phase2[6];
          input_pipeline_phase2[8] <= input_pipeline_phase2[7];
          input_pipeline_phase2[9] <= input_pipeline_phase2[8];
        end
      end
    end // Delay_Pipeline_Phase2_process


  always @( posedge clk or posedge reset)
    begin: Delay_Pipeline_Phase3_process
      if (reset == 1'b1) begin
        input_pipeline_phase3[0] <= 0;
        input_pipeline_phase3[1] <= 0;
        input_pipeline_phase3[2] <= 0;
        input_pipeline_phase3[3] <= 0;
        input_pipeline_phase3[4] <= 0;
        input_pipeline_phase3[5] <= 0;
        input_pipeline_phase3[6] <= 0;
        input_pipeline_phase3[7] <= 0;
        input_pipeline_phase3[8] <= 0;
        input_pipeline_phase3[9] <= 0;
      end
      else begin
        if (phase_3 == 1'b1) begin
          input_pipeline_phase3[0] <= input_typeconvert;
          input_pipeline_phase3[1] <= input_pipeline_phase3[0];
          input_pipeline_phase3[2] <= input_pipeline_phase3[1];
          input_pipeline_phase3[3] <= input_pipeline_phase3[2];
          input_pipeline_phase3[4] <= input_pipeline_phase3[3];
          input_pipeline_phase3[5] <= input_pipeline_phase3[4];
          input_pipeline_phase3[6] <= input_pipeline_phase3[5];
          input_pipeline_phase3[7] <= input_pipeline_phase3[6];
          input_pipeline_phase3[8] <= input_pipeline_phase3[7];
          input_pipeline_phase3[9] <= input_pipeline_phase3[8];
        end
      end
    end // Delay_Pipeline_Phase3_process


  always @( posedge clk or posedge reset)
    begin: Delay_Pipeline_Phase4_process
      if (reset == 1'b1) begin
        input_pipeline_phase4[0] <= 0;
        input_pipeline_phase4[1] <= 0;
        input_pipeline_phase4[2] <= 0;
        input_pipeline_phase4[3] <= 0;
        input_pipeline_phase4[4] <= 0;
        input_pipeline_phase4[5] <= 0;
        input_pipeline_phase4[6] <= 0;
        input_pipeline_phase4[7] <= 0;
        input_pipeline_phase4[8] <= 0;
        input_pipeline_phase4[9] <= 0;
      end
      else begin
        if (phase_4 == 1'b1) begin
          input_pipeline_phase4[0] <= input_typeconvert;
          input_pipeline_phase4[1] <= input_pipeline_phase4[0];
          input_pipeline_phase4[2] <= input_pipeline_phase4[1];
          input_pipeline_phase4[3] <= input_pipeline_phase4[2];
          input_pipeline_phase4[4] <= input_pipeline_phase4[3];
          input_pipeline_phase4[5] <= input_pipeline_phase4[4];
          input_pipeline_phase4[6] <= input_pipeline_phase4[5];
          input_pipeline_phase4[7] <= input_pipeline_phase4[6];
          input_pipeline_phase4[8] <= input_pipeline_phase4[7];
          input_pipeline_phase4[9] <= input_pipeline_phase4[8];
        end
      end
    end // Delay_Pipeline_Phase4_process


  always @( posedge clk or posedge reset)
    begin: Delay_Pipeline_Phase5_process
      if (reset == 1'b1) begin
        input_pipeline_phase5[0] <= 0;
        input_pipeline_phase5[1] <= 0;
        input_pipeline_phase5[2] <= 0;
        input_pipeline_phase5[3] <= 0;
        input_pipeline_phase5[4] <= 0;
        input_pipeline_phase5[5] <= 0;
        input_pipeline_phase5[6] <= 0;
        input_pipeline_phase5[7] <= 0;
        input_pipeline_phase5[8] <= 0;
        input_pipeline_phase5[9] <= 0;
      end
      else begin
        if (phase_5 == 1'b1) begin
          input_pipeline_phase5[0] <= input_typeconvert;
          input_pipeline_phase5[1] <= input_pipeline_phase5[0];
          input_pipeline_phase5[2] <= input_pipeline_phase5[1];
          input_pipeline_phase5[3] <= input_pipeline_phase5[2];
          input_pipeline_phase5[4] <= input_pipeline_phase5[3];
          input_pipeline_phase5[5] <= input_pipeline_phase5[4];
          input_pipeline_phase5[6] <= input_pipeline_phase5[5];
          input_pipeline_phase5[7] <= input_pipeline_phase5[6];
          input_pipeline_phase5[8] <= input_pipeline_phase5[7];
          input_pipeline_phase5[9] <= input_pipeline_phase5[8];
        end
      end
    end // Delay_Pipeline_Phase5_process


  always @( posedge clk or posedge reset)
    begin: Delay_Pipeline_Phase6_process
      if (reset == 1'b1) begin
        input_pipeline_phase6[0] <= 0;
        input_pipeline_phase6[1] <= 0;
        input_pipeline_phase6[2] <= 0;
        input_pipeline_phase6[3] <= 0;
        input_pipeline_phase6[4] <= 0;
        input_pipeline_phase6[5] <= 0;
        input_pipeline_phase6[6] <= 0;
        input_pipeline_phase6[7] <= 0;
        input_pipeline_phase6[8] <= 0;
        input_pipeline_phase6[9] <= 0;
      end
      else begin
        if (phase_6 == 1'b1) begin
          input_pipeline_phase6[0] <= input_typeconvert;
          input_pipeline_phase6[1] <= input_pipeline_phase6[0];
          input_pipeline_phase6[2] <= input_pipeline_phase6[1];
          input_pipeline_phase6[3] <= input_pipeline_phase6[2];
          input_pipeline_phase6[4] <= input_pipeline_phase6[3];
          input_pipeline_phase6[5] <= input_pipeline_phase6[4];
          input_pipeline_phase6[6] <= input_pipeline_phase6[5];
          input_pipeline_phase6[7] <= input_pipeline_phase6[6];
          input_pipeline_phase6[8] <= input_pipeline_phase6[7];
          input_pipeline_phase6[9] <= input_pipeline_phase6[8];
        end
      end
    end // Delay_Pipeline_Phase6_process


  always @( posedge clk or posedge reset)
    begin: Delay_Pipeline_Phase7_process
      if (reset == 1'b1) begin
        input_pipeline_phase7[0] <= 0;
        input_pipeline_phase7[1] <= 0;
        input_pipeline_phase7[2] <= 0;
        input_pipeline_phase7[3] <= 0;
        input_pipeline_phase7[4] <= 0;
        input_pipeline_phase7[5] <= 0;
        input_pipeline_phase7[6] <= 0;
        input_pipeline_phase7[7] <= 0;
        input_pipeline_phase7[8] <= 0;
        input_pipeline_phase7[9] <= 0;
      end
      else begin
        if (phase_7 == 1'b1) begin
          input_pipeline_phase7[0] <= input_typeconvert;
          input_pipeline_phase7[1] <= input_pipeline_phase7[0];
          input_pipeline_phase7[2] <= input_pipeline_phase7[1];
          input_pipeline_phase7[3] <= input_pipeline_phase7[2];
          input_pipeline_phase7[4] <= input_pipeline_phase7[3];
          input_pipeline_phase7[5] <= input_pipeline_phase7[4];
          input_pipeline_phase7[6] <= input_pipeline_phase7[5];
          input_pipeline_phase7[7] <= input_pipeline_phase7[6];
          input_pipeline_phase7[8] <= input_pipeline_phase7[7];
          input_pipeline_phase7[9] <= input_pipeline_phase7[8];
        end
      end
    end // Delay_Pipeline_Phase7_process


  assign mul_temp = input_typeconvert * coeffphase1_1;
  assign product_phase0_1 = mul_temp[127:64];

  assign mul_temp_1 = input_pipeline_phase0[0] * coeffphase1_2;
  assign product_phase0_2 = mul_temp_1[127:64];

  assign mul_temp_2 = input_pipeline_phase0[1] * coeffphase1_3;
  assign product_phase0_3 = mul_temp_2[127:64];

  assign mul_temp_3 = input_pipeline_phase0[2] * coeffphase1_4;
  assign product_phase0_4 = mul_temp_3[127:64];

  assign mul_temp_4 = input_pipeline_phase0[3] * coeffphase1_5;
  assign product_phase0_5 = mul_temp_4[127:64];

  assign mul_temp_5 = input_pipeline_phase0[4] * coeffphase1_6;
  assign product_phase0_6 = mul_temp_5[127:64];

  assign mul_temp_6 = input_pipeline_phase0[5] * coeffphase1_7;
  assign product_phase0_7 = mul_temp_6[127:64];

  assign mul_temp_7 = input_pipeline_phase0[6] * coeffphase1_8;
  assign product_phase0_8 = mul_temp_7[127:64];

  assign mul_temp_8 = input_pipeline_phase0[7] * coeffphase1_9;
  assign product_phase0_9 = mul_temp_8[127:64];

  assign mul_temp_9 = input_pipeline_phase0[8] * coeffphase1_10;
  assign product_phase0_10 = mul_temp_9[127:64];

  assign mul_temp_10 = input_pipeline_phase0[9] * coeffphase1_11;
  assign product_phase0_11 = mul_temp_10[127:64];

  assign mul_temp_11 = input_pipeline_phase1[0] * coeffphase2_1;
  assign product_phase1_1 = mul_temp_11[127:64];

  assign mul_temp_12 = input_pipeline_phase1[1] * coeffphase2_2;
  assign product_phase1_2 = mul_temp_12[127:64];

  assign mul_temp_13 = input_pipeline_phase1[2] * coeffphase2_3;
  assign product_phase1_3 = mul_temp_13[127:64];

  assign mul_temp_14 = input_pipeline_phase1[3] * coeffphase2_4;
  assign product_phase1_4 = mul_temp_14[127:64];

  assign mul_temp_15 = input_pipeline_phase1[4] * coeffphase2_5;
  assign product_phase1_5 = mul_temp_15[127:64];

  assign mul_temp_16 = input_pipeline_phase1[5] * coeffphase2_6;
  assign product_phase1_6 = mul_temp_16[127:64];

  assign mul_temp_17 = input_pipeline_phase1[6] * coeffphase2_7;
  assign product_phase1_7 = mul_temp_17[127:64];

  assign mul_temp_18 = input_pipeline_phase1[7] * coeffphase2_8;
  assign product_phase1_8 = mul_temp_18[127:64];

  assign mul_temp_19 = input_pipeline_phase1[8] * coeffphase2_9;
  assign product_phase1_9 = mul_temp_19[127:64];

  assign mul_temp_20 = input_pipeline_phase1[9] * coeffphase2_10;
  assign product_phase1_10 = mul_temp_20[127:64];

  assign mul_temp_21 = input_pipeline_phase2[0] * coeffphase3_1;
  assign product_phase2_1 = mul_temp_21[127:64];

  assign mul_temp_22 = input_pipeline_phase2[1] * coeffphase3_2;
  assign product_phase2_2 = mul_temp_22[127:64];

  assign mul_temp_23 = input_pipeline_phase2[2] * coeffphase3_3;
  assign product_phase2_3 = mul_temp_23[127:64];

  assign mul_temp_24 = input_pipeline_phase2[3] * coeffphase3_4;
  assign product_phase2_4 = mul_temp_24[127:64];

  assign mul_temp_25 = input_pipeline_phase2[4] * coeffphase3_5;
  assign product_phase2_5 = mul_temp_25[127:64];

  assign mul_temp_26 = input_pipeline_phase2[5] * coeffphase3_6;
  assign product_phase2_6 = mul_temp_26[127:64];

  assign mul_temp_27 = input_pipeline_phase2[6] * coeffphase3_7;
  assign product_phase2_7 = mul_temp_27[127:64];

  assign mul_temp_28 = input_pipeline_phase2[7] * coeffphase3_8;
  assign product_phase2_8 = mul_temp_28[127:64];

  assign mul_temp_29 = input_pipeline_phase2[8] * coeffphase3_9;
  assign product_phase2_9 = mul_temp_29[127:64];

  assign mul_temp_30 = input_pipeline_phase2[9] * coeffphase3_10;
  assign product_phase2_10 = mul_temp_30[127:64];

  assign mul_temp_31 = input_pipeline_phase3[0] * coeffphase4_1;
  assign product_phase3_1 = mul_temp_31[127:64];

  assign mul_temp_32 = input_pipeline_phase3[1] * coeffphase4_2;
  assign product_phase3_2 = mul_temp_32[127:64];

  assign mul_temp_33 = input_pipeline_phase3[2] * coeffphase4_3;
  assign product_phase3_3 = mul_temp_33[127:64];

  assign mul_temp_34 = input_pipeline_phase3[3] * coeffphase4_4;
  assign product_phase3_4 = mul_temp_34[127:64];

  assign mul_temp_35 = input_pipeline_phase3[4] * coeffphase4_5;
  assign product_phase3_5 = mul_temp_35[127:64];

  assign mul_temp_36 = input_pipeline_phase3[5] * coeffphase4_6;
  assign product_phase3_6 = mul_temp_36[127:64];

  assign mul_temp_37 = input_pipeline_phase3[6] * coeffphase4_7;
  assign product_phase3_7 = mul_temp_37[127:64];

  assign mul_temp_38 = input_pipeline_phase3[7] * coeffphase4_8;
  assign product_phase3_8 = mul_temp_38[127:64];

  assign mul_temp_39 = input_pipeline_phase3[8] * coeffphase4_9;
  assign product_phase3_9 = mul_temp_39[127:64];

  assign mul_temp_40 = input_pipeline_phase3[9] * coeffphase4_10;
  assign product_phase3_10 = mul_temp_40[127:64];

  assign mul_temp_41 = input_pipeline_phase4[0] * coeffphase5_1;
  assign product_phase4_1 = mul_temp_41[127:64];

  assign mul_temp_42 = input_pipeline_phase4[1] * coeffphase5_2;
  assign product_phase4_2 = mul_temp_42[127:64];

  assign mul_temp_43 = input_pipeline_phase4[2] * coeffphase5_3;
  assign product_phase4_3 = mul_temp_43[127:64];

  assign mul_temp_44 = input_pipeline_phase4[3] * coeffphase5_4;
  assign product_phase4_4 = mul_temp_44[127:64];

  assign mul_temp_45 = input_pipeline_phase4[4] * coeffphase5_5;
  assign product_phase4_5 = mul_temp_45[127:64];

  assign mul_temp_46 = input_pipeline_phase4[5] * coeffphase5_6;
  assign product_phase4_6 = mul_temp_46[127:64];

  assign mul_temp_47 = input_pipeline_phase4[6] * coeffphase5_7;
  assign product_phase4_7 = mul_temp_47[127:64];

  assign mul_temp_48 = input_pipeline_phase4[7] * coeffphase5_8;
  assign product_phase4_8 = mul_temp_48[127:64];

  assign mul_temp_49 = input_pipeline_phase4[8] * coeffphase5_9;
  assign product_phase4_9 = mul_temp_49[127:64];

  assign mul_temp_50 = input_pipeline_phase4[9] * coeffphase5_10;
  assign product_phase4_10 = mul_temp_50[127:64];

  assign mul_temp_51 = input_pipeline_phase5[0] * coeffphase6_1;
  assign product_phase5_1 = mul_temp_51[127:64];

  assign mul_temp_52 = input_pipeline_phase5[1] * coeffphase6_2;
  assign product_phase5_2 = mul_temp_52[127:64];

  assign mul_temp_53 = input_pipeline_phase5[2] * coeffphase6_3;
  assign product_phase5_3 = mul_temp_53[127:64];

  assign mul_temp_54 = input_pipeline_phase5[3] * coeffphase6_4;
  assign product_phase5_4 = mul_temp_54[127:64];

  assign mul_temp_55 = input_pipeline_phase5[4] * coeffphase6_5;
  assign product_phase5_5 = mul_temp_55[127:64];

  assign mul_temp_56 = input_pipeline_phase5[5] * coeffphase6_6;
  assign product_phase5_6 = mul_temp_56[127:64];

  assign mul_temp_57 = input_pipeline_phase5[6] * coeffphase6_7;
  assign product_phase5_7 = mul_temp_57[127:64];

  assign mul_temp_58 = input_pipeline_phase5[7] * coeffphase6_8;
  assign product_phase5_8 = mul_temp_58[127:64];

  assign mul_temp_59 = input_pipeline_phase5[8] * coeffphase6_9;
  assign product_phase5_9 = mul_temp_59[127:64];

  assign mul_temp_60 = input_pipeline_phase5[9] * coeffphase6_10;
  assign product_phase5_10 = mul_temp_60[127:64];

  assign mul_temp_61 = input_pipeline_phase6[0] * coeffphase7_1;
  assign product_phase6_1 = mul_temp_61[127:64];

  assign mul_temp_62 = input_pipeline_phase6[1] * coeffphase7_2;
  assign product_phase6_2 = mul_temp_62[127:64];

  assign mul_temp_63 = input_pipeline_phase6[2] * coeffphase7_3;
  assign product_phase6_3 = mul_temp_63[127:64];

  assign mul_temp_64 = input_pipeline_phase6[3] * coeffphase7_4;
  assign product_phase6_4 = mul_temp_64[127:64];

  assign mul_temp_65 = input_pipeline_phase6[4] * coeffphase7_5;
  assign product_phase6_5 = mul_temp_65[127:64];

  assign mul_temp_66 = input_pipeline_phase6[5] * coeffphase7_6;
  assign product_phase6_6 = mul_temp_66[127:64];

  assign mul_temp_67 = input_pipeline_phase6[6] * coeffphase7_7;
  assign product_phase6_7 = mul_temp_67[127:64];

  assign mul_temp_68 = input_pipeline_phase6[7] * coeffphase7_8;
  assign product_phase6_8 = mul_temp_68[127:64];

  assign mul_temp_69 = input_pipeline_phase6[8] * coeffphase7_9;
  assign product_phase6_9 = mul_temp_69[127:64];

  assign mul_temp_70 = input_pipeline_phase6[9] * coeffphase7_10;
  assign product_phase6_10 = mul_temp_70[127:64];

  assign mul_temp_71 = input_pipeline_phase7[0] * coeffphase8_1;
  assign product_phase7_1 = mul_temp_71[127:64];

  assign mul_temp_72 = input_pipeline_phase7[1] * coeffphase8_2;
  assign product_phase7_2 = mul_temp_72[127:64];

  assign mul_temp_73 = input_pipeline_phase7[2] * coeffphase8_3;
  assign product_phase7_3 = mul_temp_73[127:64];

  assign mul_temp_74 = input_pipeline_phase7[3] * coeffphase8_4;
  assign product_phase7_4 = mul_temp_74[127:64];

  assign mul_temp_75 = input_pipeline_phase7[4] * coeffphase8_5;
  assign product_phase7_5 = mul_temp_75[127:64];

  assign mul_temp_76 = input_pipeline_phase7[5] * coeffphase8_6;
  assign product_phase7_6 = mul_temp_76[127:64];

  assign mul_temp_77 = input_pipeline_phase7[6] * coeffphase8_7;
  assign product_phase7_7 = mul_temp_77[127:64];

  assign mul_temp_78 = input_pipeline_phase7[7] * coeffphase8_8;
  assign product_phase7_8 = mul_temp_78[127:64];

  assign mul_temp_79 = input_pipeline_phase7[8] * coeffphase8_9;
  assign product_phase7_9 = mul_temp_79[127:64];

  assign mul_temp_80 = input_pipeline_phase7[9] * coeffphase8_10;
  assign product_phase7_10 = mul_temp_80[127:64];

  assign quantized_sum = product_phase7_1;

  assign add_cast = quantized_sum;
  assign add_cast_1 = product_phase7_2;
  assign add_temp = add_cast + add_cast_1;
  assign sum1 = add_temp[63:0];

  assign add_cast_2 = sum1;
  assign add_cast_3 = product_phase7_3;
  assign add_temp_1 = add_cast_2 + add_cast_3;
  assign sum2 = add_temp_1[63:0];

  assign add_cast_4 = sum2;
  assign add_cast_5 = product_phase7_4;
  assign add_temp_2 = add_cast_4 + add_cast_5;
  assign sum3 = add_temp_2[63:0];

  assign add_cast_6 = sum3;
  assign add_cast_7 = product_phase7_5;
  assign add_temp_3 = add_cast_6 + add_cast_7;
  assign sum4 = add_temp_3[63:0];

  assign add_cast_8 = sum4;
  assign add_cast_9 = product_phase7_6;
  assign add_temp_4 = add_cast_8 + add_cast_9;
  assign sum5 = add_temp_4[63:0];

  assign add_cast_10 = sum5;
  assign add_cast_11 = product_phase7_7;
  assign add_temp_5 = add_cast_10 + add_cast_11;
  assign sum6 = add_temp_5[63:0];

  assign add_cast_12 = sum6;
  assign add_cast_13 = product_phase7_8;
  assign add_temp_6 = add_cast_12 + add_cast_13;
  assign sum7 = add_temp_6[63:0];

  assign add_cast_14 = sum7;
  assign add_cast_15 = product_phase7_9;
  assign add_temp_7 = add_cast_14 + add_cast_15;
  assign sum8 = add_temp_7[63:0];

  assign add_cast_16 = sum8;
  assign add_cast_17 = product_phase7_10;
  assign add_temp_8 = add_cast_16 + add_cast_17;
  assign sum9 = add_temp_8[63:0];

  assign add_cast_18 = sum9;
  assign add_cast_19 = product_phase6_1;
  assign add_temp_9 = add_cast_18 + add_cast_19;
  assign sum10 = add_temp_9[63:0];

  assign add_cast_20 = sum10;
  assign add_cast_21 = product_phase6_2;
  assign add_temp_10 = add_cast_20 + add_cast_21;
  assign sum11 = add_temp_10[63:0];

  assign add_cast_22 = sum11;
  assign add_cast_23 = product_phase6_3;
  assign add_temp_11 = add_cast_22 + add_cast_23;
  assign sum12 = add_temp_11[63:0];

  assign add_cast_24 = sum12;
  assign add_cast_25 = product_phase6_4;
  assign add_temp_12 = add_cast_24 + add_cast_25;
  assign sum13 = add_temp_12[63:0];

  assign add_cast_26 = sum13;
  assign add_cast_27 = product_phase6_5;
  assign add_temp_13 = add_cast_26 + add_cast_27;
  assign sum14 = add_temp_13[63:0];

  assign add_cast_28 = sum14;
  assign add_cast_29 = product_phase6_6;
  assign add_temp_14 = add_cast_28 + add_cast_29;
  assign sum15 = add_temp_14[63:0];

  assign add_cast_30 = sum15;
  assign add_cast_31 = product_phase6_7;
  assign add_temp_15 = add_cast_30 + add_cast_31;
  assign sum16 = add_temp_15[63:0];

  assign add_cast_32 = sum16;
  assign add_cast_33 = product_phase6_8;
  assign add_temp_16 = add_cast_32 + add_cast_33;
  assign sum17 = add_temp_16[63:0];

  assign add_cast_34 = sum17;
  assign add_cast_35 = product_phase6_9;
  assign add_temp_17 = add_cast_34 + add_cast_35;
  assign sum18 = add_temp_17[63:0];

  assign add_cast_36 = sum18;
  assign add_cast_37 = product_phase6_10;
  assign add_temp_18 = add_cast_36 + add_cast_37;
  assign sum19 = add_temp_18[63:0];

  assign add_cast_38 = sum19;
  assign add_cast_39 = product_phase5_1;
  assign add_temp_19 = add_cast_38 + add_cast_39;
  assign sum20 = add_temp_19[63:0];

  assign add_cast_40 = sum20;
  assign add_cast_41 = product_phase5_2;
  assign add_temp_20 = add_cast_40 + add_cast_41;
  assign sum21 = add_temp_20[63:0];

  assign add_cast_42 = sum21;
  assign add_cast_43 = product_phase5_3;
  assign add_temp_21 = add_cast_42 + add_cast_43;
  assign sum22 = add_temp_21[63:0];

  assign add_cast_44 = sum22;
  assign add_cast_45 = product_phase5_4;
  assign add_temp_22 = add_cast_44 + add_cast_45;
  assign sum23 = add_temp_22[63:0];

  assign add_cast_46 = sum23;
  assign add_cast_47 = product_phase5_5;
  assign add_temp_23 = add_cast_46 + add_cast_47;
  assign sum24 = add_temp_23[63:0];

  assign add_cast_48 = sum24;
  assign add_cast_49 = product_phase5_6;
  assign add_temp_24 = add_cast_48 + add_cast_49;
  assign sum25 = add_temp_24[63:0];

  assign add_cast_50 = sum25;
  assign add_cast_51 = product_phase5_7;
  assign add_temp_25 = add_cast_50 + add_cast_51;
  assign sum26 = add_temp_25[63:0];

  assign add_cast_52 = sum26;
  assign add_cast_53 = product_phase5_8;
  assign add_temp_26 = add_cast_52 + add_cast_53;
  assign sum27 = add_temp_26[63:0];

  assign add_cast_54 = sum27;
  assign add_cast_55 = product_phase5_9;
  assign add_temp_27 = add_cast_54 + add_cast_55;
  assign sum28 = add_temp_27[63:0];

  assign add_cast_56 = sum28;
  assign add_cast_57 = product_phase5_10;
  assign add_temp_28 = add_cast_56 + add_cast_57;
  assign sum29 = add_temp_28[63:0];

  assign add_cast_58 = sum29;
  assign add_cast_59 = product_phase4_1;
  assign add_temp_29 = add_cast_58 + add_cast_59;
  assign sum30 = add_temp_29[63:0];

  assign add_cast_60 = sum30;
  assign add_cast_61 = product_phase4_2;
  assign add_temp_30 = add_cast_60 + add_cast_61;
  assign sum31 = add_temp_30[63:0];

  assign add_cast_62 = sum31;
  assign add_cast_63 = product_phase4_3;
  assign add_temp_31 = add_cast_62 + add_cast_63;
  assign sum32 = add_temp_31[63:0];

  assign add_cast_64 = sum32;
  assign add_cast_65 = product_phase4_4;
  assign add_temp_32 = add_cast_64 + add_cast_65;
  assign sum33 = add_temp_32[63:0];

  assign add_cast_66 = sum33;
  assign add_cast_67 = product_phase4_5;
  assign add_temp_33 = add_cast_66 + add_cast_67;
  assign sum34 = add_temp_33[63:0];

  assign add_cast_68 = sum34;
  assign add_cast_69 = product_phase4_6;
  assign add_temp_34 = add_cast_68 + add_cast_69;
  assign sum35 = add_temp_34[63:0];

  assign add_cast_70 = sum35;
  assign add_cast_71 = product_phase4_7;
  assign add_temp_35 = add_cast_70 + add_cast_71;
  assign sum36 = add_temp_35[63:0];

  assign add_cast_72 = sum36;
  assign add_cast_73 = product_phase4_8;
  assign add_temp_36 = add_cast_72 + add_cast_73;
  assign sum37 = add_temp_36[63:0];

  assign add_cast_74 = sum37;
  assign add_cast_75 = product_phase4_9;
  assign add_temp_37 = add_cast_74 + add_cast_75;
  assign sum38 = add_temp_37[63:0];

  assign add_cast_76 = sum38;
  assign add_cast_77 = product_phase4_10;
  assign add_temp_38 = add_cast_76 + add_cast_77;
  assign sum39 = add_temp_38[63:0];

  assign add_cast_78 = sum39;
  assign add_cast_79 = product_phase3_1;
  assign add_temp_39 = add_cast_78 + add_cast_79;
  assign sum40 = add_temp_39[63:0];

  assign add_cast_80 = sum40;
  assign add_cast_81 = product_phase3_2;
  assign add_temp_40 = add_cast_80 + add_cast_81;
  assign sum41 = add_temp_40[63:0];

  assign add_cast_82 = sum41;
  assign add_cast_83 = product_phase3_3;
  assign add_temp_41 = add_cast_82 + add_cast_83;
  assign sum42 = add_temp_41[63:0];

  assign add_cast_84 = sum42;
  assign add_cast_85 = product_phase3_4;
  assign add_temp_42 = add_cast_84 + add_cast_85;
  assign sum43 = add_temp_42[63:0];

  assign add_cast_86 = sum43;
  assign add_cast_87 = product_phase3_5;
  assign add_temp_43 = add_cast_86 + add_cast_87;
  assign sum44 = add_temp_43[63:0];

  assign add_cast_88 = sum44;
  assign add_cast_89 = product_phase3_6;
  assign add_temp_44 = add_cast_88 + add_cast_89;
  assign sum45 = add_temp_44[63:0];

  assign add_cast_90 = sum45;
  assign add_cast_91 = product_phase3_7;
  assign add_temp_45 = add_cast_90 + add_cast_91;
  assign sum46 = add_temp_45[63:0];

  assign add_cast_92 = sum46;
  assign add_cast_93 = product_phase3_8;
  assign add_temp_46 = add_cast_92 + add_cast_93;
  assign sum47 = add_temp_46[63:0];

  assign add_cast_94 = sum47;
  assign add_cast_95 = product_phase3_9;
  assign add_temp_47 = add_cast_94 + add_cast_95;
  assign sum48 = add_temp_47[63:0];

  assign add_cast_96 = sum48;
  assign add_cast_97 = product_phase3_10;
  assign add_temp_48 = add_cast_96 + add_cast_97;
  assign sum49 = add_temp_48[63:0];

  assign add_cast_98 = sum49;
  assign add_cast_99 = product_phase2_1;
  assign add_temp_49 = add_cast_98 + add_cast_99;
  assign sum50 = add_temp_49[63:0];

  assign add_cast_100 = sum50;
  assign add_cast_101 = product_phase2_2;
  assign add_temp_50 = add_cast_100 + add_cast_101;
  assign sum51 = add_temp_50[63:0];

  assign add_cast_102 = sum51;
  assign add_cast_103 = product_phase2_3;
  assign add_temp_51 = add_cast_102 + add_cast_103;
  assign sum52 = add_temp_51[63:0];

  assign add_cast_104 = sum52;
  assign add_cast_105 = product_phase2_4;
  assign add_temp_52 = add_cast_104 + add_cast_105;
  assign sum53 = add_temp_52[63:0];

  assign add_cast_106 = sum53;
  assign add_cast_107 = product_phase2_5;
  assign add_temp_53 = add_cast_106 + add_cast_107;
  assign sum54 = add_temp_53[63:0];

  assign add_cast_108 = sum54;
  assign add_cast_109 = product_phase2_6;
  assign add_temp_54 = add_cast_108 + add_cast_109;
  assign sum55 = add_temp_54[63:0];

  assign add_cast_110 = sum55;
  assign add_cast_111 = product_phase2_7;
  assign add_temp_55 = add_cast_110 + add_cast_111;
  assign sum56 = add_temp_55[63:0];

  assign add_cast_112 = sum56;
  assign add_cast_113 = product_phase2_8;
  assign add_temp_56 = add_cast_112 + add_cast_113;
  assign sum57 = add_temp_56[63:0];

  assign add_cast_114 = sum57;
  assign add_cast_115 = product_phase2_9;
  assign add_temp_57 = add_cast_114 + add_cast_115;
  assign sum58 = add_temp_57[63:0];

  assign add_cast_116 = sum58;
  assign add_cast_117 = product_phase2_10;
  assign add_temp_58 = add_cast_116 + add_cast_117;
  assign sum59 = add_temp_58[63:0];

  assign add_cast_118 = sum59;
  assign add_cast_119 = product_phase1_1;
  assign add_temp_59 = add_cast_118 + add_cast_119;
  assign sum60 = add_temp_59[63:0];

  assign add_cast_120 = sum60;
  assign add_cast_121 = product_phase1_2;
  assign add_temp_60 = add_cast_120 + add_cast_121;
  assign sum61 = add_temp_60[63:0];

  assign add_cast_122 = sum61;
  assign add_cast_123 = product_phase1_3;
  assign add_temp_61 = add_cast_122 + add_cast_123;
  assign sum62 = add_temp_61[63:0];

  assign add_cast_124 = sum62;
  assign add_cast_125 = product_phase1_4;
  assign add_temp_62 = add_cast_124 + add_cast_125;
  assign sum63 = add_temp_62[63:0];

  assign add_cast_126 = sum63;
  assign add_cast_127 = product_phase1_5;
  assign add_temp_63 = add_cast_126 + add_cast_127;
  assign sum64 = add_temp_63[63:0];

  assign add_cast_128 = sum64;
  assign add_cast_129 = product_phase1_6;
  assign add_temp_64 = add_cast_128 + add_cast_129;
  assign sum65 = add_temp_64[63:0];

  assign add_cast_130 = sum65;
  assign add_cast_131 = product_phase1_7;
  assign add_temp_65 = add_cast_130 + add_cast_131;
  assign sum66 = add_temp_65[63:0];

  assign add_cast_132 = sum66;
  assign add_cast_133 = product_phase1_8;
  assign add_temp_66 = add_cast_132 + add_cast_133;
  assign sum67 = add_temp_66[63:0];

  assign add_cast_134 = sum67;
  assign add_cast_135 = product_phase1_9;
  assign add_temp_67 = add_cast_134 + add_cast_135;
  assign sum68 = add_temp_67[63:0];

  assign add_cast_136 = sum68;
  assign add_cast_137 = product_phase1_10;
  assign add_temp_68 = add_cast_136 + add_cast_137;
  assign sum69 = add_temp_68[63:0];

  assign add_cast_138 = sum69;
  assign add_cast_139 = product_phase0_1;
  assign add_temp_69 = add_cast_138 + add_cast_139;
  assign sum70 = add_temp_69[63:0];

  assign add_cast_140 = sum70;
  assign add_cast_141 = product_phase0_2;
  assign add_temp_70 = add_cast_140 + add_cast_141;
  assign sum71 = add_temp_70[63:0];

  assign add_cast_142 = sum71;
  assign add_cast_143 = product_phase0_3;
  assign add_temp_71 = add_cast_142 + add_cast_143;
  assign sum72 = add_temp_71[63:0];

  assign add_cast_144 = sum72;
  assign add_cast_145 = product_phase0_4;
  assign add_temp_72 = add_cast_144 + add_cast_145;
  assign sum73 = add_temp_72[63:0];

  assign add_cast_146 = sum73;
  assign add_cast_147 = product_phase0_5;
  assign add_temp_73 = add_cast_146 + add_cast_147;
  assign sum74 = add_temp_73[63:0];

  assign add_cast_148 = sum74;
  assign add_cast_149 = product_phase0_6;
  assign add_temp_74 = add_cast_148 + add_cast_149;
  assign sum75 = add_temp_74[63:0];

  assign add_cast_150 = sum75;
  assign add_cast_151 = product_phase0_7;
  assign add_temp_75 = add_cast_150 + add_cast_151;
  assign sum76 = add_temp_75[63:0];

  assign add_cast_152 = sum76;
  assign add_cast_153 = product_phase0_8;
  assign add_temp_76 = add_cast_152 + add_cast_153;
  assign sum77 = add_temp_76[63:0];

  assign add_cast_154 = sum77;
  assign add_cast_155 = product_phase0_9;
  assign add_temp_77 = add_cast_154 + add_cast_155;
  assign sum78 = add_temp_77[63:0];

  assign add_cast_156 = sum78;
  assign add_cast_157 = product_phase0_10;
  assign add_temp_78 = add_cast_156 + add_cast_157;
  assign sum79 = add_temp_78[63:0];

  assign add_cast_158 = sum79;
  assign add_cast_159 = product_phase0_11;
  assign add_temp_79 = add_cast_158 + add_cast_159;
  assign sum80 = add_temp_79[63:0];

  always @ (posedge clk or posedge reset)
    begin: DataHoldRegister_process
      if (reset == 1'b1) begin
        regout <= 0;
      end
      else begin
        if (phase_0 == 1'b1) begin
          regout <= sum80;
        end
      end
    end // DataHoldRegister_process

  assign muxout = (phase_0 == 1'b1) ? sum80 :
            regout;
  // Assignment Statements
  assign FIR_Decimation_out = muxout;
endmodule  // FIR_Decimation
